/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyUploadSymbolApiGamificationSymbolsUploadPost,
  ErrorResponse,
  ListMapBoardsApiGamificationMapBoardsGetParams,
  ListSymbolsApiGamificationSymbolsGetParams,
  MapBoardCreate,
  MapBoardRead,
  MapBoardUpdate,
  TopographicSymbolCreate,
  TopographicSymbolRead,
  TopographicSymbolUpdate,
  UploadSymbolApiGamificationSymbolsUploadPostParams
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new map board.
 * @summary Create Map Board
 */
export type createMapBoardApiGamificationMapBoardsPostResponse201 = {
  data: MapBoardRead
  status: 201
}

export type createMapBoardApiGamificationMapBoardsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createMapBoardApiGamificationMapBoardsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createMapBoardApiGamificationMapBoardsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createMapBoardApiGamificationMapBoardsPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createMapBoardApiGamificationMapBoardsPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type createMapBoardApiGamificationMapBoardsPostResponseSuccess = (createMapBoardApiGamificationMapBoardsPostResponse201) & {
  headers: Headers;
};
export type createMapBoardApiGamificationMapBoardsPostResponseError = (createMapBoardApiGamificationMapBoardsPostResponse401 | createMapBoardApiGamificationMapBoardsPostResponse403 | createMapBoardApiGamificationMapBoardsPostResponse404 | createMapBoardApiGamificationMapBoardsPostResponse422 | createMapBoardApiGamificationMapBoardsPostResponse429) & {
  headers: Headers;
};

export type createMapBoardApiGamificationMapBoardsPostResponse = (createMapBoardApiGamificationMapBoardsPostResponseSuccess | createMapBoardApiGamificationMapBoardsPostResponseError)

export const getCreateMapBoardApiGamificationMapBoardsPostUrl = () => {


  

  return `/api/gamification/map-boards`
}

export const createMapBoardApiGamificationMapBoardsPost = async (mapBoardCreate: MapBoardCreate, options?: RequestInit): Promise<createMapBoardApiGamificationMapBoardsPostResponse> => {
  
  return customInstance<createMapBoardApiGamificationMapBoardsPostResponse>(getCreateMapBoardApiGamificationMapBoardsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mapBoardCreate,)
  }
);}




export const getCreateMapBoardApiGamificationMapBoardsPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMapBoardApiGamificationMapBoardsPost>>, TError,{data: MapBoardCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createMapBoardApiGamificationMapBoardsPost>>, TError,{data: MapBoardCreate}, TContext> => {

const mutationKey = ['createMapBoardApiGamificationMapBoardsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMapBoardApiGamificationMapBoardsPost>>, {data: MapBoardCreate}> = (props) => {
          const {data} = props ?? {};

          return  createMapBoardApiGamificationMapBoardsPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMapBoardApiGamificationMapBoardsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createMapBoardApiGamificationMapBoardsPost>>>
    export type CreateMapBoardApiGamificationMapBoardsPostMutationBody = MapBoardCreate
    export type CreateMapBoardApiGamificationMapBoardsPostMutationError = ErrorResponse

    /**
 * @summary Create Map Board
 */
export const useCreateMapBoardApiGamificationMapBoardsPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMapBoardApiGamificationMapBoardsPost>>, TError,{data: MapBoardCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMapBoardApiGamificationMapBoardsPost>>,
        TError,
        {data: MapBoardCreate},
        TContext
      > => {
      return useMutation(getCreateMapBoardApiGamificationMapBoardsPostMutationOptions(options), queryClient);
    }
    /**
 * List all map boards.
 * @summary List Map Boards
 */
export type listMapBoardsApiGamificationMapBoardsGetResponse200 = {
  data: MapBoardRead[]
  status: 200
}

export type listMapBoardsApiGamificationMapBoardsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listMapBoardsApiGamificationMapBoardsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listMapBoardsApiGamificationMapBoardsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listMapBoardsApiGamificationMapBoardsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listMapBoardsApiGamificationMapBoardsGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listMapBoardsApiGamificationMapBoardsGetResponseSuccess = (listMapBoardsApiGamificationMapBoardsGetResponse200) & {
  headers: Headers;
};
export type listMapBoardsApiGamificationMapBoardsGetResponseError = (listMapBoardsApiGamificationMapBoardsGetResponse401 | listMapBoardsApiGamificationMapBoardsGetResponse403 | listMapBoardsApiGamificationMapBoardsGetResponse404 | listMapBoardsApiGamificationMapBoardsGetResponse422 | listMapBoardsApiGamificationMapBoardsGetResponse429) & {
  headers: Headers;
};

export type listMapBoardsApiGamificationMapBoardsGetResponse = (listMapBoardsApiGamificationMapBoardsGetResponseSuccess | listMapBoardsApiGamificationMapBoardsGetResponseError)

export const getListMapBoardsApiGamificationMapBoardsGetUrl = (params?: ListMapBoardsApiGamificationMapBoardsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/gamification/map-boards?${stringifiedParams}` : `/api/gamification/map-boards`
}

export const listMapBoardsApiGamificationMapBoardsGet = async (params?: ListMapBoardsApiGamificationMapBoardsGetParams, options?: RequestInit): Promise<listMapBoardsApiGamificationMapBoardsGetResponse> => {
  
  return customInstance<listMapBoardsApiGamificationMapBoardsGetResponse>(getListMapBoardsApiGamificationMapBoardsGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListMapBoardsApiGamificationMapBoardsGetQueryKey = (params?: ListMapBoardsApiGamificationMapBoardsGetParams,) => {
    return [
    `/api/gamification/map-boards`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListMapBoardsApiGamificationMapBoardsGetQueryOptions = <TData = Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError = ErrorResponse>(params?: ListMapBoardsApiGamificationMapBoardsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMapBoardsApiGamificationMapBoardsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>> = ({ signal }) => listMapBoardsApiGamificationMapBoardsGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListMapBoardsApiGamificationMapBoardsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>>
export type ListMapBoardsApiGamificationMapBoardsGetQueryError = ErrorResponse


export function useListMapBoardsApiGamificationMapBoardsGet<TData = Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError = ErrorResponse>(
 params: undefined |  ListMapBoardsApiGamificationMapBoardsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>,
          TError,
          Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMapBoardsApiGamificationMapBoardsGet<TData = Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError = ErrorResponse>(
 params?: ListMapBoardsApiGamificationMapBoardsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>,
          TError,
          Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListMapBoardsApiGamificationMapBoardsGet<TData = Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError = ErrorResponse>(
 params?: ListMapBoardsApiGamificationMapBoardsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Map Boards
 */

export function useListMapBoardsApiGamificationMapBoardsGet<TData = Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError = ErrorResponse>(
 params?: ListMapBoardsApiGamificationMapBoardsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listMapBoardsApiGamificationMapBoardsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListMapBoardsApiGamificationMapBoardsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get map board by ID.
 * @summary Get Map Board
 */
export type getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse200 = {
  data: MapBoardRead
  status: 200
}

export type getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getMapBoardApiGamificationMapBoardsMapBoardIdGetResponseSuccess = (getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse200) & {
  headers: Headers;
};
export type getMapBoardApiGamificationMapBoardsMapBoardIdGetResponseError = (getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse401 | getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse403 | getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse404 | getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse422 | getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse429) & {
  headers: Headers;
};

export type getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse = (getMapBoardApiGamificationMapBoardsMapBoardIdGetResponseSuccess | getMapBoardApiGamificationMapBoardsMapBoardIdGetResponseError)

export const getGetMapBoardApiGamificationMapBoardsMapBoardIdGetUrl = (mapBoardId: number,) => {


  

  return `/api/gamification/map-boards/${mapBoardId}`
}

export const getMapBoardApiGamificationMapBoardsMapBoardIdGet = async (mapBoardId: number, options?: RequestInit): Promise<getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse> => {
  
  return customInstance<getMapBoardApiGamificationMapBoardsMapBoardIdGetResponse>(getGetMapBoardApiGamificationMapBoardsMapBoardIdGetUrl(mapBoardId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMapBoardApiGamificationMapBoardsMapBoardIdGetQueryKey = (mapBoardId: number,) => {
    return [
    `/api/gamification/map-boards/${mapBoardId}`
    ] as const;
    }

    
export const getGetMapBoardApiGamificationMapBoardsMapBoardIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError = ErrorResponse>(mapBoardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMapBoardApiGamificationMapBoardsMapBoardIdGetQueryKey(mapBoardId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>> = ({ signal }) => getMapBoardApiGamificationMapBoardsMapBoardIdGet(mapBoardId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(mapBoardId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMapBoardApiGamificationMapBoardsMapBoardIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>>
export type GetMapBoardApiGamificationMapBoardsMapBoardIdGetQueryError = ErrorResponse


export function useGetMapBoardApiGamificationMapBoardsMapBoardIdGet<TData = Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError = ErrorResponse>(
 mapBoardId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapBoardApiGamificationMapBoardsMapBoardIdGet<TData = Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError = ErrorResponse>(
 mapBoardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>,
          TError,
          Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapBoardApiGamificationMapBoardsMapBoardIdGet<TData = Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError = ErrorResponse>(
 mapBoardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Map Board
 */

export function useGetMapBoardApiGamificationMapBoardsMapBoardIdGet<TData = Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError = ErrorResponse>(
 mapBoardId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapBoardApiGamificationMapBoardsMapBoardIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMapBoardApiGamificationMapBoardsMapBoardIdGetQueryOptions(mapBoardId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update map board.
 * @summary Update Map Board
 */
export type updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse200 = {
  data: MapBoardRead
  status: 200
}

export type updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponseSuccess = (updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse200) & {
  headers: Headers;
};
export type updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponseError = (updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse401 | updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse403 | updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse404 | updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse422 | updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse429) & {
  headers: Headers;
};

export type updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse = (updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponseSuccess | updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponseError)

export const getUpdateMapBoardApiGamificationMapBoardsMapBoardIdPutUrl = (mapBoardId: number,) => {


  

  return `/api/gamification/map-boards/${mapBoardId}`
}

export const updateMapBoardApiGamificationMapBoardsMapBoardIdPut = async (mapBoardId: number,
    mapBoardUpdate: MapBoardUpdate, options?: RequestInit): Promise<updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse> => {
  
  return customInstance<updateMapBoardApiGamificationMapBoardsMapBoardIdPutResponse>(getUpdateMapBoardApiGamificationMapBoardsMapBoardIdPutUrl(mapBoardId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mapBoardUpdate,)
  }
);}




export const getUpdateMapBoardApiGamificationMapBoardsMapBoardIdPutMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMapBoardApiGamificationMapBoardsMapBoardIdPut>>, TError,{mapBoardId: number;data: MapBoardUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMapBoardApiGamificationMapBoardsMapBoardIdPut>>, TError,{mapBoardId: number;data: MapBoardUpdate}, TContext> => {

const mutationKey = ['updateMapBoardApiGamificationMapBoardsMapBoardIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMapBoardApiGamificationMapBoardsMapBoardIdPut>>, {mapBoardId: number;data: MapBoardUpdate}> = (props) => {
          const {mapBoardId,data} = props ?? {};

          return  updateMapBoardApiGamificationMapBoardsMapBoardIdPut(mapBoardId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMapBoardApiGamificationMapBoardsMapBoardIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateMapBoardApiGamificationMapBoardsMapBoardIdPut>>>
    export type UpdateMapBoardApiGamificationMapBoardsMapBoardIdPutMutationBody = MapBoardUpdate
    export type UpdateMapBoardApiGamificationMapBoardsMapBoardIdPutMutationError = ErrorResponse

    /**
 * @summary Update Map Board
 */
export const useUpdateMapBoardApiGamificationMapBoardsMapBoardIdPut = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMapBoardApiGamificationMapBoardsMapBoardIdPut>>, TError,{mapBoardId: number;data: MapBoardUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMapBoardApiGamificationMapBoardsMapBoardIdPut>>,
        TError,
        {mapBoardId: number;data: MapBoardUpdate},
        TContext
      > => {
      return useMutation(getUpdateMapBoardApiGamificationMapBoardsMapBoardIdPutMutationOptions(options), queryClient);
    }
    /**
 * Delete a map board.
 * @summary Delete Map Board
 */
export type deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse422 = {
  data: ErrorResponse
  status: 422
}

export type deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponseSuccess = (deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponseError = (deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse401 | deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse403 | deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse404 | deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse422 | deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse429) & {
  headers: Headers;
};

export type deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse = (deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponseSuccess | deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponseError)

export const getDeleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteUrl = (mapBoardId: number,) => {


  

  return `/api/gamification/map-boards/${mapBoardId}`
}

export const deleteMapBoardApiGamificationMapBoardsMapBoardIdDelete = async (mapBoardId: number, options?: RequestInit): Promise<deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse> => {
  
  return customInstance<deleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteResponse>(getDeleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteUrl(mapBoardId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMapBoardApiGamificationMapBoardsMapBoardIdDelete>>, TError,{mapBoardId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMapBoardApiGamificationMapBoardsMapBoardIdDelete>>, TError,{mapBoardId: number}, TContext> => {

const mutationKey = ['deleteMapBoardApiGamificationMapBoardsMapBoardIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMapBoardApiGamificationMapBoardsMapBoardIdDelete>>, {mapBoardId: number}> = (props) => {
          const {mapBoardId} = props ?? {};

          return  deleteMapBoardApiGamificationMapBoardsMapBoardIdDelete(mapBoardId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMapBoardApiGamificationMapBoardsMapBoardIdDelete>>>
    
    export type DeleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteMutationError = ErrorResponse

    /**
 * @summary Delete Map Board
 */
export const useDeleteMapBoardApiGamificationMapBoardsMapBoardIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMapBoardApiGamificationMapBoardsMapBoardIdDelete>>, TError,{mapBoardId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMapBoardApiGamificationMapBoardsMapBoardIdDelete>>,
        TError,
        {mapBoardId: number},
        TContext
      > => {
      return useMutation(getDeleteMapBoardApiGamificationMapBoardsMapBoardIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * List all topographic symbols.
 * @summary List Symbols
 */
export type listSymbolsApiGamificationSymbolsGetResponse200 = {
  data: TopographicSymbolRead[]
  status: 200
}

export type listSymbolsApiGamificationSymbolsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listSymbolsApiGamificationSymbolsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listSymbolsApiGamificationSymbolsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listSymbolsApiGamificationSymbolsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listSymbolsApiGamificationSymbolsGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listSymbolsApiGamificationSymbolsGetResponseSuccess = (listSymbolsApiGamificationSymbolsGetResponse200) & {
  headers: Headers;
};
export type listSymbolsApiGamificationSymbolsGetResponseError = (listSymbolsApiGamificationSymbolsGetResponse401 | listSymbolsApiGamificationSymbolsGetResponse403 | listSymbolsApiGamificationSymbolsGetResponse404 | listSymbolsApiGamificationSymbolsGetResponse422 | listSymbolsApiGamificationSymbolsGetResponse429) & {
  headers: Headers;
};

export type listSymbolsApiGamificationSymbolsGetResponse = (listSymbolsApiGamificationSymbolsGetResponseSuccess | listSymbolsApiGamificationSymbolsGetResponseError)

export const getListSymbolsApiGamificationSymbolsGetUrl = (params?: ListSymbolsApiGamificationSymbolsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/gamification/symbols?${stringifiedParams}` : `/api/gamification/symbols`
}

export const listSymbolsApiGamificationSymbolsGet = async (params?: ListSymbolsApiGamificationSymbolsGetParams, options?: RequestInit): Promise<listSymbolsApiGamificationSymbolsGetResponse> => {
  
  return customInstance<listSymbolsApiGamificationSymbolsGetResponse>(getListSymbolsApiGamificationSymbolsGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListSymbolsApiGamificationSymbolsGetQueryKey = (params?: ListSymbolsApiGamificationSymbolsGetParams,) => {
    return [
    `/api/gamification/symbols`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListSymbolsApiGamificationSymbolsGetQueryOptions = <TData = Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError = ErrorResponse>(params?: ListSymbolsApiGamificationSymbolsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSymbolsApiGamificationSymbolsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>> = ({ signal }) => listSymbolsApiGamificationSymbolsGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSymbolsApiGamificationSymbolsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>>
export type ListSymbolsApiGamificationSymbolsGetQueryError = ErrorResponse


export function useListSymbolsApiGamificationSymbolsGet<TData = Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError = ErrorResponse>(
 params: undefined |  ListSymbolsApiGamificationSymbolsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>,
          TError,
          Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSymbolsApiGamificationSymbolsGet<TData = Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError = ErrorResponse>(
 params?: ListSymbolsApiGamificationSymbolsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>,
          TError,
          Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSymbolsApiGamificationSymbolsGet<TData = Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError = ErrorResponse>(
 params?: ListSymbolsApiGamificationSymbolsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Symbols
 */

export function useListSymbolsApiGamificationSymbolsGet<TData = Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError = ErrorResponse>(
 params?: ListSymbolsApiGamificationSymbolsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSymbolsApiGamificationSymbolsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSymbolsApiGamificationSymbolsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new symbol (JSON).
Use this for EDITOR type symbols.
 * @summary Create Symbol
 */
export type createSymbolApiGamificationSymbolsPostResponse201 = {
  data: TopographicSymbolRead
  status: 201
}

export type createSymbolApiGamificationSymbolsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createSymbolApiGamificationSymbolsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createSymbolApiGamificationSymbolsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createSymbolApiGamificationSymbolsPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createSymbolApiGamificationSymbolsPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type createSymbolApiGamificationSymbolsPostResponseSuccess = (createSymbolApiGamificationSymbolsPostResponse201) & {
  headers: Headers;
};
export type createSymbolApiGamificationSymbolsPostResponseError = (createSymbolApiGamificationSymbolsPostResponse401 | createSymbolApiGamificationSymbolsPostResponse403 | createSymbolApiGamificationSymbolsPostResponse404 | createSymbolApiGamificationSymbolsPostResponse422 | createSymbolApiGamificationSymbolsPostResponse429) & {
  headers: Headers;
};

export type createSymbolApiGamificationSymbolsPostResponse = (createSymbolApiGamificationSymbolsPostResponseSuccess | createSymbolApiGamificationSymbolsPostResponseError)

export const getCreateSymbolApiGamificationSymbolsPostUrl = () => {


  

  return `/api/gamification/symbols`
}

export const createSymbolApiGamificationSymbolsPost = async (topographicSymbolCreate: TopographicSymbolCreate, options?: RequestInit): Promise<createSymbolApiGamificationSymbolsPostResponse> => {
  
  return customInstance<createSymbolApiGamificationSymbolsPostResponse>(getCreateSymbolApiGamificationSymbolsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      topographicSymbolCreate,)
  }
);}




export const getCreateSymbolApiGamificationSymbolsPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSymbolApiGamificationSymbolsPost>>, TError,{data: TopographicSymbolCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSymbolApiGamificationSymbolsPost>>, TError,{data: TopographicSymbolCreate}, TContext> => {

const mutationKey = ['createSymbolApiGamificationSymbolsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSymbolApiGamificationSymbolsPost>>, {data: TopographicSymbolCreate}> = (props) => {
          const {data} = props ?? {};

          return  createSymbolApiGamificationSymbolsPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSymbolApiGamificationSymbolsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createSymbolApiGamificationSymbolsPost>>>
    export type CreateSymbolApiGamificationSymbolsPostMutationBody = TopographicSymbolCreate
    export type CreateSymbolApiGamificationSymbolsPostMutationError = ErrorResponse

    /**
 * @summary Create Symbol
 */
export const useCreateSymbolApiGamificationSymbolsPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSymbolApiGamificationSymbolsPost>>, TError,{data: TopographicSymbolCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSymbolApiGamificationSymbolsPost>>,
        TError,
        {data: TopographicSymbolCreate},
        TContext
      > => {
      return useMutation(getCreateSymbolApiGamificationSymbolsPostMutationOptions(options), queryClient);
    }
    /**
 * Upload a symbol image with linked attachment.
 * @summary Upload Symbol
 */
export type uploadSymbolApiGamificationSymbolsUploadPostResponse201 = {
  data: TopographicSymbolRead
  status: 201
}

export type uploadSymbolApiGamificationSymbolsUploadPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type uploadSymbolApiGamificationSymbolsUploadPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type uploadSymbolApiGamificationSymbolsUploadPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type uploadSymbolApiGamificationSymbolsUploadPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type uploadSymbolApiGamificationSymbolsUploadPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type uploadSymbolApiGamificationSymbolsUploadPostResponseSuccess = (uploadSymbolApiGamificationSymbolsUploadPostResponse201) & {
  headers: Headers;
};
export type uploadSymbolApiGamificationSymbolsUploadPostResponseError = (uploadSymbolApiGamificationSymbolsUploadPostResponse401 | uploadSymbolApiGamificationSymbolsUploadPostResponse403 | uploadSymbolApiGamificationSymbolsUploadPostResponse404 | uploadSymbolApiGamificationSymbolsUploadPostResponse422 | uploadSymbolApiGamificationSymbolsUploadPostResponse429) & {
  headers: Headers;
};

export type uploadSymbolApiGamificationSymbolsUploadPostResponse = (uploadSymbolApiGamificationSymbolsUploadPostResponseSuccess | uploadSymbolApiGamificationSymbolsUploadPostResponseError)

export const getUploadSymbolApiGamificationSymbolsUploadPostUrl = (params?: UploadSymbolApiGamificationSymbolsUploadPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/gamification/symbols/upload?${stringifiedParams}` : `/api/gamification/symbols/upload`
}

export const uploadSymbolApiGamificationSymbolsUploadPost = async (bodyUploadSymbolApiGamificationSymbolsUploadPost: BodyUploadSymbolApiGamificationSymbolsUploadPost,
    params?: UploadSymbolApiGamificationSymbolsUploadPostParams, options?: RequestInit): Promise<uploadSymbolApiGamificationSymbolsUploadPostResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadSymbolApiGamificationSymbolsUploadPost.file);

  return customInstance<uploadSymbolApiGamificationSymbolsUploadPostResponse>(getUploadSymbolApiGamificationSymbolsUploadPostUrl(params),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadSymbolApiGamificationSymbolsUploadPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadSymbolApiGamificationSymbolsUploadPost>>, TError,{data: BodyUploadSymbolApiGamificationSymbolsUploadPost;params?: UploadSymbolApiGamificationSymbolsUploadPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadSymbolApiGamificationSymbolsUploadPost>>, TError,{data: BodyUploadSymbolApiGamificationSymbolsUploadPost;params?: UploadSymbolApiGamificationSymbolsUploadPostParams}, TContext> => {

const mutationKey = ['uploadSymbolApiGamificationSymbolsUploadPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadSymbolApiGamificationSymbolsUploadPost>>, {data: BodyUploadSymbolApiGamificationSymbolsUploadPost;params?: UploadSymbolApiGamificationSymbolsUploadPostParams}> = (props) => {
          const {data,params} = props ?? {};

          return  uploadSymbolApiGamificationSymbolsUploadPost(data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadSymbolApiGamificationSymbolsUploadPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadSymbolApiGamificationSymbolsUploadPost>>>
    export type UploadSymbolApiGamificationSymbolsUploadPostMutationBody = BodyUploadSymbolApiGamificationSymbolsUploadPost
    export type UploadSymbolApiGamificationSymbolsUploadPostMutationError = ErrorResponse

    /**
 * @summary Upload Symbol
 */
export const useUploadSymbolApiGamificationSymbolsUploadPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadSymbolApiGamificationSymbolsUploadPost>>, TError,{data: BodyUploadSymbolApiGamificationSymbolsUploadPost;params?: UploadSymbolApiGamificationSymbolsUploadPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadSymbolApiGamificationSymbolsUploadPost>>,
        TError,
        {data: BodyUploadSymbolApiGamificationSymbolsUploadPost;params?: UploadSymbolApiGamificationSymbolsUploadPostParams},
        TContext
      > => {
      return useMutation(getUploadSymbolApiGamificationSymbolsUploadPostMutationOptions(options), queryClient);
    }
    /**
 * Get topographic symbol by ID.
 * @summary Get Symbol
 */
export type getSymbolApiGamificationSymbolsSymbolIdGetResponse200 = {
  data: TopographicSymbolRead
  status: 200
}

export type getSymbolApiGamificationSymbolsSymbolIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getSymbolApiGamificationSymbolsSymbolIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getSymbolApiGamificationSymbolsSymbolIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getSymbolApiGamificationSymbolsSymbolIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getSymbolApiGamificationSymbolsSymbolIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getSymbolApiGamificationSymbolsSymbolIdGetResponseSuccess = (getSymbolApiGamificationSymbolsSymbolIdGetResponse200) & {
  headers: Headers;
};
export type getSymbolApiGamificationSymbolsSymbolIdGetResponseError = (getSymbolApiGamificationSymbolsSymbolIdGetResponse401 | getSymbolApiGamificationSymbolsSymbolIdGetResponse403 | getSymbolApiGamificationSymbolsSymbolIdGetResponse404 | getSymbolApiGamificationSymbolsSymbolIdGetResponse422 | getSymbolApiGamificationSymbolsSymbolIdGetResponse429) & {
  headers: Headers;
};

export type getSymbolApiGamificationSymbolsSymbolIdGetResponse = (getSymbolApiGamificationSymbolsSymbolIdGetResponseSuccess | getSymbolApiGamificationSymbolsSymbolIdGetResponseError)

export const getGetSymbolApiGamificationSymbolsSymbolIdGetUrl = (symbolId: number,) => {


  

  return `/api/gamification/symbols/${symbolId}`
}

export const getSymbolApiGamificationSymbolsSymbolIdGet = async (symbolId: number, options?: RequestInit): Promise<getSymbolApiGamificationSymbolsSymbolIdGetResponse> => {
  
  return customInstance<getSymbolApiGamificationSymbolsSymbolIdGetResponse>(getGetSymbolApiGamificationSymbolsSymbolIdGetUrl(symbolId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSymbolApiGamificationSymbolsSymbolIdGetQueryKey = (symbolId: number,) => {
    return [
    `/api/gamification/symbols/${symbolId}`
    ] as const;
    }

    
export const getGetSymbolApiGamificationSymbolsSymbolIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError = ErrorResponse>(symbolId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSymbolApiGamificationSymbolsSymbolIdGetQueryKey(symbolId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>> = ({ signal }) => getSymbolApiGamificationSymbolsSymbolIdGet(symbolId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(symbolId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSymbolApiGamificationSymbolsSymbolIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>>
export type GetSymbolApiGamificationSymbolsSymbolIdGetQueryError = ErrorResponse


export function useGetSymbolApiGamificationSymbolsSymbolIdGet<TData = Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError = ErrorResponse>(
 symbolId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSymbolApiGamificationSymbolsSymbolIdGet<TData = Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError = ErrorResponse>(
 symbolId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSymbolApiGamificationSymbolsSymbolIdGet<TData = Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError = ErrorResponse>(
 symbolId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Symbol
 */

export function useGetSymbolApiGamificationSymbolsSymbolIdGet<TData = Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError = ErrorResponse>(
 symbolId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSymbolApiGamificationSymbolsSymbolIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSymbolApiGamificationSymbolsSymbolIdGetQueryOptions(symbolId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update topographic symbol.
 * @summary Update Symbol
 */
export type updateSymbolApiGamificationSymbolsSymbolIdPutResponse200 = {
  data: TopographicSymbolRead
  status: 200
}

export type updateSymbolApiGamificationSymbolsSymbolIdPutResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateSymbolApiGamificationSymbolsSymbolIdPutResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateSymbolApiGamificationSymbolsSymbolIdPutResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateSymbolApiGamificationSymbolsSymbolIdPutResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateSymbolApiGamificationSymbolsSymbolIdPutResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type updateSymbolApiGamificationSymbolsSymbolIdPutResponseSuccess = (updateSymbolApiGamificationSymbolsSymbolIdPutResponse200) & {
  headers: Headers;
};
export type updateSymbolApiGamificationSymbolsSymbolIdPutResponseError = (updateSymbolApiGamificationSymbolsSymbolIdPutResponse401 | updateSymbolApiGamificationSymbolsSymbolIdPutResponse403 | updateSymbolApiGamificationSymbolsSymbolIdPutResponse404 | updateSymbolApiGamificationSymbolsSymbolIdPutResponse422 | updateSymbolApiGamificationSymbolsSymbolIdPutResponse429) & {
  headers: Headers;
};

export type updateSymbolApiGamificationSymbolsSymbolIdPutResponse = (updateSymbolApiGamificationSymbolsSymbolIdPutResponseSuccess | updateSymbolApiGamificationSymbolsSymbolIdPutResponseError)

export const getUpdateSymbolApiGamificationSymbolsSymbolIdPutUrl = (symbolId: number,) => {


  

  return `/api/gamification/symbols/${symbolId}`
}

export const updateSymbolApiGamificationSymbolsSymbolIdPut = async (symbolId: number,
    topographicSymbolUpdate: TopographicSymbolUpdate, options?: RequestInit): Promise<updateSymbolApiGamificationSymbolsSymbolIdPutResponse> => {
  
  return customInstance<updateSymbolApiGamificationSymbolsSymbolIdPutResponse>(getUpdateSymbolApiGamificationSymbolsSymbolIdPutUrl(symbolId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      topographicSymbolUpdate,)
  }
);}




export const getUpdateSymbolApiGamificationSymbolsSymbolIdPutMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSymbolApiGamificationSymbolsSymbolIdPut>>, TError,{symbolId: number;data: TopographicSymbolUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSymbolApiGamificationSymbolsSymbolIdPut>>, TError,{symbolId: number;data: TopographicSymbolUpdate}, TContext> => {

const mutationKey = ['updateSymbolApiGamificationSymbolsSymbolIdPut'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSymbolApiGamificationSymbolsSymbolIdPut>>, {symbolId: number;data: TopographicSymbolUpdate}> = (props) => {
          const {symbolId,data} = props ?? {};

          return  updateSymbolApiGamificationSymbolsSymbolIdPut(symbolId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSymbolApiGamificationSymbolsSymbolIdPutMutationResult = NonNullable<Awaited<ReturnType<typeof updateSymbolApiGamificationSymbolsSymbolIdPut>>>
    export type UpdateSymbolApiGamificationSymbolsSymbolIdPutMutationBody = TopographicSymbolUpdate
    export type UpdateSymbolApiGamificationSymbolsSymbolIdPutMutationError = ErrorResponse

    /**
 * @summary Update Symbol
 */
export const useUpdateSymbolApiGamificationSymbolsSymbolIdPut = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSymbolApiGamificationSymbolsSymbolIdPut>>, TError,{symbolId: number;data: TopographicSymbolUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSymbolApiGamificationSymbolsSymbolIdPut>>,
        TError,
        {symbolId: number;data: TopographicSymbolUpdate},
        TContext
      > => {
      return useMutation(getUpdateSymbolApiGamificationSymbolsSymbolIdPutMutationOptions(options), queryClient);
    }
    /**
 * Delete a symbol and its associated attachments and storage files.
 * @summary Delete Symbol
 */
export type deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse422 = {
  data: ErrorResponse
  status: 422
}

export type deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponseSuccess = (deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponseError = (deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse401 | deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse403 | deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse404 | deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse422 | deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse429) & {
  headers: Headers;
};

export type deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse = (deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponseSuccess | deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponseError)

export const getDeleteSymbolApiGamificationSymbolsSymbolIdDeleteUrl = (symbolId: number,) => {


  

  return `/api/gamification/symbols/${symbolId}`
}

export const deleteSymbolApiGamificationSymbolsSymbolIdDelete = async (symbolId: number, options?: RequestInit): Promise<deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse> => {
  
  return customInstance<deleteSymbolApiGamificationSymbolsSymbolIdDeleteResponse>(getDeleteSymbolApiGamificationSymbolsSymbolIdDeleteUrl(symbolId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteSymbolApiGamificationSymbolsSymbolIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSymbolApiGamificationSymbolsSymbolIdDelete>>, TError,{symbolId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSymbolApiGamificationSymbolsSymbolIdDelete>>, TError,{symbolId: number}, TContext> => {

const mutationKey = ['deleteSymbolApiGamificationSymbolsSymbolIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSymbolApiGamificationSymbolsSymbolIdDelete>>, {symbolId: number}> = (props) => {
          const {symbolId} = props ?? {};

          return  deleteSymbolApiGamificationSymbolsSymbolIdDelete(symbolId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSymbolApiGamificationSymbolsSymbolIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSymbolApiGamificationSymbolsSymbolIdDelete>>>
    
    export type DeleteSymbolApiGamificationSymbolsSymbolIdDeleteMutationError = ErrorResponse

    /**
 * @summary Delete Symbol
 */
export const useDeleteSymbolApiGamificationSymbolsSymbolIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSymbolApiGamificationSymbolsSymbolIdDelete>>, TError,{symbolId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSymbolApiGamificationSymbolsSymbolIdDelete>>,
        TError,
        {symbolId: number},
        TContext
      > => {
      return useMutation(getDeleteSymbolApiGamificationSymbolsSymbolIdDeleteMutationOptions(options), queryClient);
    }
    