/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentEventType } from './assessmentEventType';

/**
 * Schema for reading assessment event information.
 */
export interface AssessmentEventRead {
  id: number;
  name: string;
  event_type: AssessmentEventType;
  group_id: number;
  subject_id: number;
  date: string;
  semester: number;
  academic_year: string;
  max_score: number;
  description: string | null;
  created_at: string;
  updated_at: string;
}
