/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Types of assessment events.
 */
export type AssessmentEventType = typeof AssessmentEventType[keyof typeof AssessmentEventType];


export const AssessmentEventType = {
  midterm_1: 'midterm_1',
  midterm_2: 'midterm_2',
  exam_1: 'exam_1',
  exam_2: 'exam_2',
  custom: 'custom',
} as const;
