/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentEventType } from './assessmentEventType';

/**
 * Schema for updating assessment event information.
 */
export interface AssessmentEventUpdate {
  name?: string | null;
  event_type?: AssessmentEventType | null;
  /** @nullable */
  date?: null;
  max_score?: number | null;
  description?: string | null;
}
