/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for updating assignment information.
 */
export interface AssignmentUpdate {
  title?: string | null;
  description?: string | null;
  instructions?: string | null;
  attachment_url?: string | null;
  due_date?: string | null;
  max_score?: number | null;
  is_published?: boolean | null;
  group_id?: number | null;
}
