/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupRead } from './groupRead';
import type { SubjectRead } from './subjectRead';
import type { TeacherRead } from './teacherRead';

/**
 * Schema for reading assignment information.
 */
export interface AssignmentRead {
  id: number;
  subject_id: number;
  teacher_id: number;
  group_id?: number | null;
  title: string;
  description?: string | null;
  instructions?: string | null;
  attachment_url?: string | null;
  due_date?: string | null;
  max_score: number;
  is_published: boolean;
  created_at: string;
  updated_at: string;
  subject?: SubjectRead | null;
  teacher?: TeacherRead | null;
  group?: GroupRead | null;
}
