/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for creating a new assignment.
 */
export interface AssignmentCreate {
  subject_id: number;
  teacher_id?: number | null;
  group_id?: number | null;
  title: string;
  description?: string | null;
  instructions?: string | null;
  attachment_url?: string | null;
  due_date?: string | null;
  max_score?: number;
  is_published?: boolean;
}
