/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttachmentEntity } from './attachmentEntity';
import type { AttachmentType } from './attachmentType';

/**
 * Schema for reading attachment information.
 */
export interface AttachmentRead {
  id: number;
  entity_type: AttachmentEntity;
  entity_id: number;
  original_filename: string;
  content_type: string;
  file_size: number;
  attachment_type: AttachmentType;
  title?: string | null;
  description?: string | null;
  url?: string | null;
  uploaded_by_id: number;
  created_at: string;
  updated_at: string;
  file_size_mb?: number | null;
}
