/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Entity types that can have attachments.
Allows flexible attachment to different models.
 */
export type AttachmentEntity = typeof AttachmentEntity[keyof typeof AttachmentEntity];


export const AttachmentEntity = {
  schedule: 'schedule',
  assignment: 'assignment',
  symbol: 'symbol',
} as const;
