/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttachmentRead } from './attachmentRead';

/**
 * Response after successful file upload.
 */
export interface AttachmentUploadResponse {
  attachment: AttachmentRead;
  message?: string;
}
