/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttachmentRead } from './attachmentRead';

/**
 * Response for listing attachments.
 */
export interface AttachmentListResponse {
  items: AttachmentRead[];
  total: number;
}
