/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for updating attachment metadata.
 */
export interface AttachmentUpdate {
  /** Display title */
  title?: string | null;
  /** Description */
  description?: string | null;
}
