/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceStatus } from './attendanceStatus';

/**
 * Schema for updating attendance information.
 */
export interface AttendanceUpdate {
  status?: AttendanceStatus | null;
  reason?: string | null;
}
