/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceRecord } from './attendanceRecord';

/**
 * Schema for bulk attendance marking (entire class at once).
 */
export interface AttendanceBulkCreate {
  schedule_id: number;
  date: string;
  records: AttendanceRecord[];
}
