/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceStatus } from './attendanceStatus';

/**
 * Single student attendance record for bulk operations.
 */
export interface AttendanceRecord {
  student_id: number;
  status: AttendanceStatus;
  reason?: string | null;
}
