/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceStatus } from './attendanceStatus';

/**
 * Schema for creating a single attendance record.
 */
export interface AttendanceCreate {
  student_id: number;
  schedule_id: number;
  date: string;
  status: AttendanceStatus;
  reason?: string | null;
}
