/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceSimpleRecordItem } from './attendanceSimpleRecordItem';

/**
 * Schema for simplified bulk attendance (without schedule selection).
 */
export interface AttendanceSimpleBulkCreate {
  group_id: number;
  date: string;
  records: AttendanceSimpleRecordItem[];
}
