/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttachmentEntity } from './attachmentEntity';

export interface BodyUploadAttachmentApiAttachmentsUploadPost {
  /** File to upload */
  file: Blob;
  /** Entity type (schedule, assignment) */
  entity_type: AttachmentEntity;
  /** Entity ID */
  entity_id: number;
  /** Optional display title */
  title?: string;
  /** Optional description */
  description?: string;
}
