/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for bulk grade input (for one student in an event).
 */
export interface BulkGradeInput {
  student_id: number;
  score?: number | null;
  comment?: string | null;
}
