/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { BulkGradeInput } from './bulkGradeInput';

/**
 * Schema for creating multiple grades at once for an event.
 */
export interface BulkGradesCreate {
  assessment_event_id: number;
  grades: BulkGradeInput[];
}
