/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { CanvasContentOutputMetadata } from './canvasContentOutputMetadata';
import type { CanvasImageObject } from './canvasImageObject';
import type { CanvasShapeObjectOutput } from './canvasShapeObjectOutput';
import type { CanvasSymbolObject } from './canvasSymbolObject';
import type { CanvasTextObject } from './canvasTextObject';

export interface CanvasContentOutput {
  version?: string;
  canvasWidth?: number;
  canvasHeight?: number;
  backgroundColor?: string;
  objects?: (CanvasTextObject | CanvasImageObject | CanvasShapeObjectOutput | CanvasSymbolObject)[];
  metadata?: CanvasContentOutputMetadata;
}
