/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { CanvasEngineType } from './canvasEngineType';

export interface CanvasRead {
  title: string;
  engine_type?: CanvasEngineType;
  id: number;
  creator_id: number;
  created_at: string;
  updated_at: string;
}
