/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

export type ChangePasswordApiAuthChangePasswordPostParams = {
old_password: string;
new_password: string;
};
