/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { SeverityLevel } from './severityLevel';
import type { ViolationType } from './violationType';

/**
 * Schema for creating a new disciplinary record.
 */
export interface DisciplinaryCreate {
  student_id: number;
  reported_by_id: number;
  violation_type: ViolationType;
  severity: SeverityLevel;
  date: string;
  description: string;
  action_taken?: string | null;
}
