/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { SeverityLevel } from './severityLevel';
import type { StudentRead } from './studentRead';
import type { TeacherRead } from './teacherRead';
import type { ViolationType } from './violationType';

/**
 * Schema for reading disciplinary record information.
 */
export interface DisciplinaryRead {
  id: number;
  student_id: number;
  reported_by_id: number;
  violation_type: ViolationType;
  severity: SeverityLevel;
  date: string;
  description: string;
  action_taken: string | null;
  report_number: string | null;
  is_resolved: boolean;
  resolved_date: string | null;
  resolution_notes: string | null;
  created_at: string;
  updated_at: string;
  student?: StudentRead | null;
  reported_by?: TeacherRead | null;
  /** Computed field for student's full name. */
  readonly student_name: string;
}
