/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorDetail } from './errorDetail';

/**
 * Additional error details (validation errors, context, etc.)
 */
export type ErrorBodyDetails = ErrorDetail[] | { [key: string]: unknown } | null;
