/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorBody } from './errorBody';

/**
 * Standard error response format.
All API errors follow this structure for consistent error handling.
 */
export interface ErrorResponse {
  error: ErrorBody;
}
