/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Single validation error detail.
 */
export interface ErrorDetail {
  /** Field name that caused the error */
  field: string;
  /** Error message for this field */
  message: string;
  /** Error type (e.g., 'value_error', 'type_error') */
  type: string;
  /** The invalid input value */
  input?: unknown | null;
}
