/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

export type GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams = {
group_id?: number;
date_from?: string;
date_to?: string;
};
