/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for creating a new grade.
 */
export interface GradeCreate {
  student_id: number;
  assessment_event_id: number;
  score?: number | null;
  comment?: string | null;
}
