/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for reading group information.
 */
export interface GroupRead {
  id: number;
  name: string;
  course: number;
  year: number;
  created_at: string;
}
