/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for updating group information.
 */
export interface GroupUpdate {
  name?: string | null;
  course?: number | null;
  year?: number | null;
}
