/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { SeverityLevel } from './severityLevel';
import type { ViolationType } from './violationType';

export type ListDisciplinaryRecordsApiDisciplinaryGetParams = {
student_id?: number;
group_id?: number;
violation_type?: ViolationType;
severity?: SeverityLevel;
is_resolved?: boolean;
date_from?: string;
date_to?: string;
skip?: number;
limit?: number;
};
