/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttachmentEntity } from './attachmentEntity';
import type { AttachmentType } from './attachmentType';

export type ListAttachmentsApiAttachmentsGetParams = {
entity_type?: AttachmentEntity;
attachment_type?: AttachmentType;
skip?: number;
limit?: number;
};
