/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceStatus } from './attendanceStatus';

export type ListAttendanceApiAttendanceGetParams = {
student_id?: number;
schedule_id?: number;
group_id?: number;
date_from?: string;
date_to?: string;
status_filter?: AttendanceStatus;
skip?: number;
limit?: number;
};
