/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { UserRole } from './userRole';

export type ListUsersApiUsersGetParams = {
skip?: number;
limit?: number;
role?: UserRole;
};
