/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

export type ListAssignmentsApiAssignmentsGetParams = {
subject_id?: number;
teacher_id?: number;
group_id?: number;
published_only?: boolean;
skip?: number;
limit?: number;
};
