/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { AssessmentEventType } from './assessmentEventType';

export type ListAssessmentEventsApiAssessmentEventsGetParams = {
group_id?: number | null;
subject_id?: number | null;
event_type?: AssessmentEventType | null;
academic_year?: string | null;
semester?: number | null;
skip?: number;
limit?: number;
};
