/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

export type ListSchedulesApiScheduleGetParams = {
group_id?: number;
teacher_id?: number;
subject_id?: number;
academic_year?: string;
semester?: number;
active_only?: boolean;
};
