/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { TopographicSymbolRead } from './topographicSymbolRead';

export interface MapBoardRead {
  name: string;
  canvas_id: number;
  id: number;
  symbols?: TopographicSymbolRead[];
}
