/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

export interface MapBoardUpdate {
  name?: string | null;
  canvas_id?: number | null;
  symbol_ids?: number[] | null;
}
