/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Single schedule item with specific date for monthly creation.
 */
export interface MonthScheduleItem {
  subject_id: number;
  teacher_id: number;
  specific_date: string;
  start_time: string;
  end_time: string;
  room: string;
}
