/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for updating schedule information.
 */
export interface ScheduleUpdate {
  group_id?: number | null;
  subject_id?: number | null;
  teacher_id?: number | null;
  specific_date?: string | null;
  start_time?: string | null;
  end_time?: string | null;
  room?: string | null;
  semester?: number | null;
  academic_year?: string | null;
  is_active?: boolean | null;
}
