/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for creating a new schedule entry.
 */
export interface ScheduleCreate {
  group_id: number;
  subject_id: number;
  teacher_id: number;
  specific_date: string;
  start_time: string;
  end_time: string;
  room: string;
  semester: number;
  academic_year: string;
}
