/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { GroupRead } from './groupRead';
import type { SubjectRead } from './subjectRead';
import type { TeacherRead } from './teacherRead';

/**
 * Schema for reading schedule information.
 */
export interface ScheduleRead {
  id: number;
  group_id: number;
  subject_id: number;
  teacher_id: number;
  specific_date: string;
  start_time: string;
  end_time: string;
  room: string;
  semester: number;
  academic_year: string;
  is_active: boolean;
  created_at: string;
  group?: GroupRead | null;
  subject?: SubjectRead | null;
  teacher?: TeacherRead | null;
}
