/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Severity levels for violations.
 */
export type SeverityLevel = typeof SeverityLevel[keyof typeof SeverityLevel];


export const SeverityLevel = {
  minor: 'minor',
  moderate: 'moderate',
  major: 'major',
  critical: 'critical',
} as const;
