/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { ShapeType } from './shapeType';

export interface ShapeField {
  shapeType: ShapeType;
  points?: number[] | null;
}
