/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Information about storage configuration.
 */
export interface StorageInfoResponse {
  /** Storage backend type: 'local' or 's3' */
  backend: string;
  /** Maximum allowed file size in MB */
  max_file_size_mb: number;
  /** List of allowed file extensions */
  allowed_extensions: string[];
}
