/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for updating student information.
 */
export interface StudentUpdate {
  group_id?: number | null;
  first_name?: string | null;
  last_name?: string | null;
  middle_name?: string | null;
  birth_date?: string | null;
  phone?: string | null;
  military_id?: string | null;
  rank?: string | null;
  notes?: string | null;
}
