/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for creating a new subject.
 */
export interface SubjectCreate {
  name: string;
  code: string;
  description?: string | null;
  credits?: number;
}
