/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for reading subject information.
 */
export interface SubjectRead {
  id: number;
  name: string;
  code: string;
  description: string | null;
  credits: number;
  created_at: string;
}
