/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for updating subject information.
 */
export interface SubjectUpdate {
  name?: string | null;
  code?: string | null;
  description?: string | null;
  credits?: number | null;
}
