/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Render type for topographic symbols.
 */
export type SymbolRenderType = typeof SymbolRenderType[keyof typeof SymbolRenderType];


export const SymbolRenderType = {
  file: 'file',
  editor: 'editor',
} as const;
