/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Schema for creating a new teacher.
 */
export interface TeacherCreate {
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  middle_name?: string | null;
  phone?: string | null;
  military_rank?: string | null;
  position?: string | null;
  department?: string | null;
  hire_date?: string | null;
  bio?: string | null;
}
