/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import type { SymbolRenderType } from './symbolRenderType';

export interface TopographicSymbolUpdate {
  name?: string | null;
  description?: string | null;
  render_type?: SymbolRenderType | null;
  canvas_id?: number | null;
}
