/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssessmentEventCreate,
  AssessmentEventRead,
  AssessmentEventUpdate,
  BulkGradeInput,
  ErrorResponse,
  ListAssessmentEventsApiAssessmentEventsGetParams
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new assessment event (teachers and admins only).
 * @summary Create Assessment Event
 */
export type createAssessmentEventApiAssessmentEventsPostResponse201 = {
  data: AssessmentEventRead
  status: 201
}

export type createAssessmentEventApiAssessmentEventsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createAssessmentEventApiAssessmentEventsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createAssessmentEventApiAssessmentEventsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createAssessmentEventApiAssessmentEventsPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createAssessmentEventApiAssessmentEventsPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type createAssessmentEventApiAssessmentEventsPostResponseSuccess = (createAssessmentEventApiAssessmentEventsPostResponse201) & {
  headers: Headers;
};
export type createAssessmentEventApiAssessmentEventsPostResponseError = (createAssessmentEventApiAssessmentEventsPostResponse401 | createAssessmentEventApiAssessmentEventsPostResponse403 | createAssessmentEventApiAssessmentEventsPostResponse404 | createAssessmentEventApiAssessmentEventsPostResponse422 | createAssessmentEventApiAssessmentEventsPostResponse429) & {
  headers: Headers;
};

export type createAssessmentEventApiAssessmentEventsPostResponse = (createAssessmentEventApiAssessmentEventsPostResponseSuccess | createAssessmentEventApiAssessmentEventsPostResponseError)

export const getCreateAssessmentEventApiAssessmentEventsPostUrl = () => {


  

  return `/api/assessment-events/`
}

export const createAssessmentEventApiAssessmentEventsPost = async (assessmentEventCreate: AssessmentEventCreate, options?: RequestInit): Promise<createAssessmentEventApiAssessmentEventsPostResponse> => {
  
  return customInstance<createAssessmentEventApiAssessmentEventsPostResponse>(getCreateAssessmentEventApiAssessmentEventsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assessmentEventCreate,)
  }
);}




export const getCreateAssessmentEventApiAssessmentEventsPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAssessmentEventApiAssessmentEventsPost>>, TError,{data: AssessmentEventCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createAssessmentEventApiAssessmentEventsPost>>, TError,{data: AssessmentEventCreate}, TContext> => {

const mutationKey = ['createAssessmentEventApiAssessmentEventsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAssessmentEventApiAssessmentEventsPost>>, {data: AssessmentEventCreate}> = (props) => {
          const {data} = props ?? {};

          return  createAssessmentEventApiAssessmentEventsPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAssessmentEventApiAssessmentEventsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createAssessmentEventApiAssessmentEventsPost>>>
    export type CreateAssessmentEventApiAssessmentEventsPostMutationBody = AssessmentEventCreate
    export type CreateAssessmentEventApiAssessmentEventsPostMutationError = ErrorResponse

    /**
 * @summary Create Assessment Event
 */
export const useCreateAssessmentEventApiAssessmentEventsPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAssessmentEventApiAssessmentEventsPost>>, TError,{data: AssessmentEventCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAssessmentEventApiAssessmentEventsPost>>,
        TError,
        {data: AssessmentEventCreate},
        TContext
      > => {
      return useMutation(getCreateAssessmentEventApiAssessmentEventsPostMutationOptions(options), queryClient);
    }
    /**
 * List assessment events with optional filters.
 * @summary List Assessment Events
 */
export type listAssessmentEventsApiAssessmentEventsGetResponse200 = {
  data: AssessmentEventRead[]
  status: 200
}

export type listAssessmentEventsApiAssessmentEventsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listAssessmentEventsApiAssessmentEventsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listAssessmentEventsApiAssessmentEventsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listAssessmentEventsApiAssessmentEventsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listAssessmentEventsApiAssessmentEventsGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listAssessmentEventsApiAssessmentEventsGetResponseSuccess = (listAssessmentEventsApiAssessmentEventsGetResponse200) & {
  headers: Headers;
};
export type listAssessmentEventsApiAssessmentEventsGetResponseError = (listAssessmentEventsApiAssessmentEventsGetResponse401 | listAssessmentEventsApiAssessmentEventsGetResponse403 | listAssessmentEventsApiAssessmentEventsGetResponse404 | listAssessmentEventsApiAssessmentEventsGetResponse422 | listAssessmentEventsApiAssessmentEventsGetResponse429) & {
  headers: Headers;
};

export type listAssessmentEventsApiAssessmentEventsGetResponse = (listAssessmentEventsApiAssessmentEventsGetResponseSuccess | listAssessmentEventsApiAssessmentEventsGetResponseError)

export const getListAssessmentEventsApiAssessmentEventsGetUrl = (params?: ListAssessmentEventsApiAssessmentEventsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/assessment-events/?${stringifiedParams}` : `/api/assessment-events/`
}

export const listAssessmentEventsApiAssessmentEventsGet = async (params?: ListAssessmentEventsApiAssessmentEventsGetParams, options?: RequestInit): Promise<listAssessmentEventsApiAssessmentEventsGetResponse> => {
  
  return customInstance<listAssessmentEventsApiAssessmentEventsGetResponse>(getListAssessmentEventsApiAssessmentEventsGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListAssessmentEventsApiAssessmentEventsGetQueryKey = (params?: ListAssessmentEventsApiAssessmentEventsGetParams,) => {
    return [
    `/api/assessment-events/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListAssessmentEventsApiAssessmentEventsGetQueryOptions = <TData = Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError = ErrorResponse>(params?: ListAssessmentEventsApiAssessmentEventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAssessmentEventsApiAssessmentEventsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>> = ({ signal }) => listAssessmentEventsApiAssessmentEventsGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAssessmentEventsApiAssessmentEventsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>>
export type ListAssessmentEventsApiAssessmentEventsGetQueryError = ErrorResponse


export function useListAssessmentEventsApiAssessmentEventsGet<TData = Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError = ErrorResponse>(
 params: undefined |  ListAssessmentEventsApiAssessmentEventsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>,
          TError,
          Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAssessmentEventsApiAssessmentEventsGet<TData = Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError = ErrorResponse>(
 params?: ListAssessmentEventsApiAssessmentEventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>,
          TError,
          Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAssessmentEventsApiAssessmentEventsGet<TData = Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError = ErrorResponse>(
 params?: ListAssessmentEventsApiAssessmentEventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Assessment Events
 */

export function useListAssessmentEventsApiAssessmentEventsGet<TData = Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError = ErrorResponse>(
 params?: ListAssessmentEventsApiAssessmentEventsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssessmentEventsApiAssessmentEventsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAssessmentEventsApiAssessmentEventsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get assessment event by ID.
 * @summary Get Assessment Event
 */
export type getAssessmentEventApiAssessmentEventsEventIdGetResponse200 = {
  data: AssessmentEventRead
  status: 200
}

export type getAssessmentEventApiAssessmentEventsEventIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAssessmentEventApiAssessmentEventsEventIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getAssessmentEventApiAssessmentEventsEventIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAssessmentEventApiAssessmentEventsEventIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getAssessmentEventApiAssessmentEventsEventIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getAssessmentEventApiAssessmentEventsEventIdGetResponseSuccess = (getAssessmentEventApiAssessmentEventsEventIdGetResponse200) & {
  headers: Headers;
};
export type getAssessmentEventApiAssessmentEventsEventIdGetResponseError = (getAssessmentEventApiAssessmentEventsEventIdGetResponse401 | getAssessmentEventApiAssessmentEventsEventIdGetResponse403 | getAssessmentEventApiAssessmentEventsEventIdGetResponse404 | getAssessmentEventApiAssessmentEventsEventIdGetResponse422 | getAssessmentEventApiAssessmentEventsEventIdGetResponse429) & {
  headers: Headers;
};

export type getAssessmentEventApiAssessmentEventsEventIdGetResponse = (getAssessmentEventApiAssessmentEventsEventIdGetResponseSuccess | getAssessmentEventApiAssessmentEventsEventIdGetResponseError)

export const getGetAssessmentEventApiAssessmentEventsEventIdGetUrl = (eventId: number,) => {


  

  return `/api/assessment-events/${eventId}`
}

export const getAssessmentEventApiAssessmentEventsEventIdGet = async (eventId: number, options?: RequestInit): Promise<getAssessmentEventApiAssessmentEventsEventIdGetResponse> => {
  
  return customInstance<getAssessmentEventApiAssessmentEventsEventIdGetResponse>(getGetAssessmentEventApiAssessmentEventsEventIdGetUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAssessmentEventApiAssessmentEventsEventIdGetQueryKey = (eventId: number,) => {
    return [
    `/api/assessment-events/${eventId}`
    ] as const;
    }

    
export const getGetAssessmentEventApiAssessmentEventsEventIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError = ErrorResponse>(eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssessmentEventApiAssessmentEventsEventIdGetQueryKey(eventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>> = ({ signal }) => getAssessmentEventApiAssessmentEventsEventIdGet(eventId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAssessmentEventApiAssessmentEventsEventIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>>
export type GetAssessmentEventApiAssessmentEventsEventIdGetQueryError = ErrorResponse


export function useGetAssessmentEventApiAssessmentEventsEventIdGet<TData = Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError = ErrorResponse>(
 eventId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>,
          TError,
          Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssessmentEventApiAssessmentEventsEventIdGet<TData = Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError = ErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>,
          TError,
          Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssessmentEventApiAssessmentEventsEventIdGet<TData = Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError = ErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Assessment Event
 */

export function useGetAssessmentEventApiAssessmentEventsEventIdGet<TData = Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError = ErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssessmentEventApiAssessmentEventsEventIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAssessmentEventApiAssessmentEventsEventIdGetQueryOptions(eventId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update assessment event (teachers and admins only).
 * @summary Update Assessment Event
 */
export type updateAssessmentEventApiAssessmentEventsEventIdPatchResponse200 = {
  data: AssessmentEventRead
  status: 200
}

export type updateAssessmentEventApiAssessmentEventsEventIdPatchResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateAssessmentEventApiAssessmentEventsEventIdPatchResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateAssessmentEventApiAssessmentEventsEventIdPatchResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateAssessmentEventApiAssessmentEventsEventIdPatchResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateAssessmentEventApiAssessmentEventsEventIdPatchResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type updateAssessmentEventApiAssessmentEventsEventIdPatchResponseSuccess = (updateAssessmentEventApiAssessmentEventsEventIdPatchResponse200) & {
  headers: Headers;
};
export type updateAssessmentEventApiAssessmentEventsEventIdPatchResponseError = (updateAssessmentEventApiAssessmentEventsEventIdPatchResponse401 | updateAssessmentEventApiAssessmentEventsEventIdPatchResponse403 | updateAssessmentEventApiAssessmentEventsEventIdPatchResponse404 | updateAssessmentEventApiAssessmentEventsEventIdPatchResponse422 | updateAssessmentEventApiAssessmentEventsEventIdPatchResponse429) & {
  headers: Headers;
};

export type updateAssessmentEventApiAssessmentEventsEventIdPatchResponse = (updateAssessmentEventApiAssessmentEventsEventIdPatchResponseSuccess | updateAssessmentEventApiAssessmentEventsEventIdPatchResponseError)

export const getUpdateAssessmentEventApiAssessmentEventsEventIdPatchUrl = (eventId: number,) => {


  

  return `/api/assessment-events/${eventId}`
}

export const updateAssessmentEventApiAssessmentEventsEventIdPatch = async (eventId: number,
    assessmentEventUpdate: AssessmentEventUpdate, options?: RequestInit): Promise<updateAssessmentEventApiAssessmentEventsEventIdPatchResponse> => {
  
  return customInstance<updateAssessmentEventApiAssessmentEventsEventIdPatchResponse>(getUpdateAssessmentEventApiAssessmentEventsEventIdPatchUrl(eventId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assessmentEventUpdate,)
  }
);}




export const getUpdateAssessmentEventApiAssessmentEventsEventIdPatchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAssessmentEventApiAssessmentEventsEventIdPatch>>, TError,{eventId: number;data: AssessmentEventUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAssessmentEventApiAssessmentEventsEventIdPatch>>, TError,{eventId: number;data: AssessmentEventUpdate}, TContext> => {

const mutationKey = ['updateAssessmentEventApiAssessmentEventsEventIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAssessmentEventApiAssessmentEventsEventIdPatch>>, {eventId: number;data: AssessmentEventUpdate}> = (props) => {
          const {eventId,data} = props ?? {};

          return  updateAssessmentEventApiAssessmentEventsEventIdPatch(eventId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAssessmentEventApiAssessmentEventsEventIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateAssessmentEventApiAssessmentEventsEventIdPatch>>>
    export type UpdateAssessmentEventApiAssessmentEventsEventIdPatchMutationBody = AssessmentEventUpdate
    export type UpdateAssessmentEventApiAssessmentEventsEventIdPatchMutationError = ErrorResponse

    /**
 * @summary Update Assessment Event
 */
export const useUpdateAssessmentEventApiAssessmentEventsEventIdPatch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAssessmentEventApiAssessmentEventsEventIdPatch>>, TError,{eventId: number;data: AssessmentEventUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAssessmentEventApiAssessmentEventsEventIdPatch>>,
        TError,
        {eventId: number;data: AssessmentEventUpdate},
        TContext
      > => {
      return useMutation(getUpdateAssessmentEventApiAssessmentEventsEventIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete assessment event (teachers and admins only).
This will also delete all associated grades.
 * @summary Delete Assessment Event
 */
export type deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse422 = {
  data: ErrorResponse
  status: 422
}

export type deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponseSuccess = (deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponseError = (deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse401 | deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse403 | deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse404 | deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse422 | deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse429) & {
  headers: Headers;
};

export type deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse = (deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponseSuccess | deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponseError)

export const getDeleteAssessmentEventApiAssessmentEventsEventIdDeleteUrl = (eventId: number,) => {


  

  return `/api/assessment-events/${eventId}`
}

export const deleteAssessmentEventApiAssessmentEventsEventIdDelete = async (eventId: number, options?: RequestInit): Promise<deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse> => {
  
  return customInstance<deleteAssessmentEventApiAssessmentEventsEventIdDeleteResponse>(getDeleteAssessmentEventApiAssessmentEventsEventIdDeleteUrl(eventId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteAssessmentEventApiAssessmentEventsEventIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssessmentEventApiAssessmentEventsEventIdDelete>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAssessmentEventApiAssessmentEventsEventIdDelete>>, TError,{eventId: number}, TContext> => {

const mutationKey = ['deleteAssessmentEventApiAssessmentEventsEventIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAssessmentEventApiAssessmentEventsEventIdDelete>>, {eventId: number}> = (props) => {
          const {eventId} = props ?? {};

          return  deleteAssessmentEventApiAssessmentEventsEventIdDelete(eventId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAssessmentEventApiAssessmentEventsEventIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAssessmentEventApiAssessmentEventsEventIdDelete>>>
    
    export type DeleteAssessmentEventApiAssessmentEventsEventIdDeleteMutationError = ErrorResponse

    /**
 * @summary Delete Assessment Event
 */
export const useDeleteAssessmentEventApiAssessmentEventsEventIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssessmentEventApiAssessmentEventsEventIdDelete>>, TError,{eventId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAssessmentEventApiAssessmentEventsEventIdDelete>>,
        TError,
        {eventId: number},
        TContext
      > => {
      return useMutation(getDeleteAssessmentEventApiAssessmentEventsEventIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Get all grades for an assessment event with student info.
 * @summary Get Event Grades
 */
export type getEventGradesApiAssessmentEventsEventIdGradesGetResponse200 = {
  data: unknown
  status: 200
}

export type getEventGradesApiAssessmentEventsEventIdGradesGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getEventGradesApiAssessmentEventsEventIdGradesGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getEventGradesApiAssessmentEventsEventIdGradesGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getEventGradesApiAssessmentEventsEventIdGradesGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getEventGradesApiAssessmentEventsEventIdGradesGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getEventGradesApiAssessmentEventsEventIdGradesGetResponseSuccess = (getEventGradesApiAssessmentEventsEventIdGradesGetResponse200) & {
  headers: Headers;
};
export type getEventGradesApiAssessmentEventsEventIdGradesGetResponseError = (getEventGradesApiAssessmentEventsEventIdGradesGetResponse401 | getEventGradesApiAssessmentEventsEventIdGradesGetResponse403 | getEventGradesApiAssessmentEventsEventIdGradesGetResponse404 | getEventGradesApiAssessmentEventsEventIdGradesGetResponse422 | getEventGradesApiAssessmentEventsEventIdGradesGetResponse429) & {
  headers: Headers;
};

export type getEventGradesApiAssessmentEventsEventIdGradesGetResponse = (getEventGradesApiAssessmentEventsEventIdGradesGetResponseSuccess | getEventGradesApiAssessmentEventsEventIdGradesGetResponseError)

export const getGetEventGradesApiAssessmentEventsEventIdGradesGetUrl = (eventId: number,) => {


  

  return `/api/assessment-events/${eventId}/grades`
}

export const getEventGradesApiAssessmentEventsEventIdGradesGet = async (eventId: number, options?: RequestInit): Promise<getEventGradesApiAssessmentEventsEventIdGradesGetResponse> => {
  
  return customInstance<getEventGradesApiAssessmentEventsEventIdGradesGetResponse>(getGetEventGradesApiAssessmentEventsEventIdGradesGetUrl(eventId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetEventGradesApiAssessmentEventsEventIdGradesGetQueryKey = (eventId: number,) => {
    return [
    `/api/assessment-events/${eventId}/grades`
    ] as const;
    }

    
export const getGetEventGradesApiAssessmentEventsEventIdGradesGetQueryOptions = <TData = Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError = ErrorResponse>(eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEventGradesApiAssessmentEventsEventIdGradesGetQueryKey(eventId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>> = ({ signal }) => getEventGradesApiAssessmentEventsEventIdGradesGet(eventId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(eventId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEventGradesApiAssessmentEventsEventIdGradesGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>>
export type GetEventGradesApiAssessmentEventsEventIdGradesGetQueryError = ErrorResponse


export function useGetEventGradesApiAssessmentEventsEventIdGradesGet<TData = Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError = ErrorResponse>(
 eventId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>,
          TError,
          Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventGradesApiAssessmentEventsEventIdGradesGet<TData = Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError = ErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>,
          TError,
          Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEventGradesApiAssessmentEventsEventIdGradesGet<TData = Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError = ErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Event Grades
 */

export function useGetEventGradesApiAssessmentEventsEventIdGradesGet<TData = Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError = ErrorResponse>(
 eventId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEventGradesApiAssessmentEventsEventIdGradesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEventGradesApiAssessmentEventsEventIdGradesGetQueryOptions(eventId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create or update grades for multiple students in an event (bulk operation).
 * @summary Bulk Update Grades
 */
export type bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse200 = {
  data: unknown
  status: 200
}

export type bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponseSuccess = (bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse200) & {
  headers: Headers;
};
export type bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponseError = (bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse401 | bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse403 | bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse404 | bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse422 | bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse429) & {
  headers: Headers;
};

export type bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse = (bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponseSuccess | bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponseError)

export const getBulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostUrl = (eventId: number,) => {


  

  return `/api/assessment-events/${eventId}/grades/bulk`
}

export const bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost = async (eventId: number,
    bulkGradeInput: BulkGradeInput[], options?: RequestInit): Promise<bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse> => {
  
  return customInstance<bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostResponse>(getBulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostUrl(eventId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkGradeInput,)
  }
);}




export const getBulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost>>, TError,{eventId: number;data: BulkGradeInput[]}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost>>, TError,{eventId: number;data: BulkGradeInput[]}, TContext> => {

const mutationKey = ['bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost>>, {eventId: number;data: BulkGradeInput[]}> = (props) => {
          const {eventId,data} = props ?? {};

          return  bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost(eventId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type BulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostMutationResult = NonNullable<Awaited<ReturnType<typeof bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost>>>
    export type BulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostMutationBody = BulkGradeInput[]
    export type BulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostMutationError = ErrorResponse

    /**
 * @summary Bulk Update Grades
 */
export const useBulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost>>, TError,{eventId: number;data: BulkGradeInput[]}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof bulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPost>>,
        TError,
        {eventId: number;data: BulkGradeInput[]},
        TContext
      > => {
      return useMutation(getBulkUpdateGradesApiAssessmentEventsEventIdGradesBulkPostMutationOptions(options), queryClient);
    }
    