/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * 
## Электронный журнал для Военной кафедры КазУТБ

### Возможности API:
- 🔐 **Аутентификация** - JWT токены, регистрация, авторизация
- 👥 **Управление пользователями** - курсанты, преподаватели, администраторы
- 📚 **Учебный процесс** - расписание, посещаемость, оценки
- 📎 **Файлы** - загрузка материалов к занятиям
- 📊 **Аналитика** - статистика успеваемости

### Аутентификация:
Все защищённые эндпоинты требуют JWT токен в заголовке:
```
Authorization: Bearer <token>
```

### Формат ошибок:
Все ошибки возвращаются в стандартном формате:
```json
{
    "error": {
        "code": "ERROR_CODE",
        "message": "Описание ошибки",
        "details": [...]
    }
}
```
    
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  ListStudentsApiStudentsGetParams,
  StudentCreate,
  StudentRead,
  StudentUpdate
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new student with user account (teachers and admins only).
 * @summary Create Student
 */
export type createStudentApiStudentsPostResponse201 = {
  data: StudentRead
  status: 201
}

export type createStudentApiStudentsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createStudentApiStudentsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createStudentApiStudentsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createStudentApiStudentsPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createStudentApiStudentsPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type createStudentApiStudentsPostResponseSuccess = (createStudentApiStudentsPostResponse201) & {
  headers: Headers;
};
export type createStudentApiStudentsPostResponseError = (createStudentApiStudentsPostResponse401 | createStudentApiStudentsPostResponse403 | createStudentApiStudentsPostResponse404 | createStudentApiStudentsPostResponse422 | createStudentApiStudentsPostResponse429) & {
  headers: Headers;
};

export type createStudentApiStudentsPostResponse = (createStudentApiStudentsPostResponseSuccess | createStudentApiStudentsPostResponseError)

export const getCreateStudentApiStudentsPostUrl = () => {


  

  return `/api/students/`
}

export const createStudentApiStudentsPost = async (studentCreate: StudentCreate, options?: RequestInit): Promise<createStudentApiStudentsPostResponse> => {
  
  return customInstance<createStudentApiStudentsPostResponse>(getCreateStudentApiStudentsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      studentCreate,)
  }
);}




export const getCreateStudentApiStudentsPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStudentApiStudentsPost>>, TError,{data: StudentCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createStudentApiStudentsPost>>, TError,{data: StudentCreate}, TContext> => {

const mutationKey = ['createStudentApiStudentsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createStudentApiStudentsPost>>, {data: StudentCreate}> = (props) => {
          const {data} = props ?? {};

          return  createStudentApiStudentsPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateStudentApiStudentsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createStudentApiStudentsPost>>>
    export type CreateStudentApiStudentsPostMutationBody = StudentCreate
    export type CreateStudentApiStudentsPostMutationError = ErrorResponse

    /**
 * @summary Create Student
 */
export const useCreateStudentApiStudentsPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createStudentApiStudentsPost>>, TError,{data: StudentCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createStudentApiStudentsPost>>,
        TError,
        {data: StudentCreate},
        TContext
      > => {
      return useMutation(getCreateStudentApiStudentsPostMutationOptions(options), queryClient);
    }
    /**
 * List all students.
 * @summary List Students
 */
export type listStudentsApiStudentsGetResponse200 = {
  data: StudentRead[]
  status: 200
}

export type listStudentsApiStudentsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listStudentsApiStudentsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listStudentsApiStudentsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listStudentsApiStudentsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listStudentsApiStudentsGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listStudentsApiStudentsGetResponseSuccess = (listStudentsApiStudentsGetResponse200) & {
  headers: Headers;
};
export type listStudentsApiStudentsGetResponseError = (listStudentsApiStudentsGetResponse401 | listStudentsApiStudentsGetResponse403 | listStudentsApiStudentsGetResponse404 | listStudentsApiStudentsGetResponse422 | listStudentsApiStudentsGetResponse429) & {
  headers: Headers;
};

export type listStudentsApiStudentsGetResponse = (listStudentsApiStudentsGetResponseSuccess | listStudentsApiStudentsGetResponseError)

export const getListStudentsApiStudentsGetUrl = (params?: ListStudentsApiStudentsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/students/?${stringifiedParams}` : `/api/students/`
}

export const listStudentsApiStudentsGet = async (params?: ListStudentsApiStudentsGetParams, options?: RequestInit): Promise<listStudentsApiStudentsGetResponse> => {
  
  return customInstance<listStudentsApiStudentsGetResponse>(getListStudentsApiStudentsGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListStudentsApiStudentsGetQueryKey = (params?: ListStudentsApiStudentsGetParams,) => {
    return [
    `/api/students/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListStudentsApiStudentsGetQueryOptions = <TData = Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError = ErrorResponse>(params?: ListStudentsApiStudentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStudentsApiStudentsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStudentsApiStudentsGet>>> = ({ signal }) => listStudentsApiStudentsGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStudentsApiStudentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listStudentsApiStudentsGet>>>
export type ListStudentsApiStudentsGetQueryError = ErrorResponse


export function useListStudentsApiStudentsGet<TData = Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError = ErrorResponse>(
 params: undefined |  ListStudentsApiStudentsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStudentsApiStudentsGet>>,
          TError,
          Awaited<ReturnType<typeof listStudentsApiStudentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStudentsApiStudentsGet<TData = Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError = ErrorResponse>(
 params?: ListStudentsApiStudentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStudentsApiStudentsGet>>,
          TError,
          Awaited<ReturnType<typeof listStudentsApiStudentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStudentsApiStudentsGet<TData = Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError = ErrorResponse>(
 params?: ListStudentsApiStudentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Students
 */

export function useListStudentsApiStudentsGet<TData = Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError = ErrorResponse>(
 params?: ListStudentsApiStudentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStudentsApiStudentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStudentsApiStudentsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get student by ID.
 * @summary Get Student
 */
export type getStudentApiStudentsStudentIdGetResponse200 = {
  data: StudentRead
  status: 200
}

export type getStudentApiStudentsStudentIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getStudentApiStudentsStudentIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getStudentApiStudentsStudentIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getStudentApiStudentsStudentIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getStudentApiStudentsStudentIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getStudentApiStudentsStudentIdGetResponseSuccess = (getStudentApiStudentsStudentIdGetResponse200) & {
  headers: Headers;
};
export type getStudentApiStudentsStudentIdGetResponseError = (getStudentApiStudentsStudentIdGetResponse401 | getStudentApiStudentsStudentIdGetResponse403 | getStudentApiStudentsStudentIdGetResponse404 | getStudentApiStudentsStudentIdGetResponse422 | getStudentApiStudentsStudentIdGetResponse429) & {
  headers: Headers;
};

export type getStudentApiStudentsStudentIdGetResponse = (getStudentApiStudentsStudentIdGetResponseSuccess | getStudentApiStudentsStudentIdGetResponseError)

export const getGetStudentApiStudentsStudentIdGetUrl = (studentId: number,) => {


  

  return `/api/students/${studentId}`
}

export const getStudentApiStudentsStudentIdGet = async (studentId: number, options?: RequestInit): Promise<getStudentApiStudentsStudentIdGetResponse> => {
  
  return customInstance<getStudentApiStudentsStudentIdGetResponse>(getGetStudentApiStudentsStudentIdGetUrl(studentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStudentApiStudentsStudentIdGetQueryKey = (studentId: number,) => {
    return [
    `/api/students/${studentId}`
    ] as const;
    }

    
export const getGetStudentApiStudentsStudentIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError = ErrorResponse>(studentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentApiStudentsStudentIdGetQueryKey(studentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>> = ({ signal }) => getStudentApiStudentsStudentIdGet(studentId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(studentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentApiStudentsStudentIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>>
export type GetStudentApiStudentsStudentIdGetQueryError = ErrorResponse


export function useGetStudentApiStudentsStudentIdGet<TData = Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError = ErrorResponse>(
 studentId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentApiStudentsStudentIdGet<TData = Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError = ErrorResponse>(
 studentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentApiStudentsStudentIdGet<TData = Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError = ErrorResponse>(
 studentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Student
 */

export function useGetStudentApiStudentsStudentIdGet<TData = Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError = ErrorResponse>(
 studentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentApiStudentsStudentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentApiStudentsStudentIdGetQueryOptions(studentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update student information (teachers and admins only).
 * @summary Update Student
 */
export type updateStudentApiStudentsStudentIdPatchResponse200 = {
  data: StudentRead
  status: 200
}

export type updateStudentApiStudentsStudentIdPatchResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateStudentApiStudentsStudentIdPatchResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateStudentApiStudentsStudentIdPatchResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateStudentApiStudentsStudentIdPatchResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateStudentApiStudentsStudentIdPatchResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type updateStudentApiStudentsStudentIdPatchResponseSuccess = (updateStudentApiStudentsStudentIdPatchResponse200) & {
  headers: Headers;
};
export type updateStudentApiStudentsStudentIdPatchResponseError = (updateStudentApiStudentsStudentIdPatchResponse401 | updateStudentApiStudentsStudentIdPatchResponse403 | updateStudentApiStudentsStudentIdPatchResponse404 | updateStudentApiStudentsStudentIdPatchResponse422 | updateStudentApiStudentsStudentIdPatchResponse429) & {
  headers: Headers;
};

export type updateStudentApiStudentsStudentIdPatchResponse = (updateStudentApiStudentsStudentIdPatchResponseSuccess | updateStudentApiStudentsStudentIdPatchResponseError)

export const getUpdateStudentApiStudentsStudentIdPatchUrl = (studentId: number,) => {


  

  return `/api/students/${studentId}`
}

export const updateStudentApiStudentsStudentIdPatch = async (studentId: number,
    studentUpdate: StudentUpdate, options?: RequestInit): Promise<updateStudentApiStudentsStudentIdPatchResponse> => {
  
  return customInstance<updateStudentApiStudentsStudentIdPatchResponse>(getUpdateStudentApiStudentsStudentIdPatchUrl(studentId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      studentUpdate,)
  }
);}




export const getUpdateStudentApiStudentsStudentIdPatchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStudentApiStudentsStudentIdPatch>>, TError,{studentId: number;data: StudentUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateStudentApiStudentsStudentIdPatch>>, TError,{studentId: number;data: StudentUpdate}, TContext> => {

const mutationKey = ['updateStudentApiStudentsStudentIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateStudentApiStudentsStudentIdPatch>>, {studentId: number;data: StudentUpdate}> = (props) => {
          const {studentId,data} = props ?? {};

          return  updateStudentApiStudentsStudentIdPatch(studentId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateStudentApiStudentsStudentIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateStudentApiStudentsStudentIdPatch>>>
    export type UpdateStudentApiStudentsStudentIdPatchMutationBody = StudentUpdate
    export type UpdateStudentApiStudentsStudentIdPatchMutationError = ErrorResponse

    /**
 * @summary Update Student
 */
export const useUpdateStudentApiStudentsStudentIdPatch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateStudentApiStudentsStudentIdPatch>>, TError,{studentId: number;data: StudentUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateStudentApiStudentsStudentIdPatch>>,
        TError,
        {studentId: number;data: StudentUpdate},
        TContext
      > => {
      return useMutation(getUpdateStudentApiStudentsStudentIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete a student (teachers and admins only).
 * @summary Delete Student
 */
export type deleteStudentApiStudentsStudentIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteStudentApiStudentsStudentIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteStudentApiStudentsStudentIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteStudentApiStudentsStudentIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteStudentApiStudentsStudentIdDeleteResponse422 = {
  data: ErrorResponse
  status: 422
}

export type deleteStudentApiStudentsStudentIdDeleteResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type deleteStudentApiStudentsStudentIdDeleteResponseSuccess = (deleteStudentApiStudentsStudentIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteStudentApiStudentsStudentIdDeleteResponseError = (deleteStudentApiStudentsStudentIdDeleteResponse401 | deleteStudentApiStudentsStudentIdDeleteResponse403 | deleteStudentApiStudentsStudentIdDeleteResponse404 | deleteStudentApiStudentsStudentIdDeleteResponse422 | deleteStudentApiStudentsStudentIdDeleteResponse429) & {
  headers: Headers;
};

export type deleteStudentApiStudentsStudentIdDeleteResponse = (deleteStudentApiStudentsStudentIdDeleteResponseSuccess | deleteStudentApiStudentsStudentIdDeleteResponseError)

export const getDeleteStudentApiStudentsStudentIdDeleteUrl = (studentId: number,) => {


  

  return `/api/students/${studentId}`
}

export const deleteStudentApiStudentsStudentIdDelete = async (studentId: number, options?: RequestInit): Promise<deleteStudentApiStudentsStudentIdDeleteResponse> => {
  
  return customInstance<deleteStudentApiStudentsStudentIdDeleteResponse>(getDeleteStudentApiStudentsStudentIdDeleteUrl(studentId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteStudentApiStudentsStudentIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStudentApiStudentsStudentIdDelete>>, TError,{studentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStudentApiStudentsStudentIdDelete>>, TError,{studentId: number}, TContext> => {

const mutationKey = ['deleteStudentApiStudentsStudentIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStudentApiStudentsStudentIdDelete>>, {studentId: number}> = (props) => {
          const {studentId} = props ?? {};

          return  deleteStudentApiStudentsStudentIdDelete(studentId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteStudentApiStudentsStudentIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStudentApiStudentsStudentIdDelete>>>
    
    export type DeleteStudentApiStudentsStudentIdDeleteMutationError = ErrorResponse

    /**
 * @summary Delete Student
 */
export const useDeleteStudentApiStudentsStudentIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStudentApiStudentsStudentIdDelete>>, TError,{studentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteStudentApiStudentsStudentIdDelete>>,
        TError,
        {studentId: number},
        TContext
      > => {
      return useMutation(getDeleteStudentApiStudentsStudentIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Get current user's student profile.
 * @summary Get My Student Profile
 */
export type getMyStudentProfileApiStudentsMeProfileGetResponse200 = {
  data: StudentRead
  status: 200
}

export type getMyStudentProfileApiStudentsMeProfileGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getMyStudentProfileApiStudentsMeProfileGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getMyStudentProfileApiStudentsMeProfileGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getMyStudentProfileApiStudentsMeProfileGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getMyStudentProfileApiStudentsMeProfileGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getMyStudentProfileApiStudentsMeProfileGetResponseSuccess = (getMyStudentProfileApiStudentsMeProfileGetResponse200) & {
  headers: Headers;
};
export type getMyStudentProfileApiStudentsMeProfileGetResponseError = (getMyStudentProfileApiStudentsMeProfileGetResponse401 | getMyStudentProfileApiStudentsMeProfileGetResponse403 | getMyStudentProfileApiStudentsMeProfileGetResponse404 | getMyStudentProfileApiStudentsMeProfileGetResponse422 | getMyStudentProfileApiStudentsMeProfileGetResponse429) & {
  headers: Headers;
};

export type getMyStudentProfileApiStudentsMeProfileGetResponse = (getMyStudentProfileApiStudentsMeProfileGetResponseSuccess | getMyStudentProfileApiStudentsMeProfileGetResponseError)

export const getGetMyStudentProfileApiStudentsMeProfileGetUrl = () => {


  

  return `/api/students/me/profile`
}

export const getMyStudentProfileApiStudentsMeProfileGet = async ( options?: RequestInit): Promise<getMyStudentProfileApiStudentsMeProfileGetResponse> => {
  
  return customInstance<getMyStudentProfileApiStudentsMeProfileGetResponse>(getGetMyStudentProfileApiStudentsMeProfileGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyStudentProfileApiStudentsMeProfileGetQueryKey = () => {
    return [
    `/api/students/me/profile`
    ] as const;
    }

    
export const getGetMyStudentProfileApiStudentsMeProfileGetQueryOptions = <TData = Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyStudentProfileApiStudentsMeProfileGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>> = ({ signal }) => getMyStudentProfileApiStudentsMeProfileGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyStudentProfileApiStudentsMeProfileGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>>
export type GetMyStudentProfileApiStudentsMeProfileGetQueryError = ErrorResponse


export function useGetMyStudentProfileApiStudentsMeProfileGet<TData = Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>,
          TError,
          Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyStudentProfileApiStudentsMeProfileGet<TData = Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>,
          TError,
          Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyStudentProfileApiStudentsMeProfileGet<TData = Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Student Profile
 */

export function useGetMyStudentProfileApiStudentsMeProfileGet<TData = Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyStudentProfileApiStudentsMeProfileGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyStudentProfileApiStudentsMeProfileGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




