/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * 
## Электронный журнал для Военной кафедры КазУТБ

### Возможности API:
- 🔐 **Аутентификация** - JWT токены, регистрация, авторизация
- 👥 **Управление пользователями** - курсанты, преподаватели, администраторы
- 📚 **Учебный процесс** - расписание, посещаемость, оценки
- 📎 **Файлы** - загрузка материалов к занятиям
- 📊 **Аналитика** - статистика успеваемости

### Аутентификация:
Все защищённые эндпоинты требуют JWT токен в заголовке:
```
Authorization: Bearer <token>
```

### Формат ошибок:
Все ошибки возвращаются в стандартном формате:
```json
{
    "error": {
        "code": "ERROR_CODE",
        "message": "Описание ошибки",
        "details": [...]
    }
}
```
    
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  ListSubjectsApiSubjectsGetParams,
  SubjectCreate,
  SubjectRead,
  SubjectUpdate
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new subject (teachers and admins only).
 * @summary Create Subject
 */
export type createSubjectApiSubjectsPostResponse201 = {
  data: SubjectRead
  status: 201
}

export type createSubjectApiSubjectsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createSubjectApiSubjectsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createSubjectApiSubjectsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createSubjectApiSubjectsPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createSubjectApiSubjectsPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type createSubjectApiSubjectsPostResponseSuccess = (createSubjectApiSubjectsPostResponse201) & {
  headers: Headers;
};
export type createSubjectApiSubjectsPostResponseError = (createSubjectApiSubjectsPostResponse401 | createSubjectApiSubjectsPostResponse403 | createSubjectApiSubjectsPostResponse404 | createSubjectApiSubjectsPostResponse422 | createSubjectApiSubjectsPostResponse429) & {
  headers: Headers;
};

export type createSubjectApiSubjectsPostResponse = (createSubjectApiSubjectsPostResponseSuccess | createSubjectApiSubjectsPostResponseError)

export const getCreateSubjectApiSubjectsPostUrl = () => {


  

  return `/api/subjects/`
}

export const createSubjectApiSubjectsPost = async (subjectCreate: SubjectCreate, options?: RequestInit): Promise<createSubjectApiSubjectsPostResponse> => {
  
  return customInstance<createSubjectApiSubjectsPostResponse>(getCreateSubjectApiSubjectsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      subjectCreate,)
  }
);}




export const getCreateSubjectApiSubjectsPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSubjectApiSubjectsPost>>, TError,{data: SubjectCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSubjectApiSubjectsPost>>, TError,{data: SubjectCreate}, TContext> => {

const mutationKey = ['createSubjectApiSubjectsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSubjectApiSubjectsPost>>, {data: SubjectCreate}> = (props) => {
          const {data} = props ?? {};

          return  createSubjectApiSubjectsPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSubjectApiSubjectsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createSubjectApiSubjectsPost>>>
    export type CreateSubjectApiSubjectsPostMutationBody = SubjectCreate
    export type CreateSubjectApiSubjectsPostMutationError = ErrorResponse

    /**
 * @summary Create Subject
 */
export const useCreateSubjectApiSubjectsPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSubjectApiSubjectsPost>>, TError,{data: SubjectCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createSubjectApiSubjectsPost>>,
        TError,
        {data: SubjectCreate},
        TContext
      > => {
      return useMutation(getCreateSubjectApiSubjectsPostMutationOptions(options), queryClient);
    }
    /**
 * List all subjects.
 * @summary List Subjects
 */
export type listSubjectsApiSubjectsGetResponse200 = {
  data: SubjectRead[]
  status: 200
}

export type listSubjectsApiSubjectsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listSubjectsApiSubjectsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listSubjectsApiSubjectsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listSubjectsApiSubjectsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listSubjectsApiSubjectsGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listSubjectsApiSubjectsGetResponseSuccess = (listSubjectsApiSubjectsGetResponse200) & {
  headers: Headers;
};
export type listSubjectsApiSubjectsGetResponseError = (listSubjectsApiSubjectsGetResponse401 | listSubjectsApiSubjectsGetResponse403 | listSubjectsApiSubjectsGetResponse404 | listSubjectsApiSubjectsGetResponse422 | listSubjectsApiSubjectsGetResponse429) & {
  headers: Headers;
};

export type listSubjectsApiSubjectsGetResponse = (listSubjectsApiSubjectsGetResponseSuccess | listSubjectsApiSubjectsGetResponseError)

export const getListSubjectsApiSubjectsGetUrl = (params?: ListSubjectsApiSubjectsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/subjects/?${stringifiedParams}` : `/api/subjects/`
}

export const listSubjectsApiSubjectsGet = async (params?: ListSubjectsApiSubjectsGetParams, options?: RequestInit): Promise<listSubjectsApiSubjectsGetResponse> => {
  
  return customInstance<listSubjectsApiSubjectsGetResponse>(getListSubjectsApiSubjectsGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListSubjectsApiSubjectsGetQueryKey = (params?: ListSubjectsApiSubjectsGetParams,) => {
    return [
    `/api/subjects/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListSubjectsApiSubjectsGetQueryOptions = <TData = Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError = ErrorResponse>(params?: ListSubjectsApiSubjectsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSubjectsApiSubjectsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>> = ({ signal }) => listSubjectsApiSubjectsGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSubjectsApiSubjectsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>>
export type ListSubjectsApiSubjectsGetQueryError = ErrorResponse


export function useListSubjectsApiSubjectsGet<TData = Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError = ErrorResponse>(
 params: undefined |  ListSubjectsApiSubjectsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>,
          TError,
          Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSubjectsApiSubjectsGet<TData = Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError = ErrorResponse>(
 params?: ListSubjectsApiSubjectsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>,
          TError,
          Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSubjectsApiSubjectsGet<TData = Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError = ErrorResponse>(
 params?: ListSubjectsApiSubjectsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Subjects
 */

export function useListSubjectsApiSubjectsGet<TData = Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError = ErrorResponse>(
 params?: ListSubjectsApiSubjectsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSubjectsApiSubjectsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSubjectsApiSubjectsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get subject by ID.
 * @summary Get Subject
 */
export type getSubjectApiSubjectsSubjectIdGetResponse200 = {
  data: SubjectRead
  status: 200
}

export type getSubjectApiSubjectsSubjectIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getSubjectApiSubjectsSubjectIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getSubjectApiSubjectsSubjectIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getSubjectApiSubjectsSubjectIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getSubjectApiSubjectsSubjectIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getSubjectApiSubjectsSubjectIdGetResponseSuccess = (getSubjectApiSubjectsSubjectIdGetResponse200) & {
  headers: Headers;
};
export type getSubjectApiSubjectsSubjectIdGetResponseError = (getSubjectApiSubjectsSubjectIdGetResponse401 | getSubjectApiSubjectsSubjectIdGetResponse403 | getSubjectApiSubjectsSubjectIdGetResponse404 | getSubjectApiSubjectsSubjectIdGetResponse422 | getSubjectApiSubjectsSubjectIdGetResponse429) & {
  headers: Headers;
};

export type getSubjectApiSubjectsSubjectIdGetResponse = (getSubjectApiSubjectsSubjectIdGetResponseSuccess | getSubjectApiSubjectsSubjectIdGetResponseError)

export const getGetSubjectApiSubjectsSubjectIdGetUrl = (subjectId: number,) => {


  

  return `/api/subjects/${subjectId}`
}

export const getSubjectApiSubjectsSubjectIdGet = async (subjectId: number, options?: RequestInit): Promise<getSubjectApiSubjectsSubjectIdGetResponse> => {
  
  return customInstance<getSubjectApiSubjectsSubjectIdGetResponse>(getGetSubjectApiSubjectsSubjectIdGetUrl(subjectId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetSubjectApiSubjectsSubjectIdGetQueryKey = (subjectId: number,) => {
    return [
    `/api/subjects/${subjectId}`
    ] as const;
    }

    
export const getGetSubjectApiSubjectsSubjectIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError = ErrorResponse>(subjectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSubjectApiSubjectsSubjectIdGetQueryKey(subjectId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>> = ({ signal }) => getSubjectApiSubjectsSubjectIdGet(subjectId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(subjectId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSubjectApiSubjectsSubjectIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>>
export type GetSubjectApiSubjectsSubjectIdGetQueryError = ErrorResponse


export function useGetSubjectApiSubjectsSubjectIdGet<TData = Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError = ErrorResponse>(
 subjectId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubjectApiSubjectsSubjectIdGet<TData = Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError = ErrorResponse>(
 subjectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>,
          TError,
          Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSubjectApiSubjectsSubjectIdGet<TData = Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError = ErrorResponse>(
 subjectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Subject
 */

export function useGetSubjectApiSubjectsSubjectIdGet<TData = Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError = ErrorResponse>(
 subjectId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSubjectApiSubjectsSubjectIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSubjectApiSubjectsSubjectIdGetQueryOptions(subjectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update subject information (teachers and admins only).
 * @summary Update Subject
 */
export type updateSubjectApiSubjectsSubjectIdPatchResponse200 = {
  data: SubjectRead
  status: 200
}

export type updateSubjectApiSubjectsSubjectIdPatchResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateSubjectApiSubjectsSubjectIdPatchResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateSubjectApiSubjectsSubjectIdPatchResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateSubjectApiSubjectsSubjectIdPatchResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateSubjectApiSubjectsSubjectIdPatchResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type updateSubjectApiSubjectsSubjectIdPatchResponseSuccess = (updateSubjectApiSubjectsSubjectIdPatchResponse200) & {
  headers: Headers;
};
export type updateSubjectApiSubjectsSubjectIdPatchResponseError = (updateSubjectApiSubjectsSubjectIdPatchResponse401 | updateSubjectApiSubjectsSubjectIdPatchResponse403 | updateSubjectApiSubjectsSubjectIdPatchResponse404 | updateSubjectApiSubjectsSubjectIdPatchResponse422 | updateSubjectApiSubjectsSubjectIdPatchResponse429) & {
  headers: Headers;
};

export type updateSubjectApiSubjectsSubjectIdPatchResponse = (updateSubjectApiSubjectsSubjectIdPatchResponseSuccess | updateSubjectApiSubjectsSubjectIdPatchResponseError)

export const getUpdateSubjectApiSubjectsSubjectIdPatchUrl = (subjectId: number,) => {


  

  return `/api/subjects/${subjectId}`
}

export const updateSubjectApiSubjectsSubjectIdPatch = async (subjectId: number,
    subjectUpdate: SubjectUpdate, options?: RequestInit): Promise<updateSubjectApiSubjectsSubjectIdPatchResponse> => {
  
  return customInstance<updateSubjectApiSubjectsSubjectIdPatchResponse>(getUpdateSubjectApiSubjectsSubjectIdPatchUrl(subjectId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      subjectUpdate,)
  }
);}




export const getUpdateSubjectApiSubjectsSubjectIdPatchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSubjectApiSubjectsSubjectIdPatch>>, TError,{subjectId: number;data: SubjectUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSubjectApiSubjectsSubjectIdPatch>>, TError,{subjectId: number;data: SubjectUpdate}, TContext> => {

const mutationKey = ['updateSubjectApiSubjectsSubjectIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSubjectApiSubjectsSubjectIdPatch>>, {subjectId: number;data: SubjectUpdate}> = (props) => {
          const {subjectId,data} = props ?? {};

          return  updateSubjectApiSubjectsSubjectIdPatch(subjectId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSubjectApiSubjectsSubjectIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateSubjectApiSubjectsSubjectIdPatch>>>
    export type UpdateSubjectApiSubjectsSubjectIdPatchMutationBody = SubjectUpdate
    export type UpdateSubjectApiSubjectsSubjectIdPatchMutationError = ErrorResponse

    /**
 * @summary Update Subject
 */
export const useUpdateSubjectApiSubjectsSubjectIdPatch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSubjectApiSubjectsSubjectIdPatch>>, TError,{subjectId: number;data: SubjectUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSubjectApiSubjectsSubjectIdPatch>>,
        TError,
        {subjectId: number;data: SubjectUpdate},
        TContext
      > => {
      return useMutation(getUpdateSubjectApiSubjectsSubjectIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete a subject (teachers and admins only).
 * @summary Delete Subject
 */
export type deleteSubjectApiSubjectsSubjectIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteSubjectApiSubjectsSubjectIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteSubjectApiSubjectsSubjectIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteSubjectApiSubjectsSubjectIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteSubjectApiSubjectsSubjectIdDeleteResponse422 = {
  data: ErrorResponse
  status: 422
}

export type deleteSubjectApiSubjectsSubjectIdDeleteResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type deleteSubjectApiSubjectsSubjectIdDeleteResponseSuccess = (deleteSubjectApiSubjectsSubjectIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteSubjectApiSubjectsSubjectIdDeleteResponseError = (deleteSubjectApiSubjectsSubjectIdDeleteResponse401 | deleteSubjectApiSubjectsSubjectIdDeleteResponse403 | deleteSubjectApiSubjectsSubjectIdDeleteResponse404 | deleteSubjectApiSubjectsSubjectIdDeleteResponse422 | deleteSubjectApiSubjectsSubjectIdDeleteResponse429) & {
  headers: Headers;
};

export type deleteSubjectApiSubjectsSubjectIdDeleteResponse = (deleteSubjectApiSubjectsSubjectIdDeleteResponseSuccess | deleteSubjectApiSubjectsSubjectIdDeleteResponseError)

export const getDeleteSubjectApiSubjectsSubjectIdDeleteUrl = (subjectId: number,) => {


  

  return `/api/subjects/${subjectId}`
}

export const deleteSubjectApiSubjectsSubjectIdDelete = async (subjectId: number, options?: RequestInit): Promise<deleteSubjectApiSubjectsSubjectIdDeleteResponse> => {
  
  return customInstance<deleteSubjectApiSubjectsSubjectIdDeleteResponse>(getDeleteSubjectApiSubjectsSubjectIdDeleteUrl(subjectId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteSubjectApiSubjectsSubjectIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSubjectApiSubjectsSubjectIdDelete>>, TError,{subjectId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSubjectApiSubjectsSubjectIdDelete>>, TError,{subjectId: number}, TContext> => {

const mutationKey = ['deleteSubjectApiSubjectsSubjectIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSubjectApiSubjectsSubjectIdDelete>>, {subjectId: number}> = (props) => {
          const {subjectId} = props ?? {};

          return  deleteSubjectApiSubjectsSubjectIdDelete(subjectId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteSubjectApiSubjectsSubjectIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSubjectApiSubjectsSubjectIdDelete>>>
    
    export type DeleteSubjectApiSubjectsSubjectIdDeleteMutationError = ErrorResponse

    /**
 * @summary Delete Subject
 */
export const useDeleteSubjectApiSubjectsSubjectIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSubjectApiSubjectsSubjectIdDelete>>, TError,{subjectId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteSubjectApiSubjectsSubjectIdDelete>>,
        TError,
        {subjectId: number},
        TContext
      > => {
      return useMutation(getDeleteSubjectApiSubjectsSubjectIdDeleteMutationOptions(options), queryClient);
    }
    