/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkGradesCreate,
  ErrorResponse,
  GradeCreate,
  GradeRead,
  GradeUpdate,
  ListGradesApiGradesGetParams
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create or update multiple grades for an assessment event.
 * @summary Create Bulk Grades
 */
export type createBulkGradesApiGradesBulkPostResponse200 = {
  data: unknown
  status: 200
}

export type createBulkGradesApiGradesBulkPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createBulkGradesApiGradesBulkPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createBulkGradesApiGradesBulkPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createBulkGradesApiGradesBulkPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createBulkGradesApiGradesBulkPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type createBulkGradesApiGradesBulkPostResponseSuccess = (createBulkGradesApiGradesBulkPostResponse200) & {
  headers: Headers;
};
export type createBulkGradesApiGradesBulkPostResponseError = (createBulkGradesApiGradesBulkPostResponse401 | createBulkGradesApiGradesBulkPostResponse403 | createBulkGradesApiGradesBulkPostResponse404 | createBulkGradesApiGradesBulkPostResponse422 | createBulkGradesApiGradesBulkPostResponse429) & {
  headers: Headers;
};

export type createBulkGradesApiGradesBulkPostResponse = (createBulkGradesApiGradesBulkPostResponseSuccess | createBulkGradesApiGradesBulkPostResponseError)

export const getCreateBulkGradesApiGradesBulkPostUrl = () => {


  

  return `/api/grades/bulk`
}

export const createBulkGradesApiGradesBulkPost = async (bulkGradesCreate: BulkGradesCreate, options?: RequestInit): Promise<createBulkGradesApiGradesBulkPostResponse> => {
  
  return customInstance<createBulkGradesApiGradesBulkPostResponse>(getCreateBulkGradesApiGradesBulkPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkGradesCreate,)
  }
);}




export const getCreateBulkGradesApiGradesBulkPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBulkGradesApiGradesBulkPost>>, TError,{data: BulkGradesCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createBulkGradesApiGradesBulkPost>>, TError,{data: BulkGradesCreate}, TContext> => {

const mutationKey = ['createBulkGradesApiGradesBulkPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createBulkGradesApiGradesBulkPost>>, {data: BulkGradesCreate}> = (props) => {
          const {data} = props ?? {};

          return  createBulkGradesApiGradesBulkPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateBulkGradesApiGradesBulkPostMutationResult = NonNullable<Awaited<ReturnType<typeof createBulkGradesApiGradesBulkPost>>>
    export type CreateBulkGradesApiGradesBulkPostMutationBody = BulkGradesCreate
    export type CreateBulkGradesApiGradesBulkPostMutationError = ErrorResponse

    /**
 * @summary Create Bulk Grades
 */
export const useCreateBulkGradesApiGradesBulkPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createBulkGradesApiGradesBulkPost>>, TError,{data: BulkGradesCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createBulkGradesApiGradesBulkPost>>,
        TError,
        {data: BulkGradesCreate},
        TContext
      > => {
      return useMutation(getCreateBulkGradesApiGradesBulkPostMutationOptions(options), queryClient);
    }
    /**
 * Create a new grade (teachers and admins only).
 * @summary Create Grade
 */
export type createGradeApiGradesPostResponse201 = {
  data: GradeRead
  status: 201
}

export type createGradeApiGradesPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createGradeApiGradesPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createGradeApiGradesPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createGradeApiGradesPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createGradeApiGradesPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type createGradeApiGradesPostResponseSuccess = (createGradeApiGradesPostResponse201) & {
  headers: Headers;
};
export type createGradeApiGradesPostResponseError = (createGradeApiGradesPostResponse401 | createGradeApiGradesPostResponse403 | createGradeApiGradesPostResponse404 | createGradeApiGradesPostResponse422 | createGradeApiGradesPostResponse429) & {
  headers: Headers;
};

export type createGradeApiGradesPostResponse = (createGradeApiGradesPostResponseSuccess | createGradeApiGradesPostResponseError)

export const getCreateGradeApiGradesPostUrl = () => {


  

  return `/api/grades/`
}

export const createGradeApiGradesPost = async (gradeCreate: GradeCreate, options?: RequestInit): Promise<createGradeApiGradesPostResponse> => {
  
  return customInstance<createGradeApiGradesPostResponse>(getCreateGradeApiGradesPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      gradeCreate,)
  }
);}




export const getCreateGradeApiGradesPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGradeApiGradesPost>>, TError,{data: GradeCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createGradeApiGradesPost>>, TError,{data: GradeCreate}, TContext> => {

const mutationKey = ['createGradeApiGradesPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGradeApiGradesPost>>, {data: GradeCreate}> = (props) => {
          const {data} = props ?? {};

          return  createGradeApiGradesPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGradeApiGradesPostMutationResult = NonNullable<Awaited<ReturnType<typeof createGradeApiGradesPost>>>
    export type CreateGradeApiGradesPostMutationBody = GradeCreate
    export type CreateGradeApiGradesPostMutationError = ErrorResponse

    /**
 * @summary Create Grade
 */
export const useCreateGradeApiGradesPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGradeApiGradesPost>>, TError,{data: GradeCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGradeApiGradesPost>>,
        TError,
        {data: GradeCreate},
        TContext
      > => {
      return useMutation(getCreateGradeApiGradesPostMutationOptions(options), queryClient);
    }
    /**
 * List grades with optional filters.
 * @summary List Grades
 */
export type listGradesApiGradesGetResponse200 = {
  data: GradeRead[]
  status: 200
}

export type listGradesApiGradesGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listGradesApiGradesGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listGradesApiGradesGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listGradesApiGradesGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listGradesApiGradesGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listGradesApiGradesGetResponseSuccess = (listGradesApiGradesGetResponse200) & {
  headers: Headers;
};
export type listGradesApiGradesGetResponseError = (listGradesApiGradesGetResponse401 | listGradesApiGradesGetResponse403 | listGradesApiGradesGetResponse404 | listGradesApiGradesGetResponse422 | listGradesApiGradesGetResponse429) & {
  headers: Headers;
};

export type listGradesApiGradesGetResponse = (listGradesApiGradesGetResponseSuccess | listGradesApiGradesGetResponseError)

export const getListGradesApiGradesGetUrl = (params?: ListGradesApiGradesGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/grades/?${stringifiedParams}` : `/api/grades/`
}

export const listGradesApiGradesGet = async (params?: ListGradesApiGradesGetParams, options?: RequestInit): Promise<listGradesApiGradesGetResponse> => {
  
  return customInstance<listGradesApiGradesGetResponse>(getListGradesApiGradesGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListGradesApiGradesGetQueryKey = (params?: ListGradesApiGradesGetParams,) => {
    return [
    `/api/grades/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListGradesApiGradesGetQueryOptions = <TData = Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError = ErrorResponse>(params?: ListGradesApiGradesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGradesApiGradesGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGradesApiGradesGet>>> = ({ signal }) => listGradesApiGradesGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGradesApiGradesGetQueryResult = NonNullable<Awaited<ReturnType<typeof listGradesApiGradesGet>>>
export type ListGradesApiGradesGetQueryError = ErrorResponse


export function useListGradesApiGradesGet<TData = Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError = ErrorResponse>(
 params: undefined |  ListGradesApiGradesGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGradesApiGradesGet>>,
          TError,
          Awaited<ReturnType<typeof listGradesApiGradesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGradesApiGradesGet<TData = Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError = ErrorResponse>(
 params?: ListGradesApiGradesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGradesApiGradesGet>>,
          TError,
          Awaited<ReturnType<typeof listGradesApiGradesGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGradesApiGradesGet<TData = Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError = ErrorResponse>(
 params?: ListGradesApiGradesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Grades
 */

export function useListGradesApiGradesGet<TData = Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError = ErrorResponse>(
 params?: ListGradesApiGradesGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGradesApiGradesGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGradesApiGradesGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get grade by ID.
 * @summary Get Grade
 */
export type getGradeApiGradesGradeIdGetResponse200 = {
  data: GradeRead
  status: 200
}

export type getGradeApiGradesGradeIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getGradeApiGradesGradeIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getGradeApiGradesGradeIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getGradeApiGradesGradeIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getGradeApiGradesGradeIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getGradeApiGradesGradeIdGetResponseSuccess = (getGradeApiGradesGradeIdGetResponse200) & {
  headers: Headers;
};
export type getGradeApiGradesGradeIdGetResponseError = (getGradeApiGradesGradeIdGetResponse401 | getGradeApiGradesGradeIdGetResponse403 | getGradeApiGradesGradeIdGetResponse404 | getGradeApiGradesGradeIdGetResponse422 | getGradeApiGradesGradeIdGetResponse429) & {
  headers: Headers;
};

export type getGradeApiGradesGradeIdGetResponse = (getGradeApiGradesGradeIdGetResponseSuccess | getGradeApiGradesGradeIdGetResponseError)

export const getGetGradeApiGradesGradeIdGetUrl = (gradeId: number,) => {


  

  return `/api/grades/${gradeId}`
}

export const getGradeApiGradesGradeIdGet = async (gradeId: number, options?: RequestInit): Promise<getGradeApiGradesGradeIdGetResponse> => {
  
  return customInstance<getGradeApiGradesGradeIdGetResponse>(getGetGradeApiGradesGradeIdGetUrl(gradeId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGradeApiGradesGradeIdGetQueryKey = (gradeId: number,) => {
    return [
    `/api/grades/${gradeId}`
    ] as const;
    }

    
export const getGetGradeApiGradesGradeIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError = ErrorResponse>(gradeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGradeApiGradesGradeIdGetQueryKey(gradeId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>> = ({ signal }) => getGradeApiGradesGradeIdGet(gradeId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(gradeId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGradeApiGradesGradeIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>>
export type GetGradeApiGradesGradeIdGetQueryError = ErrorResponse


export function useGetGradeApiGradesGradeIdGet<TData = Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError = ErrorResponse>(
 gradeId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>,
          TError,
          Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGradeApiGradesGradeIdGet<TData = Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError = ErrorResponse>(
 gradeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>,
          TError,
          Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGradeApiGradesGradeIdGet<TData = Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError = ErrorResponse>(
 gradeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Grade
 */

export function useGetGradeApiGradesGradeIdGet<TData = Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError = ErrorResponse>(
 gradeId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradeApiGradesGradeIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGradeApiGradesGradeIdGetQueryOptions(gradeId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update grade (teachers and admins only).
 * @summary Update Grade
 */
export type updateGradeApiGradesGradeIdPatchResponse200 = {
  data: GradeRead
  status: 200
}

export type updateGradeApiGradesGradeIdPatchResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateGradeApiGradesGradeIdPatchResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateGradeApiGradesGradeIdPatchResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateGradeApiGradesGradeIdPatchResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateGradeApiGradesGradeIdPatchResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type updateGradeApiGradesGradeIdPatchResponseSuccess = (updateGradeApiGradesGradeIdPatchResponse200) & {
  headers: Headers;
};
export type updateGradeApiGradesGradeIdPatchResponseError = (updateGradeApiGradesGradeIdPatchResponse401 | updateGradeApiGradesGradeIdPatchResponse403 | updateGradeApiGradesGradeIdPatchResponse404 | updateGradeApiGradesGradeIdPatchResponse422 | updateGradeApiGradesGradeIdPatchResponse429) & {
  headers: Headers;
};

export type updateGradeApiGradesGradeIdPatchResponse = (updateGradeApiGradesGradeIdPatchResponseSuccess | updateGradeApiGradesGradeIdPatchResponseError)

export const getUpdateGradeApiGradesGradeIdPatchUrl = (gradeId: number,) => {


  

  return `/api/grades/${gradeId}`
}

export const updateGradeApiGradesGradeIdPatch = async (gradeId: number,
    gradeUpdate: GradeUpdate, options?: RequestInit): Promise<updateGradeApiGradesGradeIdPatchResponse> => {
  
  return customInstance<updateGradeApiGradesGradeIdPatchResponse>(getUpdateGradeApiGradesGradeIdPatchUrl(gradeId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      gradeUpdate,)
  }
);}




export const getUpdateGradeApiGradesGradeIdPatchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGradeApiGradesGradeIdPatch>>, TError,{gradeId: number;data: GradeUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateGradeApiGradesGradeIdPatch>>, TError,{gradeId: number;data: GradeUpdate}, TContext> => {

const mutationKey = ['updateGradeApiGradesGradeIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGradeApiGradesGradeIdPatch>>, {gradeId: number;data: GradeUpdate}> = (props) => {
          const {gradeId,data} = props ?? {};

          return  updateGradeApiGradesGradeIdPatch(gradeId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateGradeApiGradesGradeIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateGradeApiGradesGradeIdPatch>>>
    export type UpdateGradeApiGradesGradeIdPatchMutationBody = GradeUpdate
    export type UpdateGradeApiGradesGradeIdPatchMutationError = ErrorResponse

    /**
 * @summary Update Grade
 */
export const useUpdateGradeApiGradesGradeIdPatch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGradeApiGradesGradeIdPatch>>, TError,{gradeId: number;data: GradeUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateGradeApiGradesGradeIdPatch>>,
        TError,
        {gradeId: number;data: GradeUpdate},
        TContext
      > => {
      return useMutation(getUpdateGradeApiGradesGradeIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete grade (teachers and admins only).
 * @summary Delete Grade
 */
export type deleteGradeApiGradesGradeIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteGradeApiGradesGradeIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteGradeApiGradesGradeIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteGradeApiGradesGradeIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteGradeApiGradesGradeIdDeleteResponse422 = {
  data: ErrorResponse
  status: 422
}

export type deleteGradeApiGradesGradeIdDeleteResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type deleteGradeApiGradesGradeIdDeleteResponseSuccess = (deleteGradeApiGradesGradeIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteGradeApiGradesGradeIdDeleteResponseError = (deleteGradeApiGradesGradeIdDeleteResponse401 | deleteGradeApiGradesGradeIdDeleteResponse403 | deleteGradeApiGradesGradeIdDeleteResponse404 | deleteGradeApiGradesGradeIdDeleteResponse422 | deleteGradeApiGradesGradeIdDeleteResponse429) & {
  headers: Headers;
};

export type deleteGradeApiGradesGradeIdDeleteResponse = (deleteGradeApiGradesGradeIdDeleteResponseSuccess | deleteGradeApiGradesGradeIdDeleteResponseError)

export const getDeleteGradeApiGradesGradeIdDeleteUrl = (gradeId: number,) => {


  

  return `/api/grades/${gradeId}`
}

export const deleteGradeApiGradesGradeIdDelete = async (gradeId: number, options?: RequestInit): Promise<deleteGradeApiGradesGradeIdDeleteResponse> => {
  
  return customInstance<deleteGradeApiGradesGradeIdDeleteResponse>(getDeleteGradeApiGradesGradeIdDeleteUrl(gradeId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteGradeApiGradesGradeIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGradeApiGradesGradeIdDelete>>, TError,{gradeId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteGradeApiGradesGradeIdDelete>>, TError,{gradeId: number}, TContext> => {

const mutationKey = ['deleteGradeApiGradesGradeIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGradeApiGradesGradeIdDelete>>, {gradeId: number}> = (props) => {
          const {gradeId} = props ?? {};

          return  deleteGradeApiGradesGradeIdDelete(gradeId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteGradeApiGradesGradeIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGradeApiGradesGradeIdDelete>>>
    
    export type DeleteGradeApiGradesGradeIdDeleteMutationError = ErrorResponse

    /**
 * @summary Delete Grade
 */
export const useDeleteGradeApiGradesGradeIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGradeApiGradesGradeIdDelete>>, TError,{gradeId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteGradeApiGradesGradeIdDelete>>,
        TError,
        {gradeId: number},
        TContext
      > => {
      return useMutation(getDeleteGradeApiGradesGradeIdDeleteMutationOptions(options), queryClient);
    }
    