/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssignmentCreate,
  AssignmentRead,
  AssignmentUpdate,
  ErrorResponse,
  GetMyAssignmentsApiAssignmentsMyGetParams,
  GetUpcomingAssignmentsApiAssignmentsUpcomingGetParams,
  ListAssignmentsApiAssignmentsGetParams
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new assignment (teachers and admins only).
 * @summary Create Assignment
 */
export type createAssignmentApiAssignmentsPostResponse201 = {
  data: AssignmentRead
  status: 201
}

export type createAssignmentApiAssignmentsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createAssignmentApiAssignmentsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createAssignmentApiAssignmentsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createAssignmentApiAssignmentsPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createAssignmentApiAssignmentsPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type createAssignmentApiAssignmentsPostResponseSuccess = (createAssignmentApiAssignmentsPostResponse201) & {
  headers: Headers;
};
export type createAssignmentApiAssignmentsPostResponseError = (createAssignmentApiAssignmentsPostResponse401 | createAssignmentApiAssignmentsPostResponse403 | createAssignmentApiAssignmentsPostResponse404 | createAssignmentApiAssignmentsPostResponse422 | createAssignmentApiAssignmentsPostResponse429) & {
  headers: Headers;
};

export type createAssignmentApiAssignmentsPostResponse = (createAssignmentApiAssignmentsPostResponseSuccess | createAssignmentApiAssignmentsPostResponseError)

export const getCreateAssignmentApiAssignmentsPostUrl = () => {


  

  return `/api/assignments/`
}

export const createAssignmentApiAssignmentsPost = async (assignmentCreate: AssignmentCreate, options?: RequestInit): Promise<createAssignmentApiAssignmentsPostResponse> => {
  
  return customInstance<createAssignmentApiAssignmentsPostResponse>(getCreateAssignmentApiAssignmentsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignmentCreate,)
  }
);}




export const getCreateAssignmentApiAssignmentsPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAssignmentApiAssignmentsPost>>, TError,{data: AssignmentCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createAssignmentApiAssignmentsPost>>, TError,{data: AssignmentCreate}, TContext> => {

const mutationKey = ['createAssignmentApiAssignmentsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createAssignmentApiAssignmentsPost>>, {data: AssignmentCreate}> = (props) => {
          const {data} = props ?? {};

          return  createAssignmentApiAssignmentsPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateAssignmentApiAssignmentsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createAssignmentApiAssignmentsPost>>>
    export type CreateAssignmentApiAssignmentsPostMutationBody = AssignmentCreate
    export type CreateAssignmentApiAssignmentsPostMutationError = ErrorResponse

    /**
 * @summary Create Assignment
 */
export const useCreateAssignmentApiAssignmentsPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createAssignmentApiAssignmentsPost>>, TError,{data: AssignmentCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createAssignmentApiAssignmentsPost>>,
        TError,
        {data: AssignmentCreate},
        TContext
      > => {
      return useMutation(getCreateAssignmentApiAssignmentsPostMutationOptions(options), queryClient);
    }
    /**
 * List assignments with optional filters.
Students only see published assignments.
 * @summary List Assignments
 */
export type listAssignmentsApiAssignmentsGetResponse200 = {
  data: AssignmentRead[]
  status: 200
}

export type listAssignmentsApiAssignmentsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listAssignmentsApiAssignmentsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listAssignmentsApiAssignmentsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listAssignmentsApiAssignmentsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listAssignmentsApiAssignmentsGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listAssignmentsApiAssignmentsGetResponseSuccess = (listAssignmentsApiAssignmentsGetResponse200) & {
  headers: Headers;
};
export type listAssignmentsApiAssignmentsGetResponseError = (listAssignmentsApiAssignmentsGetResponse401 | listAssignmentsApiAssignmentsGetResponse403 | listAssignmentsApiAssignmentsGetResponse404 | listAssignmentsApiAssignmentsGetResponse422 | listAssignmentsApiAssignmentsGetResponse429) & {
  headers: Headers;
};

export type listAssignmentsApiAssignmentsGetResponse = (listAssignmentsApiAssignmentsGetResponseSuccess | listAssignmentsApiAssignmentsGetResponseError)

export const getListAssignmentsApiAssignmentsGetUrl = (params?: ListAssignmentsApiAssignmentsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/assignments/?${stringifiedParams}` : `/api/assignments/`
}

export const listAssignmentsApiAssignmentsGet = async (params?: ListAssignmentsApiAssignmentsGetParams, options?: RequestInit): Promise<listAssignmentsApiAssignmentsGetResponse> => {
  
  return customInstance<listAssignmentsApiAssignmentsGetResponse>(getListAssignmentsApiAssignmentsGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListAssignmentsApiAssignmentsGetQueryKey = (params?: ListAssignmentsApiAssignmentsGetParams,) => {
    return [
    `/api/assignments/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListAssignmentsApiAssignmentsGetQueryOptions = <TData = Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError = ErrorResponse>(params?: ListAssignmentsApiAssignmentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAssignmentsApiAssignmentsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>> = ({ signal }) => listAssignmentsApiAssignmentsGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAssignmentsApiAssignmentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>>
export type ListAssignmentsApiAssignmentsGetQueryError = ErrorResponse


export function useListAssignmentsApiAssignmentsGet<TData = Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError = ErrorResponse>(
 params: undefined |  ListAssignmentsApiAssignmentsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>,
          TError,
          Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAssignmentsApiAssignmentsGet<TData = Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError = ErrorResponse>(
 params?: ListAssignmentsApiAssignmentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>,
          TError,
          Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAssignmentsApiAssignmentsGet<TData = Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError = ErrorResponse>(
 params?: ListAssignmentsApiAssignmentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Assignments
 */

export function useListAssignmentsApiAssignmentsGet<TData = Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError = ErrorResponse>(
 params?: ListAssignmentsApiAssignmentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAssignmentsApiAssignmentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAssignmentsApiAssignmentsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get assignments for current user's group (students only).
Teachers get all their assignments.
 * @summary Get My Assignments
 */
export type getMyAssignmentsApiAssignmentsMyGetResponse200 = {
  data: AssignmentRead[]
  status: 200
}

export type getMyAssignmentsApiAssignmentsMyGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getMyAssignmentsApiAssignmentsMyGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getMyAssignmentsApiAssignmentsMyGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getMyAssignmentsApiAssignmentsMyGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getMyAssignmentsApiAssignmentsMyGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getMyAssignmentsApiAssignmentsMyGetResponseSuccess = (getMyAssignmentsApiAssignmentsMyGetResponse200) & {
  headers: Headers;
};
export type getMyAssignmentsApiAssignmentsMyGetResponseError = (getMyAssignmentsApiAssignmentsMyGetResponse401 | getMyAssignmentsApiAssignmentsMyGetResponse403 | getMyAssignmentsApiAssignmentsMyGetResponse404 | getMyAssignmentsApiAssignmentsMyGetResponse422 | getMyAssignmentsApiAssignmentsMyGetResponse429) & {
  headers: Headers;
};

export type getMyAssignmentsApiAssignmentsMyGetResponse = (getMyAssignmentsApiAssignmentsMyGetResponseSuccess | getMyAssignmentsApiAssignmentsMyGetResponseError)

export const getGetMyAssignmentsApiAssignmentsMyGetUrl = (params?: GetMyAssignmentsApiAssignmentsMyGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/assignments/my?${stringifiedParams}` : `/api/assignments/my`
}

export const getMyAssignmentsApiAssignmentsMyGet = async (params?: GetMyAssignmentsApiAssignmentsMyGetParams, options?: RequestInit): Promise<getMyAssignmentsApiAssignmentsMyGetResponse> => {
  
  return customInstance<getMyAssignmentsApiAssignmentsMyGetResponse>(getGetMyAssignmentsApiAssignmentsMyGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMyAssignmentsApiAssignmentsMyGetQueryKey = (params?: GetMyAssignmentsApiAssignmentsMyGetParams,) => {
    return [
    `/api/assignments/my`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetMyAssignmentsApiAssignmentsMyGetQueryOptions = <TData = Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError = ErrorResponse>(params?: GetMyAssignmentsApiAssignmentsMyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyAssignmentsApiAssignmentsMyGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>> = ({ signal }) => getMyAssignmentsApiAssignmentsMyGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyAssignmentsApiAssignmentsMyGetQueryResult = NonNullable<Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>>
export type GetMyAssignmentsApiAssignmentsMyGetQueryError = ErrorResponse


export function useGetMyAssignmentsApiAssignmentsMyGet<TData = Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError = ErrorResponse>(
 params: undefined |  GetMyAssignmentsApiAssignmentsMyGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>,
          TError,
          Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyAssignmentsApiAssignmentsMyGet<TData = Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError = ErrorResponse>(
 params?: GetMyAssignmentsApiAssignmentsMyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>,
          TError,
          Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyAssignmentsApiAssignmentsMyGet<TData = Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError = ErrorResponse>(
 params?: GetMyAssignmentsApiAssignmentsMyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Assignments
 */

export function useGetMyAssignmentsApiAssignmentsMyGet<TData = Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError = ErrorResponse>(
 params?: GetMyAssignmentsApiAssignmentsMyGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyAssignmentsApiAssignmentsMyGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyAssignmentsApiAssignmentsMyGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get upcoming assignments with due dates.
 * @summary Get Upcoming Assignments
 */
export type getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse200 = {
  data: AssignmentRead[]
  status: 200
}

export type getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getUpcomingAssignmentsApiAssignmentsUpcomingGetResponseSuccess = (getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse200) & {
  headers: Headers;
};
export type getUpcomingAssignmentsApiAssignmentsUpcomingGetResponseError = (getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse401 | getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse403 | getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse404 | getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse422 | getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse429) & {
  headers: Headers;
};

export type getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse = (getUpcomingAssignmentsApiAssignmentsUpcomingGetResponseSuccess | getUpcomingAssignmentsApiAssignmentsUpcomingGetResponseError)

export const getGetUpcomingAssignmentsApiAssignmentsUpcomingGetUrl = (params?: GetUpcomingAssignmentsApiAssignmentsUpcomingGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/assignments/upcoming?${stringifiedParams}` : `/api/assignments/upcoming`
}

export const getUpcomingAssignmentsApiAssignmentsUpcomingGet = async (params?: GetUpcomingAssignmentsApiAssignmentsUpcomingGetParams, options?: RequestInit): Promise<getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse> => {
  
  return customInstance<getUpcomingAssignmentsApiAssignmentsUpcomingGetResponse>(getGetUpcomingAssignmentsApiAssignmentsUpcomingGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUpcomingAssignmentsApiAssignmentsUpcomingGetQueryKey = (params?: GetUpcomingAssignmentsApiAssignmentsUpcomingGetParams,) => {
    return [
    `/api/assignments/upcoming`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetUpcomingAssignmentsApiAssignmentsUpcomingGetQueryOptions = <TData = Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError = ErrorResponse>(params?: GetUpcomingAssignmentsApiAssignmentsUpcomingGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUpcomingAssignmentsApiAssignmentsUpcomingGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>> = ({ signal }) => getUpcomingAssignmentsApiAssignmentsUpcomingGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUpcomingAssignmentsApiAssignmentsUpcomingGetQueryResult = NonNullable<Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>>
export type GetUpcomingAssignmentsApiAssignmentsUpcomingGetQueryError = ErrorResponse


export function useGetUpcomingAssignmentsApiAssignmentsUpcomingGet<TData = Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError = ErrorResponse>(
 params: undefined |  GetUpcomingAssignmentsApiAssignmentsUpcomingGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>,
          TError,
          Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUpcomingAssignmentsApiAssignmentsUpcomingGet<TData = Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError = ErrorResponse>(
 params?: GetUpcomingAssignmentsApiAssignmentsUpcomingGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>,
          TError,
          Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUpcomingAssignmentsApiAssignmentsUpcomingGet<TData = Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError = ErrorResponse>(
 params?: GetUpcomingAssignmentsApiAssignmentsUpcomingGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Upcoming Assignments
 */

export function useGetUpcomingAssignmentsApiAssignmentsUpcomingGet<TData = Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError = ErrorResponse>(
 params?: GetUpcomingAssignmentsApiAssignmentsUpcomingGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUpcomingAssignmentsApiAssignmentsUpcomingGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUpcomingAssignmentsApiAssignmentsUpcomingGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get assignment by ID.
 * @summary Get Assignment
 */
export type getAssignmentApiAssignmentsAssignmentIdGetResponse200 = {
  data: AssignmentRead
  status: 200
}

export type getAssignmentApiAssignmentsAssignmentIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAssignmentApiAssignmentsAssignmentIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getAssignmentApiAssignmentsAssignmentIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAssignmentApiAssignmentsAssignmentIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getAssignmentApiAssignmentsAssignmentIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getAssignmentApiAssignmentsAssignmentIdGetResponseSuccess = (getAssignmentApiAssignmentsAssignmentIdGetResponse200) & {
  headers: Headers;
};
export type getAssignmentApiAssignmentsAssignmentIdGetResponseError = (getAssignmentApiAssignmentsAssignmentIdGetResponse401 | getAssignmentApiAssignmentsAssignmentIdGetResponse403 | getAssignmentApiAssignmentsAssignmentIdGetResponse404 | getAssignmentApiAssignmentsAssignmentIdGetResponse422 | getAssignmentApiAssignmentsAssignmentIdGetResponse429) & {
  headers: Headers;
};

export type getAssignmentApiAssignmentsAssignmentIdGetResponse = (getAssignmentApiAssignmentsAssignmentIdGetResponseSuccess | getAssignmentApiAssignmentsAssignmentIdGetResponseError)

export const getGetAssignmentApiAssignmentsAssignmentIdGetUrl = (assignmentId: number,) => {


  

  return `/api/assignments/${assignmentId}`
}

export const getAssignmentApiAssignmentsAssignmentIdGet = async (assignmentId: number, options?: RequestInit): Promise<getAssignmentApiAssignmentsAssignmentIdGetResponse> => {
  
  return customInstance<getAssignmentApiAssignmentsAssignmentIdGetResponse>(getGetAssignmentApiAssignmentsAssignmentIdGetUrl(assignmentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAssignmentApiAssignmentsAssignmentIdGetQueryKey = (assignmentId: number,) => {
    return [
    `/api/assignments/${assignmentId}`
    ] as const;
    }

    
export const getGetAssignmentApiAssignmentsAssignmentIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError = ErrorResponse>(assignmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAssignmentApiAssignmentsAssignmentIdGetQueryKey(assignmentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>> = ({ signal }) => getAssignmentApiAssignmentsAssignmentIdGet(assignmentId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(assignmentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAssignmentApiAssignmentsAssignmentIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>>
export type GetAssignmentApiAssignmentsAssignmentIdGetQueryError = ErrorResponse


export function useGetAssignmentApiAssignmentsAssignmentIdGet<TData = Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError = ErrorResponse>(
 assignmentId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssignmentApiAssignmentsAssignmentIdGet<TData = Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError = ErrorResponse>(
 assignmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAssignmentApiAssignmentsAssignmentIdGet<TData = Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError = ErrorResponse>(
 assignmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Assignment
 */

export function useGetAssignmentApiAssignmentsAssignmentIdGet<TData = Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError = ErrorResponse>(
 assignmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAssignmentApiAssignmentsAssignmentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAssignmentApiAssignmentsAssignmentIdGetQueryOptions(assignmentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update assignment (teachers and admins only).
 * @summary Update Assignment
 */
export type updateAssignmentApiAssignmentsAssignmentIdPatchResponse200 = {
  data: AssignmentRead
  status: 200
}

export type updateAssignmentApiAssignmentsAssignmentIdPatchResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateAssignmentApiAssignmentsAssignmentIdPatchResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateAssignmentApiAssignmentsAssignmentIdPatchResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateAssignmentApiAssignmentsAssignmentIdPatchResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateAssignmentApiAssignmentsAssignmentIdPatchResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type updateAssignmentApiAssignmentsAssignmentIdPatchResponseSuccess = (updateAssignmentApiAssignmentsAssignmentIdPatchResponse200) & {
  headers: Headers;
};
export type updateAssignmentApiAssignmentsAssignmentIdPatchResponseError = (updateAssignmentApiAssignmentsAssignmentIdPatchResponse401 | updateAssignmentApiAssignmentsAssignmentIdPatchResponse403 | updateAssignmentApiAssignmentsAssignmentIdPatchResponse404 | updateAssignmentApiAssignmentsAssignmentIdPatchResponse422 | updateAssignmentApiAssignmentsAssignmentIdPatchResponse429) & {
  headers: Headers;
};

export type updateAssignmentApiAssignmentsAssignmentIdPatchResponse = (updateAssignmentApiAssignmentsAssignmentIdPatchResponseSuccess | updateAssignmentApiAssignmentsAssignmentIdPatchResponseError)

export const getUpdateAssignmentApiAssignmentsAssignmentIdPatchUrl = (assignmentId: number,) => {


  

  return `/api/assignments/${assignmentId}`
}

export const updateAssignmentApiAssignmentsAssignmentIdPatch = async (assignmentId: number,
    assignmentUpdate: AssignmentUpdate, options?: RequestInit): Promise<updateAssignmentApiAssignmentsAssignmentIdPatchResponse> => {
  
  return customInstance<updateAssignmentApiAssignmentsAssignmentIdPatchResponse>(getUpdateAssignmentApiAssignmentsAssignmentIdPatchUrl(assignmentId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignmentUpdate,)
  }
);}




export const getUpdateAssignmentApiAssignmentsAssignmentIdPatchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAssignmentApiAssignmentsAssignmentIdPatch>>, TError,{assignmentId: number;data: AssignmentUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAssignmentApiAssignmentsAssignmentIdPatch>>, TError,{assignmentId: number;data: AssignmentUpdate}, TContext> => {

const mutationKey = ['updateAssignmentApiAssignmentsAssignmentIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAssignmentApiAssignmentsAssignmentIdPatch>>, {assignmentId: number;data: AssignmentUpdate}> = (props) => {
          const {assignmentId,data} = props ?? {};

          return  updateAssignmentApiAssignmentsAssignmentIdPatch(assignmentId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAssignmentApiAssignmentsAssignmentIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateAssignmentApiAssignmentsAssignmentIdPatch>>>
    export type UpdateAssignmentApiAssignmentsAssignmentIdPatchMutationBody = AssignmentUpdate
    export type UpdateAssignmentApiAssignmentsAssignmentIdPatchMutationError = ErrorResponse

    /**
 * @summary Update Assignment
 */
export const useUpdateAssignmentApiAssignmentsAssignmentIdPatch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAssignmentApiAssignmentsAssignmentIdPatch>>, TError,{assignmentId: number;data: AssignmentUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAssignmentApiAssignmentsAssignmentIdPatch>>,
        TError,
        {assignmentId: number;data: AssignmentUpdate},
        TContext
      > => {
      return useMutation(getUpdateAssignmentApiAssignmentsAssignmentIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete assignment (teachers and admins only).
 * @summary Delete Assignment
 */
export type deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse422 = {
  data: ErrorResponse
  status: 422
}

export type deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type deleteAssignmentApiAssignmentsAssignmentIdDeleteResponseSuccess = (deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteAssignmentApiAssignmentsAssignmentIdDeleteResponseError = (deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse401 | deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse403 | deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse404 | deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse422 | deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse429) & {
  headers: Headers;
};

export type deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse = (deleteAssignmentApiAssignmentsAssignmentIdDeleteResponseSuccess | deleteAssignmentApiAssignmentsAssignmentIdDeleteResponseError)

export const getDeleteAssignmentApiAssignmentsAssignmentIdDeleteUrl = (assignmentId: number,) => {


  

  return `/api/assignments/${assignmentId}`
}

export const deleteAssignmentApiAssignmentsAssignmentIdDelete = async (assignmentId: number, options?: RequestInit): Promise<deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse> => {
  
  return customInstance<deleteAssignmentApiAssignmentsAssignmentIdDeleteResponse>(getDeleteAssignmentApiAssignmentsAssignmentIdDeleteUrl(assignmentId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteAssignmentApiAssignmentsAssignmentIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssignmentApiAssignmentsAssignmentIdDelete>>, TError,{assignmentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAssignmentApiAssignmentsAssignmentIdDelete>>, TError,{assignmentId: number}, TContext> => {

const mutationKey = ['deleteAssignmentApiAssignmentsAssignmentIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAssignmentApiAssignmentsAssignmentIdDelete>>, {assignmentId: number}> = (props) => {
          const {assignmentId} = props ?? {};

          return  deleteAssignmentApiAssignmentsAssignmentIdDelete(assignmentId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAssignmentApiAssignmentsAssignmentIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAssignmentApiAssignmentsAssignmentIdDelete>>>
    
    export type DeleteAssignmentApiAssignmentsAssignmentIdDeleteMutationError = ErrorResponse

    /**
 * @summary Delete Assignment
 */
export const useDeleteAssignmentApiAssignmentsAssignmentIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAssignmentApiAssignmentsAssignmentIdDelete>>, TError,{assignmentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAssignmentApiAssignmentsAssignmentIdDelete>>,
        TError,
        {assignmentId: number},
        TContext
      > => {
      return useMutation(getDeleteAssignmentApiAssignmentsAssignmentIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Publish an assignment (teachers and admins only).
 * @summary Publish Assignment
 */
export type publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse200 = {
  data: AssignmentRead
  status: 200
}

export type publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type publishAssignmentApiAssignmentsAssignmentIdPublishPostResponseSuccess = (publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse200) & {
  headers: Headers;
};
export type publishAssignmentApiAssignmentsAssignmentIdPublishPostResponseError = (publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse401 | publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse403 | publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse404 | publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse422 | publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse429) & {
  headers: Headers;
};

export type publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse = (publishAssignmentApiAssignmentsAssignmentIdPublishPostResponseSuccess | publishAssignmentApiAssignmentsAssignmentIdPublishPostResponseError)

export const getPublishAssignmentApiAssignmentsAssignmentIdPublishPostUrl = (assignmentId: number,) => {


  

  return `/api/assignments/${assignmentId}/publish`
}

export const publishAssignmentApiAssignmentsAssignmentIdPublishPost = async (assignmentId: number, options?: RequestInit): Promise<publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse> => {
  
  return customInstance<publishAssignmentApiAssignmentsAssignmentIdPublishPostResponse>(getPublishAssignmentApiAssignmentsAssignmentIdPublishPostUrl(assignmentId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getPublishAssignmentApiAssignmentsAssignmentIdPublishPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishAssignmentApiAssignmentsAssignmentIdPublishPost>>, TError,{assignmentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof publishAssignmentApiAssignmentsAssignmentIdPublishPost>>, TError,{assignmentId: number}, TContext> => {

const mutationKey = ['publishAssignmentApiAssignmentsAssignmentIdPublishPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof publishAssignmentApiAssignmentsAssignmentIdPublishPost>>, {assignmentId: number}> = (props) => {
          const {assignmentId} = props ?? {};

          return  publishAssignmentApiAssignmentsAssignmentIdPublishPost(assignmentId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PublishAssignmentApiAssignmentsAssignmentIdPublishPostMutationResult = NonNullable<Awaited<ReturnType<typeof publishAssignmentApiAssignmentsAssignmentIdPublishPost>>>
    
    export type PublishAssignmentApiAssignmentsAssignmentIdPublishPostMutationError = ErrorResponse

    /**
 * @summary Publish Assignment
 */
export const usePublishAssignmentApiAssignmentsAssignmentIdPublishPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof publishAssignmentApiAssignmentsAssignmentIdPublishPost>>, TError,{assignmentId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof publishAssignmentApiAssignmentsAssignmentIdPublishPost>>,
        TError,
        {assignmentId: number},
        TContext
      > => {
      return useMutation(getPublishAssignmentApiAssignmentsAssignmentIdPublishPostMutationOptions(options), queryClient);
    }
    