/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DashboardStats,
  ErrorResponse,
  GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams,
  GetGradesDistributionApiAnalyticsGradesDistributionGetParams,
  GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetParams,
  GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetParams,
  GroupAnalytics
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get dashboard statistics for admin/teacher overview.
 * @summary Get Dashboard Stats
 */
export type getDashboardStatsApiAnalyticsDashboardGetResponse200 = {
  data: DashboardStats
  status: 200
}

export type getDashboardStatsApiAnalyticsDashboardGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getDashboardStatsApiAnalyticsDashboardGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getDashboardStatsApiAnalyticsDashboardGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getDashboardStatsApiAnalyticsDashboardGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getDashboardStatsApiAnalyticsDashboardGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getDashboardStatsApiAnalyticsDashboardGetResponseSuccess = (getDashboardStatsApiAnalyticsDashboardGetResponse200) & {
  headers: Headers;
};
export type getDashboardStatsApiAnalyticsDashboardGetResponseError = (getDashboardStatsApiAnalyticsDashboardGetResponse401 | getDashboardStatsApiAnalyticsDashboardGetResponse403 | getDashboardStatsApiAnalyticsDashboardGetResponse404 | getDashboardStatsApiAnalyticsDashboardGetResponse422 | getDashboardStatsApiAnalyticsDashboardGetResponse429) & {
  headers: Headers;
};

export type getDashboardStatsApiAnalyticsDashboardGetResponse = (getDashboardStatsApiAnalyticsDashboardGetResponseSuccess | getDashboardStatsApiAnalyticsDashboardGetResponseError)

export const getGetDashboardStatsApiAnalyticsDashboardGetUrl = () => {


  

  return `/api/analytics/dashboard`
}

export const getDashboardStatsApiAnalyticsDashboardGet = async ( options?: RequestInit): Promise<getDashboardStatsApiAnalyticsDashboardGetResponse> => {
  
  return customInstance<getDashboardStatsApiAnalyticsDashboardGetResponse>(getGetDashboardStatsApiAnalyticsDashboardGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetDashboardStatsApiAnalyticsDashboardGetQueryKey = () => {
    return [
    `/api/analytics/dashboard`
    ] as const;
    }

    
export const getGetDashboardStatsApiAnalyticsDashboardGetQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardStatsApiAnalyticsDashboardGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>> = ({ signal }) => getDashboardStatsApiAnalyticsDashboardGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardStatsApiAnalyticsDashboardGetQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>>
export type GetDashboardStatsApiAnalyticsDashboardGetQueryError = ErrorResponse


export function useGetDashboardStatsApiAnalyticsDashboardGet<TData = Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>,
          TError,
          Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardStatsApiAnalyticsDashboardGet<TData = Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>,
          TError,
          Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboardStatsApiAnalyticsDashboardGet<TData = Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Dashboard Stats
 */

export function useGetDashboardStatsApiAnalyticsDashboardGet<TData = Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboardStatsApiAnalyticsDashboardGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardStatsApiAnalyticsDashboardGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get comprehensive analytics for a group.
 * @summary Get Group Analytics
 */
export type getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse200 = {
  data: GroupAnalytics
  status: 200
}

export type getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponseSuccess = (getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse200) & {
  headers: Headers;
};
export type getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponseError = (getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse401 | getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse403 | getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse404 | getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse422 | getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse429) & {
  headers: Headers;
};

export type getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse = (getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponseSuccess | getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponseError)

export const getGetGroupAnalyticsApiAnalyticsGroupsGroupIdGetUrl = (groupId: number,
    params?: GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/analytics/groups/${groupId}?${stringifiedParams}` : `/api/analytics/groups/${groupId}`
}

export const getGroupAnalyticsApiAnalyticsGroupsGroupIdGet = async (groupId: number,
    params?: GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetParams, options?: RequestInit): Promise<getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse> => {
  
  return customInstance<getGroupAnalyticsApiAnalyticsGroupsGroupIdGetResponse>(getGetGroupAnalyticsApiAnalyticsGroupsGroupIdGetUrl(groupId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGroupAnalyticsApiAnalyticsGroupsGroupIdGetQueryKey = (groupId: number,
    params?: GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetParams,) => {
    return [
    `/api/analytics/groups/${groupId}`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetGroupAnalyticsApiAnalyticsGroupsGroupIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError = ErrorResponse>(groupId: number,
    params?: GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGroupAnalyticsApiAnalyticsGroupsGroupIdGetQueryKey(groupId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>> = ({ signal }) => getGroupAnalyticsApiAnalyticsGroupsGroupIdGet(groupId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(groupId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>>
export type GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetQueryError = ErrorResponse


export function useGetGroupAnalyticsApiAnalyticsGroupsGroupIdGet<TData = Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError = ErrorResponse>(
 groupId: number,
    params: undefined |  GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>,
          TError,
          Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupAnalyticsApiAnalyticsGroupsGroupIdGet<TData = Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError = ErrorResponse>(
 groupId: number,
    params?: GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>,
          TError,
          Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupAnalyticsApiAnalyticsGroupsGroupIdGet<TData = Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError = ErrorResponse>(
 groupId: number,
    params?: GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Group Analytics
 */

export function useGetGroupAnalyticsApiAnalyticsGroupsGroupIdGet<TData = Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError = ErrorResponse>(
 groupId: number,
    params?: GetGroupAnalyticsApiAnalyticsGroupsGroupIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupAnalyticsApiAnalyticsGroupsGroupIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGroupAnalyticsApiAnalyticsGroupsGroupIdGetQueryOptions(groupId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get comprehensive analytics for a student.
 * @summary Get Student Analytics
 */
export type getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse200 = {
  data: unknown
  status: 200
}

export type getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponseSuccess = (getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse200) & {
  headers: Headers;
};
export type getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponseError = (getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse401 | getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse403 | getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse404 | getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse422 | getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse429) & {
  headers: Headers;
};

export type getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse = (getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponseSuccess | getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponseError)

export const getGetStudentAnalyticsApiAnalyticsStudentsStudentIdGetUrl = (studentId: number,
    params?: GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/analytics/students/${studentId}?${stringifiedParams}` : `/api/analytics/students/${studentId}`
}

export const getStudentAnalyticsApiAnalyticsStudentsStudentIdGet = async (studentId: number,
    params?: GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetParams, options?: RequestInit): Promise<getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse> => {
  
  return customInstance<getStudentAnalyticsApiAnalyticsStudentsStudentIdGetResponse>(getGetStudentAnalyticsApiAnalyticsStudentsStudentIdGetUrl(studentId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStudentAnalyticsApiAnalyticsStudentsStudentIdGetQueryKey = (studentId: number,
    params?: GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetParams,) => {
    return [
    `/api/analytics/students/${studentId}`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetStudentAnalyticsApiAnalyticsStudentsStudentIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError = ErrorResponse>(studentId: number,
    params?: GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudentAnalyticsApiAnalyticsStudentsStudentIdGetQueryKey(studentId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>> = ({ signal }) => getStudentAnalyticsApiAnalyticsStudentsStudentIdGet(studentId,params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(studentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>>
export type GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetQueryError = ErrorResponse


export function useGetStudentAnalyticsApiAnalyticsStudentsStudentIdGet<TData = Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError = ErrorResponse>(
 studentId: number,
    params: undefined |  GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentAnalyticsApiAnalyticsStudentsStudentIdGet<TData = Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError = ErrorResponse>(
 studentId: number,
    params?: GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStudentAnalyticsApiAnalyticsStudentsStudentIdGet<TData = Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError = ErrorResponse>(
 studentId: number,
    params?: GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Student Analytics
 */

export function useGetStudentAnalyticsApiAnalyticsStudentsStudentIdGet<TData = Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError = ErrorResponse>(
 studentId: number,
    params?: GetStudentAnalyticsApiAnalyticsStudentsStudentIdGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudentAnalyticsApiAnalyticsStudentsStudentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStudentAnalyticsApiAnalyticsStudentsStudentIdGetQueryOptions(studentId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get attendance statistics grouped by date.
 * @summary Get Attendance By Date
 */
export type getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse200 = {
  data: unknown
  status: 200
}

export type getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getAttendanceByDateApiAnalyticsAttendanceByDateGetResponseSuccess = (getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse200) & {
  headers: Headers;
};
export type getAttendanceByDateApiAnalyticsAttendanceByDateGetResponseError = (getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse401 | getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse403 | getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse404 | getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse422 | getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse429) & {
  headers: Headers;
};

export type getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse = (getAttendanceByDateApiAnalyticsAttendanceByDateGetResponseSuccess | getAttendanceByDateApiAnalyticsAttendanceByDateGetResponseError)

export const getGetAttendanceByDateApiAnalyticsAttendanceByDateGetUrl = (params?: GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/analytics/attendance/by-date?${stringifiedParams}` : `/api/analytics/attendance/by-date`
}

export const getAttendanceByDateApiAnalyticsAttendanceByDateGet = async (params?: GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams, options?: RequestInit): Promise<getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse> => {
  
  return customInstance<getAttendanceByDateApiAnalyticsAttendanceByDateGetResponse>(getGetAttendanceByDateApiAnalyticsAttendanceByDateGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAttendanceByDateApiAnalyticsAttendanceByDateGetQueryKey = (params?: GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams,) => {
    return [
    `/api/analytics/attendance/by-date`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAttendanceByDateApiAnalyticsAttendanceByDateGetQueryOptions = <TData = Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError = ErrorResponse>(params?: GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAttendanceByDateApiAnalyticsAttendanceByDateGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>> = ({ signal }) => getAttendanceByDateApiAnalyticsAttendanceByDateGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAttendanceByDateApiAnalyticsAttendanceByDateGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>>
export type GetAttendanceByDateApiAnalyticsAttendanceByDateGetQueryError = ErrorResponse


export function useGetAttendanceByDateApiAnalyticsAttendanceByDateGet<TData = Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError = ErrorResponse>(
 params: undefined |  GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>,
          TError,
          Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttendanceByDateApiAnalyticsAttendanceByDateGet<TData = Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError = ErrorResponse>(
 params?: GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>,
          TError,
          Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttendanceByDateApiAnalyticsAttendanceByDateGet<TData = Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError = ErrorResponse>(
 params?: GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Attendance By Date
 */

export function useGetAttendanceByDateApiAnalyticsAttendanceByDateGet<TData = Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError = ErrorResponse>(
 params?: GetAttendanceByDateApiAnalyticsAttendanceByDateGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttendanceByDateApiAnalyticsAttendanceByDateGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAttendanceByDateApiAnalyticsAttendanceByDateGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get grade distribution statistics.
 * @summary Get Grades Distribution
 */
export type getGradesDistributionApiAnalyticsGradesDistributionGetResponse200 = {
  data: unknown
  status: 200
}

export type getGradesDistributionApiAnalyticsGradesDistributionGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getGradesDistributionApiAnalyticsGradesDistributionGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getGradesDistributionApiAnalyticsGradesDistributionGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getGradesDistributionApiAnalyticsGradesDistributionGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getGradesDistributionApiAnalyticsGradesDistributionGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getGradesDistributionApiAnalyticsGradesDistributionGetResponseSuccess = (getGradesDistributionApiAnalyticsGradesDistributionGetResponse200) & {
  headers: Headers;
};
export type getGradesDistributionApiAnalyticsGradesDistributionGetResponseError = (getGradesDistributionApiAnalyticsGradesDistributionGetResponse401 | getGradesDistributionApiAnalyticsGradesDistributionGetResponse403 | getGradesDistributionApiAnalyticsGradesDistributionGetResponse404 | getGradesDistributionApiAnalyticsGradesDistributionGetResponse422 | getGradesDistributionApiAnalyticsGradesDistributionGetResponse429) & {
  headers: Headers;
};

export type getGradesDistributionApiAnalyticsGradesDistributionGetResponse = (getGradesDistributionApiAnalyticsGradesDistributionGetResponseSuccess | getGradesDistributionApiAnalyticsGradesDistributionGetResponseError)

export const getGetGradesDistributionApiAnalyticsGradesDistributionGetUrl = (params?: GetGradesDistributionApiAnalyticsGradesDistributionGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/analytics/grades/distribution?${stringifiedParams}` : `/api/analytics/grades/distribution`
}

export const getGradesDistributionApiAnalyticsGradesDistributionGet = async (params?: GetGradesDistributionApiAnalyticsGradesDistributionGetParams, options?: RequestInit): Promise<getGradesDistributionApiAnalyticsGradesDistributionGetResponse> => {
  
  return customInstance<getGradesDistributionApiAnalyticsGradesDistributionGetResponse>(getGetGradesDistributionApiAnalyticsGradesDistributionGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGradesDistributionApiAnalyticsGradesDistributionGetQueryKey = (params?: GetGradesDistributionApiAnalyticsGradesDistributionGetParams,) => {
    return [
    `/api/analytics/grades/distribution`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetGradesDistributionApiAnalyticsGradesDistributionGetQueryOptions = <TData = Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError = ErrorResponse>(params?: GetGradesDistributionApiAnalyticsGradesDistributionGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGradesDistributionApiAnalyticsGradesDistributionGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>> = ({ signal }) => getGradesDistributionApiAnalyticsGradesDistributionGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGradesDistributionApiAnalyticsGradesDistributionGetQueryResult = NonNullable<Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>>
export type GetGradesDistributionApiAnalyticsGradesDistributionGetQueryError = ErrorResponse


export function useGetGradesDistributionApiAnalyticsGradesDistributionGet<TData = Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError = ErrorResponse>(
 params: undefined |  GetGradesDistributionApiAnalyticsGradesDistributionGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>,
          TError,
          Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGradesDistributionApiAnalyticsGradesDistributionGet<TData = Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError = ErrorResponse>(
 params?: GetGradesDistributionApiAnalyticsGradesDistributionGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>,
          TError,
          Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGradesDistributionApiAnalyticsGradesDistributionGet<TData = Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError = ErrorResponse>(
 params?: GetGradesDistributionApiAnalyticsGradesDistributionGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Grades Distribution
 */

export function useGetGradesDistributionApiAnalyticsGradesDistributionGet<TData = Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError = ErrorResponse>(
 params?: GetGradesDistributionApiAnalyticsGradesDistributionGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGradesDistributionApiAnalyticsGradesDistributionGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGradesDistributionApiAnalyticsGradesDistributionGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




