"""add_group_id_to_assignments

Revision ID: 533c62c54052
Revises: 790c6240dc6c
Create Date: 2026-01-07 23:18:26.638038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533c62c54052'
down_revision: Union[str, None] = '790c6240dc6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_assignments_group_id', 'assignments', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_assignments_group_id', 'assignments', type_='foreignkey')
    op.drop_column('assignments', 'group_id')
    # ### end Alembic commands ###
