"""add_attachments_table

Revision ID: ecee06ebf27e
Revises: 533c62c54052
Create Date: 2026-01-27 23:50:19.307313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecee06ebf27e'
down_revision: Union[str, None] = '533c62c54052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('SCHEDULE', 'ASSIGNMENT', name='attachmententity'), nullable=False, comment='Type of entity this attachment belongs to'),
    sa.Column('entity_id', sa.Integer(), nullable=False, comment='ID of the entity this attachment belongs to'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original filename uploaded by user'),
    sa.Column('storage_key', sa.String(length=500), nullable=False, comment='Unique key/path in storage system'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME type of the file'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='File size in bytes'),
    sa.Column('checksum', sa.String(length=32), nullable=False, comment='MD5 checksum for integrity verification'),
    sa.Column('storage_backend', sa.String(length=20), nullable=False, comment="Storage backend: 'local' or 's3'"),
    sa.Column('attachment_type', sa.Enum('DOCUMENT', 'IMAGE', 'VIDEO', 'AUDIO', 'ARCHIVE', 'OTHER', name='attachmenttype'), nullable=False, comment='Type/category of attachment'),
    sa.Column('title', sa.String(length=255), nullable=True, comment='Display title (if different from filename)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description of the attachment'),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False, comment='User who uploaded the file'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_entity_id'), 'attachments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachments_entity_type'), 'attachments', ['entity_type'], unique=False)
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.create_index(op.f('ix_attachments_storage_key'), 'attachments', ['storage_key'], unique=True)
    # NOTE: Removed auto-detected drop_table('books') - not related to attachments
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_storage_key'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_entity_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
