/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * 
## Электронный журнал для Военной кафедры КазУТБ

### Возможности API:
- 🔐 **Аутентификация** - JWT токены, регистрация, авторизация
- 👥 **Управление пользователями** - курсанты, преподаватели, администраторы
- 📚 **Учебный процесс** - расписание, посещаемость, оценки
- 📎 **Файлы** - загрузка материалов к занятиям
- 📊 **Аналитика** - статистика успеваемости

### Аутентификация:
Все защищённые эндпоинты требуют JWT токен в заголовке:
```
Authorization: Bearer <token>
```

### Формат ошибок:
Все ошибки возвращаются в стандартном формате:
```json
{
    "error": {
        "code": "ERROR_CODE",
        "message": "Описание ошибки",
        "details": [...]
    }
}
```
    
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorResponse,
  GroupCreate,
  GroupRead,
  GroupUpdate,
  ListGroupsApiGroupsGetParams,
  StudentRead
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Create a new student group (teachers and admins only).
 * @summary Create Group
 */
export type createGroupApiGroupsPostResponse201 = {
  data: GroupRead
  status: 201
}

export type createGroupApiGroupsPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type createGroupApiGroupsPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type createGroupApiGroupsPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type createGroupApiGroupsPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type createGroupApiGroupsPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type createGroupApiGroupsPostResponseSuccess = (createGroupApiGroupsPostResponse201) & {
  headers: Headers;
};
export type createGroupApiGroupsPostResponseError = (createGroupApiGroupsPostResponse401 | createGroupApiGroupsPostResponse403 | createGroupApiGroupsPostResponse404 | createGroupApiGroupsPostResponse422 | createGroupApiGroupsPostResponse429) & {
  headers: Headers;
};

export type createGroupApiGroupsPostResponse = (createGroupApiGroupsPostResponseSuccess | createGroupApiGroupsPostResponseError)

export const getCreateGroupApiGroupsPostUrl = () => {


  

  return `/api/groups/`
}

export const createGroupApiGroupsPost = async (groupCreate: GroupCreate, options?: RequestInit): Promise<createGroupApiGroupsPostResponse> => {
  
  return customInstance<createGroupApiGroupsPostResponse>(getCreateGroupApiGroupsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      groupCreate,)
  }
);}




export const getCreateGroupApiGroupsPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGroupApiGroupsPost>>, TError,{data: GroupCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createGroupApiGroupsPost>>, TError,{data: GroupCreate}, TContext> => {

const mutationKey = ['createGroupApiGroupsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createGroupApiGroupsPost>>, {data: GroupCreate}> = (props) => {
          const {data} = props ?? {};

          return  createGroupApiGroupsPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateGroupApiGroupsPostMutationResult = NonNullable<Awaited<ReturnType<typeof createGroupApiGroupsPost>>>
    export type CreateGroupApiGroupsPostMutationBody = GroupCreate
    export type CreateGroupApiGroupsPostMutationError = ErrorResponse

    /**
 * @summary Create Group
 */
export const useCreateGroupApiGroupsPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createGroupApiGroupsPost>>, TError,{data: GroupCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createGroupApiGroupsPost>>,
        TError,
        {data: GroupCreate},
        TContext
      > => {
      return useMutation(getCreateGroupApiGroupsPostMutationOptions(options), queryClient);
    }
    /**
 * List all groups (public endpoint for registration).
 * @summary List Groups
 */
export type listGroupsApiGroupsGetResponse200 = {
  data: GroupRead[]
  status: 200
}

export type listGroupsApiGroupsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listGroupsApiGroupsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listGroupsApiGroupsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listGroupsApiGroupsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listGroupsApiGroupsGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listGroupsApiGroupsGetResponseSuccess = (listGroupsApiGroupsGetResponse200) & {
  headers: Headers;
};
export type listGroupsApiGroupsGetResponseError = (listGroupsApiGroupsGetResponse401 | listGroupsApiGroupsGetResponse403 | listGroupsApiGroupsGetResponse404 | listGroupsApiGroupsGetResponse422 | listGroupsApiGroupsGetResponse429) & {
  headers: Headers;
};

export type listGroupsApiGroupsGetResponse = (listGroupsApiGroupsGetResponseSuccess | listGroupsApiGroupsGetResponseError)

export const getListGroupsApiGroupsGetUrl = (params?: ListGroupsApiGroupsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/groups/?${stringifiedParams}` : `/api/groups/`
}

export const listGroupsApiGroupsGet = async (params?: ListGroupsApiGroupsGetParams, options?: RequestInit): Promise<listGroupsApiGroupsGetResponse> => {
  
  return customInstance<listGroupsApiGroupsGetResponse>(getListGroupsApiGroupsGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListGroupsApiGroupsGetQueryKey = (params?: ListGroupsApiGroupsGetParams,) => {
    return [
    `/api/groups/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListGroupsApiGroupsGetQueryOptions = <TData = Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError = ErrorResponse>(params?: ListGroupsApiGroupsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGroupsApiGroupsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroupsApiGroupsGet>>> = ({ signal }) => listGroupsApiGroupsGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGroupsApiGroupsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listGroupsApiGroupsGet>>>
export type ListGroupsApiGroupsGetQueryError = ErrorResponse


export function useListGroupsApiGroupsGet<TData = Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError = ErrorResponse>(
 params: undefined |  ListGroupsApiGroupsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroupsApiGroupsGet>>,
          TError,
          Awaited<ReturnType<typeof listGroupsApiGroupsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroupsApiGroupsGet<TData = Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError = ErrorResponse>(
 params?: ListGroupsApiGroupsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroupsApiGroupsGet>>,
          TError,
          Awaited<ReturnType<typeof listGroupsApiGroupsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroupsApiGroupsGet<TData = Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError = ErrorResponse>(
 params?: ListGroupsApiGroupsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Groups
 */

export function useListGroupsApiGroupsGet<TData = Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError = ErrorResponse>(
 params?: ListGroupsApiGroupsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroupsApiGroupsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGroupsApiGroupsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get group by ID.
 * @summary Get Group
 */
export type getGroupApiGroupsGroupIdGetResponse200 = {
  data: GroupRead
  status: 200
}

export type getGroupApiGroupsGroupIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getGroupApiGroupsGroupIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getGroupApiGroupsGroupIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getGroupApiGroupsGroupIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getGroupApiGroupsGroupIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getGroupApiGroupsGroupIdGetResponseSuccess = (getGroupApiGroupsGroupIdGetResponse200) & {
  headers: Headers;
};
export type getGroupApiGroupsGroupIdGetResponseError = (getGroupApiGroupsGroupIdGetResponse401 | getGroupApiGroupsGroupIdGetResponse403 | getGroupApiGroupsGroupIdGetResponse404 | getGroupApiGroupsGroupIdGetResponse422 | getGroupApiGroupsGroupIdGetResponse429) & {
  headers: Headers;
};

export type getGroupApiGroupsGroupIdGetResponse = (getGroupApiGroupsGroupIdGetResponseSuccess | getGroupApiGroupsGroupIdGetResponseError)

export const getGetGroupApiGroupsGroupIdGetUrl = (groupId: number,) => {


  

  return `/api/groups/${groupId}`
}

export const getGroupApiGroupsGroupIdGet = async (groupId: number, options?: RequestInit): Promise<getGroupApiGroupsGroupIdGetResponse> => {
  
  return customInstance<getGroupApiGroupsGroupIdGetResponse>(getGetGroupApiGroupsGroupIdGetUrl(groupId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGroupApiGroupsGroupIdGetQueryKey = (groupId: number,) => {
    return [
    `/api/groups/${groupId}`
    ] as const;
    }

    
export const getGetGroupApiGroupsGroupIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError = ErrorResponse>(groupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGroupApiGroupsGroupIdGetQueryKey(groupId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>> = ({ signal }) => getGroupApiGroupsGroupIdGet(groupId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(groupId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGroupApiGroupsGroupIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>>
export type GetGroupApiGroupsGroupIdGetQueryError = ErrorResponse


export function useGetGroupApiGroupsGroupIdGet<TData = Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError = ErrorResponse>(
 groupId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>,
          TError,
          Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupApiGroupsGroupIdGet<TData = Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError = ErrorResponse>(
 groupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>,
          TError,
          Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupApiGroupsGroupIdGet<TData = Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError = ErrorResponse>(
 groupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Group
 */

export function useGetGroupApiGroupsGroupIdGet<TData = Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError = ErrorResponse>(
 groupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupApiGroupsGroupIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGroupApiGroupsGroupIdGetQueryOptions(groupId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update group information (teachers and admins only).
 * @summary Update Group
 */
export type updateGroupApiGroupsGroupIdPatchResponse200 = {
  data: GroupRead
  status: 200
}

export type updateGroupApiGroupsGroupIdPatchResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateGroupApiGroupsGroupIdPatchResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateGroupApiGroupsGroupIdPatchResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateGroupApiGroupsGroupIdPatchResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateGroupApiGroupsGroupIdPatchResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type updateGroupApiGroupsGroupIdPatchResponseSuccess = (updateGroupApiGroupsGroupIdPatchResponse200) & {
  headers: Headers;
};
export type updateGroupApiGroupsGroupIdPatchResponseError = (updateGroupApiGroupsGroupIdPatchResponse401 | updateGroupApiGroupsGroupIdPatchResponse403 | updateGroupApiGroupsGroupIdPatchResponse404 | updateGroupApiGroupsGroupIdPatchResponse422 | updateGroupApiGroupsGroupIdPatchResponse429) & {
  headers: Headers;
};

export type updateGroupApiGroupsGroupIdPatchResponse = (updateGroupApiGroupsGroupIdPatchResponseSuccess | updateGroupApiGroupsGroupIdPatchResponseError)

export const getUpdateGroupApiGroupsGroupIdPatchUrl = (groupId: number,) => {


  

  return `/api/groups/${groupId}`
}

export const updateGroupApiGroupsGroupIdPatch = async (groupId: number,
    groupUpdate: GroupUpdate, options?: RequestInit): Promise<updateGroupApiGroupsGroupIdPatchResponse> => {
  
  return customInstance<updateGroupApiGroupsGroupIdPatchResponse>(getUpdateGroupApiGroupsGroupIdPatchUrl(groupId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      groupUpdate,)
  }
);}




export const getUpdateGroupApiGroupsGroupIdPatchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroupApiGroupsGroupIdPatch>>, TError,{groupId: number;data: GroupUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateGroupApiGroupsGroupIdPatch>>, TError,{groupId: number;data: GroupUpdate}, TContext> => {

const mutationKey = ['updateGroupApiGroupsGroupIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateGroupApiGroupsGroupIdPatch>>, {groupId: number;data: GroupUpdate}> = (props) => {
          const {groupId,data} = props ?? {};

          return  updateGroupApiGroupsGroupIdPatch(groupId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateGroupApiGroupsGroupIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateGroupApiGroupsGroupIdPatch>>>
    export type UpdateGroupApiGroupsGroupIdPatchMutationBody = GroupUpdate
    export type UpdateGroupApiGroupsGroupIdPatchMutationError = ErrorResponse

    /**
 * @summary Update Group
 */
export const useUpdateGroupApiGroupsGroupIdPatch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateGroupApiGroupsGroupIdPatch>>, TError,{groupId: number;data: GroupUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateGroupApiGroupsGroupIdPatch>>,
        TError,
        {groupId: number;data: GroupUpdate},
        TContext
      > => {
      return useMutation(getUpdateGroupApiGroupsGroupIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete a group (teachers and admins only).
 * @summary Delete Group
 */
export type deleteGroupApiGroupsGroupIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteGroupApiGroupsGroupIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteGroupApiGroupsGroupIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteGroupApiGroupsGroupIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteGroupApiGroupsGroupIdDeleteResponse422 = {
  data: ErrorResponse
  status: 422
}

export type deleteGroupApiGroupsGroupIdDeleteResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type deleteGroupApiGroupsGroupIdDeleteResponseSuccess = (deleteGroupApiGroupsGroupIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteGroupApiGroupsGroupIdDeleteResponseError = (deleteGroupApiGroupsGroupIdDeleteResponse401 | deleteGroupApiGroupsGroupIdDeleteResponse403 | deleteGroupApiGroupsGroupIdDeleteResponse404 | deleteGroupApiGroupsGroupIdDeleteResponse422 | deleteGroupApiGroupsGroupIdDeleteResponse429) & {
  headers: Headers;
};

export type deleteGroupApiGroupsGroupIdDeleteResponse = (deleteGroupApiGroupsGroupIdDeleteResponseSuccess | deleteGroupApiGroupsGroupIdDeleteResponseError)

export const getDeleteGroupApiGroupsGroupIdDeleteUrl = (groupId: number,) => {


  

  return `/api/groups/${groupId}`
}

export const deleteGroupApiGroupsGroupIdDelete = async (groupId: number, options?: RequestInit): Promise<deleteGroupApiGroupsGroupIdDeleteResponse> => {
  
  return customInstance<deleteGroupApiGroupsGroupIdDeleteResponse>(getDeleteGroupApiGroupsGroupIdDeleteUrl(groupId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteGroupApiGroupsGroupIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGroupApiGroupsGroupIdDelete>>, TError,{groupId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteGroupApiGroupsGroupIdDelete>>, TError,{groupId: number}, TContext> => {

const mutationKey = ['deleteGroupApiGroupsGroupIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteGroupApiGroupsGroupIdDelete>>, {groupId: number}> = (props) => {
          const {groupId} = props ?? {};

          return  deleteGroupApiGroupsGroupIdDelete(groupId,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteGroupApiGroupsGroupIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteGroupApiGroupsGroupIdDelete>>>
    
    export type DeleteGroupApiGroupsGroupIdDeleteMutationError = ErrorResponse

    /**
 * @summary Delete Group
 */
export const useDeleteGroupApiGroupsGroupIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteGroupApiGroupsGroupIdDelete>>, TError,{groupId: number}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteGroupApiGroupsGroupIdDelete>>,
        TError,
        {groupId: number},
        TContext
      > => {
      return useMutation(getDeleteGroupApiGroupsGroupIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Get all students in a group.
 * @summary Get Group Students
 */
export type getGroupStudentsApiGroupsGroupIdStudentsGetResponse200 = {
  data: StudentRead[]
  status: 200
}

export type getGroupStudentsApiGroupsGroupIdStudentsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getGroupStudentsApiGroupsGroupIdStudentsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getGroupStudentsApiGroupsGroupIdStudentsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getGroupStudentsApiGroupsGroupIdStudentsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getGroupStudentsApiGroupsGroupIdStudentsGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getGroupStudentsApiGroupsGroupIdStudentsGetResponseSuccess = (getGroupStudentsApiGroupsGroupIdStudentsGetResponse200) & {
  headers: Headers;
};
export type getGroupStudentsApiGroupsGroupIdStudentsGetResponseError = (getGroupStudentsApiGroupsGroupIdStudentsGetResponse401 | getGroupStudentsApiGroupsGroupIdStudentsGetResponse403 | getGroupStudentsApiGroupsGroupIdStudentsGetResponse404 | getGroupStudentsApiGroupsGroupIdStudentsGetResponse422 | getGroupStudentsApiGroupsGroupIdStudentsGetResponse429) & {
  headers: Headers;
};

export type getGroupStudentsApiGroupsGroupIdStudentsGetResponse = (getGroupStudentsApiGroupsGroupIdStudentsGetResponseSuccess | getGroupStudentsApiGroupsGroupIdStudentsGetResponseError)

export const getGetGroupStudentsApiGroupsGroupIdStudentsGetUrl = (groupId: number,) => {


  

  return `/api/groups/${groupId}/students`
}

export const getGroupStudentsApiGroupsGroupIdStudentsGet = async (groupId: number, options?: RequestInit): Promise<getGroupStudentsApiGroupsGroupIdStudentsGetResponse> => {
  
  return customInstance<getGroupStudentsApiGroupsGroupIdStudentsGetResponse>(getGetGroupStudentsApiGroupsGroupIdStudentsGetUrl(groupId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetGroupStudentsApiGroupsGroupIdStudentsGetQueryKey = (groupId: number,) => {
    return [
    `/api/groups/${groupId}/students`
    ] as const;
    }

    
export const getGetGroupStudentsApiGroupsGroupIdStudentsGetQueryOptions = <TData = Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError = ErrorResponse>(groupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGroupStudentsApiGroupsGroupIdStudentsGetQueryKey(groupId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>> = ({ signal }) => getGroupStudentsApiGroupsGroupIdStudentsGet(groupId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(groupId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGroupStudentsApiGroupsGroupIdStudentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>>
export type GetGroupStudentsApiGroupsGroupIdStudentsGetQueryError = ErrorResponse


export function useGetGroupStudentsApiGroupsGroupIdStudentsGet<TData = Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError = ErrorResponse>(
 groupId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>,
          TError,
          Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupStudentsApiGroupsGroupIdStudentsGet<TData = Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError = ErrorResponse>(
 groupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>,
          TError,
          Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGroupStudentsApiGroupsGroupIdStudentsGet<TData = Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError = ErrorResponse>(
 groupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Group Students
 */

export function useGetGroupStudentsApiGroupsGroupIdStudentsGet<TData = Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError = ErrorResponse>(
 groupId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGroupStudentsApiGroupsGroupIdStudentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGroupStudentsApiGroupsGroupIdStudentsGetQueryOptions(groupId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




