"""add description to topographic symbols

Revision ID: e1fa3f829298
Revises: fa99930ceaa7
Create Date: 2026-02-14 15:28:36.584489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fa3f829298'
down_revision: Union[str, None] = 'fa99930ceaa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topographic_symbols', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topographic_symbols', 'description')
    # ### end Alembic commands ###
