/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChangePasswordApiAuthChangePasswordPostParams,
  ErrorResponse,
  TokenResponse,
  UserCreate,
  UserLogin,
  UserRead
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Register a new user account.
Returns JWT token upon successful registration.
 * @summary Register
 */
export type registerApiAuthRegisterPostResponse201 = {
  data: TokenResponse
  status: 201
}

export type registerApiAuthRegisterPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type registerApiAuthRegisterPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type registerApiAuthRegisterPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type registerApiAuthRegisterPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type registerApiAuthRegisterPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type registerApiAuthRegisterPostResponseSuccess = (registerApiAuthRegisterPostResponse201) & {
  headers: Headers;
};
export type registerApiAuthRegisterPostResponseError = (registerApiAuthRegisterPostResponse401 | registerApiAuthRegisterPostResponse403 | registerApiAuthRegisterPostResponse404 | registerApiAuthRegisterPostResponse422 | registerApiAuthRegisterPostResponse429) & {
  headers: Headers;
};

export type registerApiAuthRegisterPostResponse = (registerApiAuthRegisterPostResponseSuccess | registerApiAuthRegisterPostResponseError)

export const getRegisterApiAuthRegisterPostUrl = () => {


  

  return `/api/auth/register`
}

export const registerApiAuthRegisterPost = async (userCreate: UserCreate, options?: RequestInit): Promise<registerApiAuthRegisterPostResponse> => {
  
  return customInstance<registerApiAuthRegisterPostResponse>(getRegisterApiAuthRegisterPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userCreate,)
  }
);}




export const getRegisterApiAuthRegisterPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>, TError,{data: UserCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>, TError,{data: UserCreate}, TContext> => {

const mutationKey = ['registerApiAuthRegisterPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>, {data: UserCreate}> = (props) => {
          const {data} = props ?? {};

          return  registerApiAuthRegisterPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterApiAuthRegisterPostMutationResult = NonNullable<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>>
    export type RegisterApiAuthRegisterPostMutationBody = UserCreate
    export type RegisterApiAuthRegisterPostMutationError = ErrorResponse

    /**
 * @summary Register
 */
export const useRegisterApiAuthRegisterPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerApiAuthRegisterPost>>, TError,{data: UserCreate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerApiAuthRegisterPost>>,
        TError,
        {data: UserCreate},
        TContext
      > => {
      return useMutation(getRegisterApiAuthRegisterPostMutationOptions(options), queryClient);
    }
    /**
 * Authenticate user and return JWT token.
 * @summary Login
 */
export type loginApiAuthLoginPostResponse200 = {
  data: TokenResponse
  status: 200
}

export type loginApiAuthLoginPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type loginApiAuthLoginPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type loginApiAuthLoginPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type loginApiAuthLoginPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type loginApiAuthLoginPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type loginApiAuthLoginPostResponseSuccess = (loginApiAuthLoginPostResponse200) & {
  headers: Headers;
};
export type loginApiAuthLoginPostResponseError = (loginApiAuthLoginPostResponse401 | loginApiAuthLoginPostResponse403 | loginApiAuthLoginPostResponse404 | loginApiAuthLoginPostResponse422 | loginApiAuthLoginPostResponse429) & {
  headers: Headers;
};

export type loginApiAuthLoginPostResponse = (loginApiAuthLoginPostResponseSuccess | loginApiAuthLoginPostResponseError)

export const getLoginApiAuthLoginPostUrl = () => {


  

  return `/api/auth/login`
}

export const loginApiAuthLoginPost = async (userLogin: UserLogin, options?: RequestInit): Promise<loginApiAuthLoginPostResponse> => {
  
  return customInstance<loginApiAuthLoginPostResponse>(getLoginApiAuthLoginPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userLogin,)
  }
);}




export const getLoginApiAuthLoginPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: UserLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: UserLogin}, TContext> => {

const mutationKey = ['loginApiAuthLoginPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, {data: UserLogin}> = (props) => {
          const {data} = props ?? {};

          return  loginApiAuthLoginPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginApiAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginApiAuthLoginPost>>>
    export type LoginApiAuthLoginPostMutationBody = UserLogin
    export type LoginApiAuthLoginPostMutationError = ErrorResponse

    /**
 * @summary Login
 */
export const useLoginApiAuthLoginPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginApiAuthLoginPost>>, TError,{data: UserLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginApiAuthLoginPost>>,
        TError,
        {data: UserLogin},
        TContext
      > => {
      return useMutation(getLoginApiAuthLoginPostMutationOptions(options), queryClient);
    }
    /**
 * Get current authenticated user information.
 * @summary Get Current User Info
 */
export type getCurrentUserInfoApiAuthMeGetResponse200 = {
  data: UserRead
  status: 200
}

export type getCurrentUserInfoApiAuthMeGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getCurrentUserInfoApiAuthMeGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getCurrentUserInfoApiAuthMeGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getCurrentUserInfoApiAuthMeGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getCurrentUserInfoApiAuthMeGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getCurrentUserInfoApiAuthMeGetResponseSuccess = (getCurrentUserInfoApiAuthMeGetResponse200) & {
  headers: Headers;
};
export type getCurrentUserInfoApiAuthMeGetResponseError = (getCurrentUserInfoApiAuthMeGetResponse401 | getCurrentUserInfoApiAuthMeGetResponse403 | getCurrentUserInfoApiAuthMeGetResponse404 | getCurrentUserInfoApiAuthMeGetResponse422 | getCurrentUserInfoApiAuthMeGetResponse429) & {
  headers: Headers;
};

export type getCurrentUserInfoApiAuthMeGetResponse = (getCurrentUserInfoApiAuthMeGetResponseSuccess | getCurrentUserInfoApiAuthMeGetResponseError)

export const getGetCurrentUserInfoApiAuthMeGetUrl = () => {


  

  return `/api/auth/me`
}

export const getCurrentUserInfoApiAuthMeGet = async ( options?: RequestInit): Promise<getCurrentUserInfoApiAuthMeGetResponse> => {
  
  return customInstance<getCurrentUserInfoApiAuthMeGetResponse>(getGetCurrentUserInfoApiAuthMeGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCurrentUserInfoApiAuthMeGetQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }

    
export const getGetCurrentUserInfoApiAuthMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserInfoApiAuthMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>> = ({ signal }) => getCurrentUserInfoApiAuthMeGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserInfoApiAuthMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>>
export type GetCurrentUserInfoApiAuthMeGetQueryError = ErrorResponse


export function useGetCurrentUserInfoApiAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserInfoApiAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserInfoApiAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Current User Info
 */

export function useGetCurrentUserInfoApiAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserInfoApiAuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserInfoApiAuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Refresh access token for authenticated user.
Returns a new token with extended expiration time.
 * @summary Refresh Token
 */
export type refreshTokenApiAuthRefreshTokenPostResponse200 = {
  data: TokenResponse
  status: 200
}

export type refreshTokenApiAuthRefreshTokenPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type refreshTokenApiAuthRefreshTokenPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type refreshTokenApiAuthRefreshTokenPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type refreshTokenApiAuthRefreshTokenPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type refreshTokenApiAuthRefreshTokenPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type refreshTokenApiAuthRefreshTokenPostResponseSuccess = (refreshTokenApiAuthRefreshTokenPostResponse200) & {
  headers: Headers;
};
export type refreshTokenApiAuthRefreshTokenPostResponseError = (refreshTokenApiAuthRefreshTokenPostResponse401 | refreshTokenApiAuthRefreshTokenPostResponse403 | refreshTokenApiAuthRefreshTokenPostResponse404 | refreshTokenApiAuthRefreshTokenPostResponse422 | refreshTokenApiAuthRefreshTokenPostResponse429) & {
  headers: Headers;
};

export type refreshTokenApiAuthRefreshTokenPostResponse = (refreshTokenApiAuthRefreshTokenPostResponseSuccess | refreshTokenApiAuthRefreshTokenPostResponseError)

export const getRefreshTokenApiAuthRefreshTokenPostUrl = () => {


  

  return `/api/auth/refresh-token`
}

export const refreshTokenApiAuthRefreshTokenPost = async ( options?: RequestInit): Promise<refreshTokenApiAuthRefreshTokenPostResponse> => {
  
  return customInstance<refreshTokenApiAuthRefreshTokenPostResponse>(getRefreshTokenApiAuthRefreshTokenPostUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getRefreshTokenApiAuthRefreshTokenPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshTokenApiAuthRefreshTokenPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refreshTokenApiAuthRefreshTokenPost>>, TError,void, TContext> => {

const mutationKey = ['refreshTokenApiAuthRefreshTokenPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshTokenApiAuthRefreshTokenPost>>, void> = () => {
          

          return  refreshTokenApiAuthRefreshTokenPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenApiAuthRefreshTokenPostMutationResult = NonNullable<Awaited<ReturnType<typeof refreshTokenApiAuthRefreshTokenPost>>>
    
    export type RefreshTokenApiAuthRefreshTokenPostMutationError = ErrorResponse

    /**
 * @summary Refresh Token
 */
export const useRefreshTokenApiAuthRefreshTokenPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshTokenApiAuthRefreshTokenPost>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshTokenApiAuthRefreshTokenPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRefreshTokenApiAuthRefreshTokenPostMutationOptions(options), queryClient);
    }
    /**
 * Change user password.
 * @summary Change Password
 */
export type changePasswordApiAuthChangePasswordPostResponse200 = {
  data: unknown
  status: 200
}

export type changePasswordApiAuthChangePasswordPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type changePasswordApiAuthChangePasswordPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type changePasswordApiAuthChangePasswordPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type changePasswordApiAuthChangePasswordPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type changePasswordApiAuthChangePasswordPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type changePasswordApiAuthChangePasswordPostResponseSuccess = (changePasswordApiAuthChangePasswordPostResponse200) & {
  headers: Headers;
};
export type changePasswordApiAuthChangePasswordPostResponseError = (changePasswordApiAuthChangePasswordPostResponse401 | changePasswordApiAuthChangePasswordPostResponse403 | changePasswordApiAuthChangePasswordPostResponse404 | changePasswordApiAuthChangePasswordPostResponse422 | changePasswordApiAuthChangePasswordPostResponse429) & {
  headers: Headers;
};

export type changePasswordApiAuthChangePasswordPostResponse = (changePasswordApiAuthChangePasswordPostResponseSuccess | changePasswordApiAuthChangePasswordPostResponseError)

export const getChangePasswordApiAuthChangePasswordPostUrl = (params: ChangePasswordApiAuthChangePasswordPostParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/change-password?${stringifiedParams}` : `/api/auth/change-password`
}

export const changePasswordApiAuthChangePasswordPost = async (params: ChangePasswordApiAuthChangePasswordPostParams, options?: RequestInit): Promise<changePasswordApiAuthChangePasswordPostResponse> => {
  
  return customInstance<changePasswordApiAuthChangePasswordPostResponse>(getChangePasswordApiAuthChangePasswordPostUrl(params),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getChangePasswordApiAuthChangePasswordPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePasswordApiAuthChangePasswordPost>>, TError,{params: ChangePasswordApiAuthChangePasswordPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changePasswordApiAuthChangePasswordPost>>, TError,{params: ChangePasswordApiAuthChangePasswordPostParams}, TContext> => {

const mutationKey = ['changePasswordApiAuthChangePasswordPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePasswordApiAuthChangePasswordPost>>, {params: ChangePasswordApiAuthChangePasswordPostParams}> = (props) => {
          const {params} = props ?? {};

          return  changePasswordApiAuthChangePasswordPost(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordApiAuthChangePasswordPostMutationResult = NonNullable<Awaited<ReturnType<typeof changePasswordApiAuthChangePasswordPost>>>
    
    export type ChangePasswordApiAuthChangePasswordPostMutationError = ErrorResponse

    /**
 * @summary Change Password
 */
export const useChangePasswordApiAuthChangePasswordPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePasswordApiAuthChangePasswordPost>>, TError,{params: ChangePasswordApiAuthChangePasswordPostParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePasswordApiAuthChangePasswordPost>>,
        TError,
        {params: ChangePasswordApiAuthChangePasswordPostParams},
        TContext
      > => {
      return useMutation(getChangePasswordApiAuthChangePasswordPostMutationOptions(options), queryClient);
    }
    