/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Military Journal API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AttachmentEntity,
  AttachmentListResponse,
  AttachmentRead,
  AttachmentUpdate,
  AttachmentUploadResponse,
  BodyUploadAttachmentApiAttachmentsUploadPost,
  DeleteAttachmentApiAttachmentsAttachmentIdDeleteParams,
  ErrorResponse,
  ListAttachmentsApiAttachmentsGetParams,
  StorageInfoResponse
} from '.././model';

import { customInstance } from '../../custom-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get information about the current storage configuration.
Useful for frontend to show upload limits.
 * @summary Get Storage Info
 */
export type getStorageInfoApiAttachmentsStorageInfoGetResponse200 = {
  data: StorageInfoResponse
  status: 200
}

export type getStorageInfoApiAttachmentsStorageInfoGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getStorageInfoApiAttachmentsStorageInfoGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getStorageInfoApiAttachmentsStorageInfoGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getStorageInfoApiAttachmentsStorageInfoGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getStorageInfoApiAttachmentsStorageInfoGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getStorageInfoApiAttachmentsStorageInfoGetResponseSuccess = (getStorageInfoApiAttachmentsStorageInfoGetResponse200) & {
  headers: Headers;
};
export type getStorageInfoApiAttachmentsStorageInfoGetResponseError = (getStorageInfoApiAttachmentsStorageInfoGetResponse401 | getStorageInfoApiAttachmentsStorageInfoGetResponse403 | getStorageInfoApiAttachmentsStorageInfoGetResponse404 | getStorageInfoApiAttachmentsStorageInfoGetResponse422 | getStorageInfoApiAttachmentsStorageInfoGetResponse429) & {
  headers: Headers;
};

export type getStorageInfoApiAttachmentsStorageInfoGetResponse = (getStorageInfoApiAttachmentsStorageInfoGetResponseSuccess | getStorageInfoApiAttachmentsStorageInfoGetResponseError)

export const getGetStorageInfoApiAttachmentsStorageInfoGetUrl = () => {


  

  return `/api/attachments/storage-info`
}

export const getStorageInfoApiAttachmentsStorageInfoGet = async ( options?: RequestInit): Promise<getStorageInfoApiAttachmentsStorageInfoGetResponse> => {
  
  return customInstance<getStorageInfoApiAttachmentsStorageInfoGetResponse>(getGetStorageInfoApiAttachmentsStorageInfoGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetStorageInfoApiAttachmentsStorageInfoGetQueryKey = () => {
    return [
    `/api/attachments/storage-info`
    ] as const;
    }

    
export const getGetStorageInfoApiAttachmentsStorageInfoGetQueryOptions = <TData = Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError = ErrorResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStorageInfoApiAttachmentsStorageInfoGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>> = ({ signal }) => getStorageInfoApiAttachmentsStorageInfoGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStorageInfoApiAttachmentsStorageInfoGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>>
export type GetStorageInfoApiAttachmentsStorageInfoGetQueryError = ErrorResponse


export function useGetStorageInfoApiAttachmentsStorageInfoGet<TData = Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError = ErrorResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>,
          TError,
          Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStorageInfoApiAttachmentsStorageInfoGet<TData = Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>,
          TError,
          Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStorageInfoApiAttachmentsStorageInfoGet<TData = Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Storage Info
 */

export function useGetStorageInfoApiAttachmentsStorageInfoGet<TData = Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError = ErrorResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStorageInfoApiAttachmentsStorageInfoGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStorageInfoApiAttachmentsStorageInfoGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Upload a file attachment to a lesson (schedule) or assignment.

- **file**: The file to upload
- **entity_type**: Type of entity to attach to (schedule, assignment)
- **entity_id**: ID of the entity
- **title**: Optional display title (defaults to filename)
- **description**: Optional description

Returns the created attachment with download URL.
 * @summary Upload Attachment
 */
export type uploadAttachmentApiAttachmentsUploadPostResponse201 = {
  data: AttachmentUploadResponse
  status: 201
}

export type uploadAttachmentApiAttachmentsUploadPostResponse401 = {
  data: ErrorResponse
  status: 401
}

export type uploadAttachmentApiAttachmentsUploadPostResponse403 = {
  data: ErrorResponse
  status: 403
}

export type uploadAttachmentApiAttachmentsUploadPostResponse404 = {
  data: ErrorResponse
  status: 404
}

export type uploadAttachmentApiAttachmentsUploadPostResponse422 = {
  data: ErrorResponse
  status: 422
}

export type uploadAttachmentApiAttachmentsUploadPostResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type uploadAttachmentApiAttachmentsUploadPostResponseSuccess = (uploadAttachmentApiAttachmentsUploadPostResponse201) & {
  headers: Headers;
};
export type uploadAttachmentApiAttachmentsUploadPostResponseError = (uploadAttachmentApiAttachmentsUploadPostResponse401 | uploadAttachmentApiAttachmentsUploadPostResponse403 | uploadAttachmentApiAttachmentsUploadPostResponse404 | uploadAttachmentApiAttachmentsUploadPostResponse422 | uploadAttachmentApiAttachmentsUploadPostResponse429) & {
  headers: Headers;
};

export type uploadAttachmentApiAttachmentsUploadPostResponse = (uploadAttachmentApiAttachmentsUploadPostResponseSuccess | uploadAttachmentApiAttachmentsUploadPostResponseError)

export const getUploadAttachmentApiAttachmentsUploadPostUrl = () => {


  

  return `/api/attachments/upload`
}

export const uploadAttachmentApiAttachmentsUploadPost = async (bodyUploadAttachmentApiAttachmentsUploadPost: BodyUploadAttachmentApiAttachmentsUploadPost, options?: RequestInit): Promise<uploadAttachmentApiAttachmentsUploadPostResponse> => {
    const formData = new FormData();
formData.append(`file`, bodyUploadAttachmentApiAttachmentsUploadPost.file);
formData.append(`entity_type`, bodyUploadAttachmentApiAttachmentsUploadPost.entity_type);
formData.append(`entity_id`, bodyUploadAttachmentApiAttachmentsUploadPost.entity_id.toString())
if(bodyUploadAttachmentApiAttachmentsUploadPost.title !== undefined) {
 formData.append(`title`, bodyUploadAttachmentApiAttachmentsUploadPost.title);
 }
if(bodyUploadAttachmentApiAttachmentsUploadPost.description !== undefined) {
 formData.append(`description`, bodyUploadAttachmentApiAttachmentsUploadPost.description);
 }

  return customInstance<uploadAttachmentApiAttachmentsUploadPostResponse>(getUploadAttachmentApiAttachmentsUploadPostUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
);}




export const getUploadAttachmentApiAttachmentsUploadPostMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAttachmentApiAttachmentsUploadPost>>, TError,{data: BodyUploadAttachmentApiAttachmentsUploadPost}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadAttachmentApiAttachmentsUploadPost>>, TError,{data: BodyUploadAttachmentApiAttachmentsUploadPost}, TContext> => {

const mutationKey = ['uploadAttachmentApiAttachmentsUploadPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadAttachmentApiAttachmentsUploadPost>>, {data: BodyUploadAttachmentApiAttachmentsUploadPost}> = (props) => {
          const {data} = props ?? {};

          return  uploadAttachmentApiAttachmentsUploadPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadAttachmentApiAttachmentsUploadPostMutationResult = NonNullable<Awaited<ReturnType<typeof uploadAttachmentApiAttachmentsUploadPost>>>
    export type UploadAttachmentApiAttachmentsUploadPostMutationBody = BodyUploadAttachmentApiAttachmentsUploadPost
    export type UploadAttachmentApiAttachmentsUploadPostMutationError = ErrorResponse

    /**
 * @summary Upload Attachment
 */
export const useUploadAttachmentApiAttachmentsUploadPost = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadAttachmentApiAttachmentsUploadPost>>, TError,{data: BodyUploadAttachmentApiAttachmentsUploadPost}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadAttachmentApiAttachmentsUploadPost>>,
        TError,
        {data: BodyUploadAttachmentApiAttachmentsUploadPost},
        TContext
      > => {
      return useMutation(getUploadAttachmentApiAttachmentsUploadPostMutationOptions(options), queryClient);
    }
    /**
 * List all attachments for a specific entity (lesson or assignment).
 * @summary List Entity Attachments
 */
export type listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse200 = {
  data: AttachmentListResponse
  status: 200
}

export type listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponseSuccess = (listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse200) & {
  headers: Headers;
};
export type listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponseError = (listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse401 | listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse403 | listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse404 | listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse422 | listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse429) & {
  headers: Headers;
};

export type listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse = (listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponseSuccess | listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponseError)

export const getListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetUrl = (entityType: AttachmentEntity,
    entityId: number,) => {


  

  return `/api/attachments/entity/${entityType}/${entityId}`
}

export const listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet = async (entityType: AttachmentEntity,
    entityId: number, options?: RequestInit): Promise<listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse> => {
  
  return customInstance<listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetResponse>(getListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetUrl(entityType,entityId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetQueryKey = (entityType: AttachmentEntity,
    entityId: number,) => {
    return [
    `/api/attachments/entity/${entityType}/${entityId}`
    ] as const;
    }

    
export const getListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetQueryOptions = <TData = Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError = ErrorResponse>(entityType: AttachmentEntity,
    entityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetQueryKey(entityType,entityId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>> = ({ signal }) => listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet(entityType,entityId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(entityType && entityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>>
export type ListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetQueryError = ErrorResponse


export function useListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet<TData = Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError = ErrorResponse>(
 entityType: AttachmentEntity,
    entityId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>,
          TError,
          Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet<TData = Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError = ErrorResponse>(
 entityType: AttachmentEntity,
    entityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>,
          TError,
          Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet<TData = Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError = ErrorResponse>(
 entityType: AttachmentEntity,
    entityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Entity Attachments
 */

export function useListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet<TData = Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError = ErrorResponse>(
 entityType: AttachmentEntity,
    entityId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListEntityAttachmentsApiAttachmentsEntityEntityTypeEntityIdGetQueryOptions(entityType,entityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get attachment details by ID.
 * @summary Get Attachment
 */
export type getAttachmentApiAttachmentsAttachmentIdGetResponse200 = {
  data: AttachmentRead
  status: 200
}

export type getAttachmentApiAttachmentsAttachmentIdGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type getAttachmentApiAttachmentsAttachmentIdGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type getAttachmentApiAttachmentsAttachmentIdGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type getAttachmentApiAttachmentsAttachmentIdGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type getAttachmentApiAttachmentsAttachmentIdGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type getAttachmentApiAttachmentsAttachmentIdGetResponseSuccess = (getAttachmentApiAttachmentsAttachmentIdGetResponse200) & {
  headers: Headers;
};
export type getAttachmentApiAttachmentsAttachmentIdGetResponseError = (getAttachmentApiAttachmentsAttachmentIdGetResponse401 | getAttachmentApiAttachmentsAttachmentIdGetResponse403 | getAttachmentApiAttachmentsAttachmentIdGetResponse404 | getAttachmentApiAttachmentsAttachmentIdGetResponse422 | getAttachmentApiAttachmentsAttachmentIdGetResponse429) & {
  headers: Headers;
};

export type getAttachmentApiAttachmentsAttachmentIdGetResponse = (getAttachmentApiAttachmentsAttachmentIdGetResponseSuccess | getAttachmentApiAttachmentsAttachmentIdGetResponseError)

export const getGetAttachmentApiAttachmentsAttachmentIdGetUrl = (attachmentId: number,) => {


  

  return `/api/attachments/${attachmentId}`
}

export const getAttachmentApiAttachmentsAttachmentIdGet = async (attachmentId: number, options?: RequestInit): Promise<getAttachmentApiAttachmentsAttachmentIdGetResponse> => {
  
  return customInstance<getAttachmentApiAttachmentsAttachmentIdGetResponse>(getGetAttachmentApiAttachmentsAttachmentIdGetUrl(attachmentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAttachmentApiAttachmentsAttachmentIdGetQueryKey = (attachmentId: number,) => {
    return [
    `/api/attachments/${attachmentId}`
    ] as const;
    }

    
export const getGetAttachmentApiAttachmentsAttachmentIdGetQueryOptions = <TData = Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError = ErrorResponse>(attachmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAttachmentApiAttachmentsAttachmentIdGetQueryKey(attachmentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>> = ({ signal }) => getAttachmentApiAttachmentsAttachmentIdGet(attachmentId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(attachmentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAttachmentApiAttachmentsAttachmentIdGetQueryResult = NonNullable<Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>>
export type GetAttachmentApiAttachmentsAttachmentIdGetQueryError = ErrorResponse


export function useGetAttachmentApiAttachmentsAttachmentIdGet<TData = Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError = ErrorResponse>(
 attachmentId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttachmentApiAttachmentsAttachmentIdGet<TData = Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError = ErrorResponse>(
 attachmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>,
          TError,
          Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAttachmentApiAttachmentsAttachmentIdGet<TData = Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError = ErrorResponse>(
 attachmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Attachment
 */

export function useGetAttachmentApiAttachmentsAttachmentIdGet<TData = Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError = ErrorResponse>(
 attachmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAttachmentApiAttachmentsAttachmentIdGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAttachmentApiAttachmentsAttachmentIdGetQueryOptions(attachmentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update attachment metadata (title, description).
Only teachers and admins can update.
 * @summary Update Attachment
 */
export type updateAttachmentApiAttachmentsAttachmentIdPatchResponse200 = {
  data: AttachmentRead
  status: 200
}

export type updateAttachmentApiAttachmentsAttachmentIdPatchResponse401 = {
  data: ErrorResponse
  status: 401
}

export type updateAttachmentApiAttachmentsAttachmentIdPatchResponse403 = {
  data: ErrorResponse
  status: 403
}

export type updateAttachmentApiAttachmentsAttachmentIdPatchResponse404 = {
  data: ErrorResponse
  status: 404
}

export type updateAttachmentApiAttachmentsAttachmentIdPatchResponse422 = {
  data: ErrorResponse
  status: 422
}

export type updateAttachmentApiAttachmentsAttachmentIdPatchResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type updateAttachmentApiAttachmentsAttachmentIdPatchResponseSuccess = (updateAttachmentApiAttachmentsAttachmentIdPatchResponse200) & {
  headers: Headers;
};
export type updateAttachmentApiAttachmentsAttachmentIdPatchResponseError = (updateAttachmentApiAttachmentsAttachmentIdPatchResponse401 | updateAttachmentApiAttachmentsAttachmentIdPatchResponse403 | updateAttachmentApiAttachmentsAttachmentIdPatchResponse404 | updateAttachmentApiAttachmentsAttachmentIdPatchResponse422 | updateAttachmentApiAttachmentsAttachmentIdPatchResponse429) & {
  headers: Headers;
};

export type updateAttachmentApiAttachmentsAttachmentIdPatchResponse = (updateAttachmentApiAttachmentsAttachmentIdPatchResponseSuccess | updateAttachmentApiAttachmentsAttachmentIdPatchResponseError)

export const getUpdateAttachmentApiAttachmentsAttachmentIdPatchUrl = (attachmentId: number,) => {


  

  return `/api/attachments/${attachmentId}`
}

export const updateAttachmentApiAttachmentsAttachmentIdPatch = async (attachmentId: number,
    attachmentUpdate: AttachmentUpdate, options?: RequestInit): Promise<updateAttachmentApiAttachmentsAttachmentIdPatchResponse> => {
  
  return customInstance<updateAttachmentApiAttachmentsAttachmentIdPatchResponse>(getUpdateAttachmentApiAttachmentsAttachmentIdPatchUrl(attachmentId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      attachmentUpdate,)
  }
);}




export const getUpdateAttachmentApiAttachmentsAttachmentIdPatchMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAttachmentApiAttachmentsAttachmentIdPatch>>, TError,{attachmentId: number;data: AttachmentUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAttachmentApiAttachmentsAttachmentIdPatch>>, TError,{attachmentId: number;data: AttachmentUpdate}, TContext> => {

const mutationKey = ['updateAttachmentApiAttachmentsAttachmentIdPatch'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAttachmentApiAttachmentsAttachmentIdPatch>>, {attachmentId: number;data: AttachmentUpdate}> = (props) => {
          const {attachmentId,data} = props ?? {};

          return  updateAttachmentApiAttachmentsAttachmentIdPatch(attachmentId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAttachmentApiAttachmentsAttachmentIdPatchMutationResult = NonNullable<Awaited<ReturnType<typeof updateAttachmentApiAttachmentsAttachmentIdPatch>>>
    export type UpdateAttachmentApiAttachmentsAttachmentIdPatchMutationBody = AttachmentUpdate
    export type UpdateAttachmentApiAttachmentsAttachmentIdPatchMutationError = ErrorResponse

    /**
 * @summary Update Attachment
 */
export const useUpdateAttachmentApiAttachmentsAttachmentIdPatch = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAttachmentApiAttachmentsAttachmentIdPatch>>, TError,{attachmentId: number;data: AttachmentUpdate}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAttachmentApiAttachmentsAttachmentIdPatch>>,
        TError,
        {attachmentId: number;data: AttachmentUpdate},
        TContext
      > => {
      return useMutation(getUpdateAttachmentApiAttachmentsAttachmentIdPatchMutationOptions(options), queryClient);
    }
    /**
 * Delete an attachment.

- **permanent**: If true, permanently delete file from storage.
                If false (default), soft delete (keep file, mark as deleted).
 * @summary Delete Attachment
 */
export type deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse204 = {
  data: void
  status: 204
}

export type deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse401 = {
  data: ErrorResponse
  status: 401
}

export type deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse403 = {
  data: ErrorResponse
  status: 403
}

export type deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse404 = {
  data: ErrorResponse
  status: 404
}

export type deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse422 = {
  data: ErrorResponse
  status: 422
}

export type deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type deleteAttachmentApiAttachmentsAttachmentIdDeleteResponseSuccess = (deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse204) & {
  headers: Headers;
};
export type deleteAttachmentApiAttachmentsAttachmentIdDeleteResponseError = (deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse401 | deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse403 | deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse404 | deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse422 | deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse429) & {
  headers: Headers;
};

export type deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse = (deleteAttachmentApiAttachmentsAttachmentIdDeleteResponseSuccess | deleteAttachmentApiAttachmentsAttachmentIdDeleteResponseError)

export const getDeleteAttachmentApiAttachmentsAttachmentIdDeleteUrl = (attachmentId: number,
    params?: DeleteAttachmentApiAttachmentsAttachmentIdDeleteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/attachments/${attachmentId}?${stringifiedParams}` : `/api/attachments/${attachmentId}`
}

export const deleteAttachmentApiAttachmentsAttachmentIdDelete = async (attachmentId: number,
    params?: DeleteAttachmentApiAttachmentsAttachmentIdDeleteParams, options?: RequestInit): Promise<deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse> => {
  
  return customInstance<deleteAttachmentApiAttachmentsAttachmentIdDeleteResponse>(getDeleteAttachmentApiAttachmentsAttachmentIdDeleteUrl(attachmentId,params),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteAttachmentApiAttachmentsAttachmentIdDeleteMutationOptions = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttachmentApiAttachmentsAttachmentIdDelete>>, TError,{attachmentId: number;params?: DeleteAttachmentApiAttachmentsAttachmentIdDeleteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteAttachmentApiAttachmentsAttachmentIdDelete>>, TError,{attachmentId: number;params?: DeleteAttachmentApiAttachmentsAttachmentIdDeleteParams}, TContext> => {

const mutationKey = ['deleteAttachmentApiAttachmentsAttachmentIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAttachmentApiAttachmentsAttachmentIdDelete>>, {attachmentId: number;params?: DeleteAttachmentApiAttachmentsAttachmentIdDeleteParams}> = (props) => {
          const {attachmentId,params} = props ?? {};

          return  deleteAttachmentApiAttachmentsAttachmentIdDelete(attachmentId,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteAttachmentApiAttachmentsAttachmentIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAttachmentApiAttachmentsAttachmentIdDelete>>>
    
    export type DeleteAttachmentApiAttachmentsAttachmentIdDeleteMutationError = ErrorResponse

    /**
 * @summary Delete Attachment
 */
export const useDeleteAttachmentApiAttachmentsAttachmentIdDelete = <TError = ErrorResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteAttachmentApiAttachmentsAttachmentIdDelete>>, TError,{attachmentId: number;params?: DeleteAttachmentApiAttachmentsAttachmentIdDeleteParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteAttachmentApiAttachmentsAttachmentIdDelete>>,
        TError,
        {attachmentId: number;params?: DeleteAttachmentApiAttachmentsAttachmentIdDeleteParams},
        TContext
      > => {
      return useMutation(getDeleteAttachmentApiAttachmentsAttachmentIdDeleteMutationOptions(options), queryClient);
    }
    /**
 * Download an attachment file.
Returns the file as a streaming response.
 * @summary Download Attachment
 */
export type downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse200 = {
  data: unknown
  status: 200
}

export type downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponseSuccess = (downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse200) & {
  headers: Headers;
};
export type downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponseError = (downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse401 | downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse403 | downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse404 | downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse422 | downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse429) & {
  headers: Headers;
};

export type downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse = (downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponseSuccess | downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponseError)

export const getDownloadAttachmentApiAttachmentsAttachmentIdDownloadGetUrl = (attachmentId: number,) => {


  

  return `/api/attachments/${attachmentId}/download`
}

export const downloadAttachmentApiAttachmentsAttachmentIdDownloadGet = async (attachmentId: number, options?: RequestInit): Promise<downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse> => {
  
  return customInstance<downloadAttachmentApiAttachmentsAttachmentIdDownloadGetResponse>(getDownloadAttachmentApiAttachmentsAttachmentIdDownloadGetUrl(attachmentId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getDownloadAttachmentApiAttachmentsAttachmentIdDownloadGetQueryKey = (attachmentId: number,) => {
    return [
    `/api/attachments/${attachmentId}/download`
    ] as const;
    }

    
export const getDownloadAttachmentApiAttachmentsAttachmentIdDownloadGetQueryOptions = <TData = Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError = ErrorResponse>(attachmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadAttachmentApiAttachmentsAttachmentIdDownloadGetQueryKey(attachmentId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>> = ({ signal }) => downloadAttachmentApiAttachmentsAttachmentIdDownloadGet(attachmentId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(attachmentId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DownloadAttachmentApiAttachmentsAttachmentIdDownloadGetQueryResult = NonNullable<Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>>
export type DownloadAttachmentApiAttachmentsAttachmentIdDownloadGetQueryError = ErrorResponse


export function useDownloadAttachmentApiAttachmentsAttachmentIdDownloadGet<TData = Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError = ErrorResponse>(
 attachmentId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAttachmentApiAttachmentsAttachmentIdDownloadGet<TData = Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError = ErrorResponse>(
 attachmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>,
          TError,
          Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDownloadAttachmentApiAttachmentsAttachmentIdDownloadGet<TData = Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError = ErrorResponse>(
 attachmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Download Attachment
 */

export function useDownloadAttachmentApiAttachmentsAttachmentIdDownloadGet<TData = Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError = ErrorResponse>(
 attachmentId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof downloadAttachmentApiAttachmentsAttachmentIdDownloadGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDownloadAttachmentApiAttachmentsAttachmentIdDownloadGetQueryOptions(attachmentId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * List all attachments with optional filtering.
Only teachers and admins can list all attachments.
 * @summary List Attachments
 */
export type listAttachmentsApiAttachmentsGetResponse200 = {
  data: AttachmentListResponse
  status: 200
}

export type listAttachmentsApiAttachmentsGetResponse401 = {
  data: ErrorResponse
  status: 401
}

export type listAttachmentsApiAttachmentsGetResponse403 = {
  data: ErrorResponse
  status: 403
}

export type listAttachmentsApiAttachmentsGetResponse404 = {
  data: ErrorResponse
  status: 404
}

export type listAttachmentsApiAttachmentsGetResponse422 = {
  data: ErrorResponse
  status: 422
}

export type listAttachmentsApiAttachmentsGetResponse429 = {
  data: ErrorResponse
  status: 429
}
    
export type listAttachmentsApiAttachmentsGetResponseSuccess = (listAttachmentsApiAttachmentsGetResponse200) & {
  headers: Headers;
};
export type listAttachmentsApiAttachmentsGetResponseError = (listAttachmentsApiAttachmentsGetResponse401 | listAttachmentsApiAttachmentsGetResponse403 | listAttachmentsApiAttachmentsGetResponse404 | listAttachmentsApiAttachmentsGetResponse422 | listAttachmentsApiAttachmentsGetResponse429) & {
  headers: Headers;
};

export type listAttachmentsApiAttachmentsGetResponse = (listAttachmentsApiAttachmentsGetResponseSuccess | listAttachmentsApiAttachmentsGetResponseError)

export const getListAttachmentsApiAttachmentsGetUrl = (params?: ListAttachmentsApiAttachmentsGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/attachments/?${stringifiedParams}` : `/api/attachments/`
}

export const listAttachmentsApiAttachmentsGet = async (params?: ListAttachmentsApiAttachmentsGetParams, options?: RequestInit): Promise<listAttachmentsApiAttachmentsGetResponse> => {
  
  return customInstance<listAttachmentsApiAttachmentsGetResponse>(getListAttachmentsApiAttachmentsGetUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListAttachmentsApiAttachmentsGetQueryKey = (params?: ListAttachmentsApiAttachmentsGetParams,) => {
    return [
    `/api/attachments/`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getListAttachmentsApiAttachmentsGetQueryOptions = <TData = Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError = ErrorResponse>(params?: ListAttachmentsApiAttachmentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListAttachmentsApiAttachmentsGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>> = ({ signal }) => listAttachmentsApiAttachmentsGet(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListAttachmentsApiAttachmentsGetQueryResult = NonNullable<Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>>
export type ListAttachmentsApiAttachmentsGetQueryError = ErrorResponse


export function useListAttachmentsApiAttachmentsGet<TData = Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError = ErrorResponse>(
 params: undefined |  ListAttachmentsApiAttachmentsGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>,
          TError,
          Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAttachmentsApiAttachmentsGet<TData = Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError = ErrorResponse>(
 params?: ListAttachmentsApiAttachmentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>,
          TError,
          Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListAttachmentsApiAttachmentsGet<TData = Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError = ErrorResponse>(
 params?: ListAttachmentsApiAttachmentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Attachments
 */

export function useListAttachmentsApiAttachmentsGet<TData = Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError = ErrorResponse>(
 params?: ListAttachmentsApiAttachmentsGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listAttachmentsApiAttachmentsGet>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListAttachmentsApiAttachmentsGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




